### PR TITLE
Fix some typos, sentence structures, and punctuation in the documentation

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by jmrodri — APPROVED** [review]
/lgtm

**Comment by jmrodri** [comment]
@sanjacodes THIS IS AMAZING! Thank you very much for this. 🎉 👍🏽 ❤️ 📖

**Review by sandrobonazzola — APPROVED** [review]
/lgtm

**Review by laxmikantbpandhare — APPROVED** [review]
/lgtm great work!

**Pull request merged**
