### PR TITLE
OWNERS: add jberkhahn as reviewer

### PR DESCRIPTION
**Pull request by jberkhahn**
Hey there, applying for reviewership of Operator-SDK

Sponsor: @estroz 
Member for at least 3 months ✔️ 
Primary reviewer of 5 PRs:
#3096
#3668
#3879
#3708 (this is an issue but involved a substantial amount of investigation)
#2893

Reviewed/Merged 20 PRs:
#3096
#3668
#3879
#3708 (this is an issue but involved a substantial amount of investigation)
#2893
#3725
#3508
#3454 
#3413 
#3411 
#3375 
#3318 
#3296 
#3287 
#3247 
#2676
#2629
#3668
#3255
#3734

### CODE REVIEW

**Comment by estroz** [comment]
I'm sponsoring @jberkhahn to gain reviewer status.

Going to merge #3955 first.

**Review by estroz — APPROVED** [review]
/lgtm

**Comment by asmacdo** [comment]
Before merge this will need to be altered to update the OWNERS_ALIAS file instead.

**Comment by jberkhahn** [comment]
wait, so is #3955 being merged first or not?

**Comment by asmacdo** [comment]
@jberkhahn either way is fine with me. I didn't see the edit.

**Comment by estroz** [comment]
We can merge this and rebase #3955. I want a few more reviews on that one first.

**Pull request merged**
