### PR TITLE
spread "fix: (helm) - do not add owner references to resources that contain the Helm keep resource-policy annotation #4389" to ansible-operator

### PR DESCRIPTION
**Pull request by bas2k**
spread "fix: (helm) - do not add owner references to resources that contain the Helm keep resource-policy annotation #4389" for ansible-operator

**Description of the change:**
Spread "fix: (helm) - do not add owner references to resources that contain the Helm keep resource-policy annotation #4389" for ansible-operator

**Motivation for the change:**
We need such ability for ansible-operator, too.

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Comment by joelanford** [comment]
`helm.sh/resource-policy: keep` is a helm-specific annotation. I don't think we want to re-use this annotation in ansible operators.

We _could_ talk about supporting a similar annotation for ansible though.

**Comment by bas2k** [comment]
We're deploying helm charts along with doing other actions using ansible-operator and we're experiencing same issue as was fixed in #4389

**Comment by joelanford** [comment]
Yes, but if I understand this change correctly, then it means that ALL resources applied by an ansible operator would need to set a helm-specific annotation to prevent the injection of the owner reference, which seems wrong.

What I'm suggesting is that we teach the ansible operator about another similar annotation and use that when deciding whether to inject an owner reference.

In your case, you would then be able to include this annotation in your helm chart templates or potentially inject them as part of your ansible run.

**Comment by bas2k** [comment]
We're including this annotation in Helm charts, but it makes no sense as ansible-operator injects ownerRef.

**Comment by bas2k** [comment]
I see, that makes sense, thank you!

**Pull request closed without merging**
