### PR TITLE
Address issue #372, add Prerequisites section to README.md

### PR DESCRIPTION
**Pull request by benjaminapetersen**
Fix issue #372 

Suggestions to improve this welcome!

### CODE REVIEW

**Comment by hasbro17** [comment]
@benjaminapetersen Thanks for the suggested improvement.
The [user-guide](https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md) already has a [Prerequisites](https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md#prerequisites) section with a more complete list.

I would suggest we move that out from the user-guide into the README.
While gvm is a useful tool I would prefer to keep the requirements concise and generic and just point users to the source for Go and dep so they can install them however best fits their platform.

**Comment by hasbro17** [comment]
@benjaminapetersen Just ping here when you've updated the prerequisites section accordingly.

**Comment by hasbro17** [comment]
@benjaminapetersen Just double checking if you're still planning to update the PR as discussed above. If not I can close this and do it separately.

**Comment by benjaminapetersen** [comment]
Sorry about the delay --

I copied over the prerequisites from the user-guide but left them in both places.  Hopefully, that's not a maintenance headache, but it does seem helpful to a reader who picks with up either doc.

I did also add a "User Guide" heading above the one-liner for the user-guide.  Personally, I missed this link entirely as I skimmed headings.  Let me know if you feel this is too redundant.

**Comment by hasbro17** [comment]
LGTM

**Pull request merged**
