### PR TITLE
docs: small typo update

### PR DESCRIPTION
**Pull request by kreempuff**
**Description of the change:**
Small type in the markdown

**Motivation for the change:**
Makes the link cleaner

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Comment by jmrodri** [comment]
@kreempuff thank you for your submission. Could you please sign your commit? `git rebase HEAD~1 --signoff` should do it.

**Comment by jmrodri** [comment]
@kreempuff Thanks for the PR. Can you sign your commit? `git rebase HEAD~1 --signoff` should fix it.

**Comment by kreempuff** [comment]
> @kreempuff Thanks for the PR. Can you sign your commit? `git rebase HEAD~1 --signoff` should fix it.

Yes I'll do that today!

**Review by jmrodri — APPROVED** [review]
/lgtm

**Comment by kreempuff** [comment]
@jmrodri friendly ping

**Review by everettraven — APPROVED** [review]
/lgtm

**Comment by kreempuff** [comment]
How exciting 😱

**Pull request merged**
