### PR TITLE
add rollback-force annotation for helm operators

### PR DESCRIPTION
**Pull request by hensur**
**Description of the change:**
Adds a `helm.sdk.operatorframework.io/rollback-force` annotation. This allows running a possible rollback after a failed upgrade without `rollback.Force` set to `true`.

In order to not break the current behavior, this annotation only overrides the current default of `true` if it is explicitly set to `"false"`.

**Motivation for the change:**
I ran into issues with failed upgrades on charts with a `Service` of type `ClusterIP`. After the upgrade had failed, the operator ran a rollback (currently with `rollback.Fore = true`) action. This would fail because the Service could not be rolled back to its previous state, which did not include the `ClusterIP` field. Without the `ClusterIP` field set, kubernetes assumes it to be empty on a force apply. And since this field is immutable after creation, it can't be force set to an empty string.

Without `rollback.Force = true` this works without errors. (I think?!) kubernetes will  use a `Three-Way-Merge` when the old Service gets applied.

See https://github.com/helm/helm/issues/6378#issuecomment-735812673 for more details.

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [x] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [x] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Comment by camilamacedo86** [comment]
Hi @hensur, 

It is not passing in the CI, Could you please rebase with the master and check if it will work or if your change here broke something? Or is no longer it a requirement?

**Comment by hensur** [comment]
Hi @camilamacedo86!

I've rebased the PR, CI seems to pass now :)

Yes, we still need this, we are currently running a custom built helm-operator.

**Comment by thueske** [comment]
Hey @camilamacedo86, @asmacdo, @jmrodri – are there any updates? Running a custom built helm-operator is messy in many ways. We would be very happy if someone could take another look at the PR so that it gets into the master soon :)

**Review by camilamacedo86 — COMMENTED** [review]
Hi @hensur, 

It seems not rebased. By looking at the changes it shows fine for me. 
@jmrodri @fabianvf @asmacdo wdyt?

**Comment by asmacdo** [comment]
@hensur sorry this fell through the cracks! We get a ton of Github notifications, but we are much better at responding to slack.

Additionally, we now have a [helm operator working group](https://github.com/operator-framework/community/#helm-operator-plugins-working-group) to stay on top of things like this. 

I'm going to close for now, but please feel free to reopen. If you do, please [reach out ](https://github.com/operator-framework/community/#contact-4) and we will make sure to get this through.

**Pull request closed without merging**
