### PR TITLE
Display simple installation first

### PR DESCRIPTION
**Pull request by nidin**
**Description of the change:**
operator-sdk installation documentation update.
Moved `brew install operator-sdk` to the top since it's the simplest installation method.

**Motivation for the change:**
Visitors only see `brew install operator-sdk` after downloading from Github method.

### CODE REVIEW

**Comment by joelanford** [comment]
@nidin This looks good to me. However, I just merged #1743, which adds links to each section at the top of the file. Could you fix the merge conflict?

**Comment by nidin** [comment]
Thanks. I’ll fix it.

**Comment by nidin** [comment]
@joelanford Conflicts resolved and reordered the links. However, Github web interface doesn't provide rebase option for conflict resolution so I merged the master into my branch. If rebasing is necessary I can create another PR.

**Pull request merged**
