### PR TITLE
docs: Add useful links to the README

### PR DESCRIPTION
**Pull request by hickeyma**
**Description of the change:**

Add the following useful links:
- Contribution guide
- Different communication channels like Slack, Email, Sig groups etc.
- Project meetings

**Motivation for the change:**

This is very useful information to have available at finger tips when land on the repo. It is something that is very helpful for a new person to the project and encourages the person to contribute. It also helpful for more experienced person to be able to access easily.

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Review by camilamacedo86 — APPROVED** [review]
/lgtm

**Review by estroz — APPROVED** [review]
/lgtm

**Comment by estroz** [comment]
Thanks @hickeyma

**Comment by hickeyma** [comment]
Thanks @camilamacedo86 @estroz for review and merge.

**Pull request merged**
