### PR TITLE
ci: add ansible-operator-base image and manual build workflow

### PR DESCRIPTION
**Pull request by estroz**
**Description of the change:**
- images/ansible-operator/base.Dockerfile: Dockerfile for the ansible-operator-base image
- .github/workflows/deploy-manual.yml: start workflows manually, namely the ansible-operator-base image deployment job

**Motivation for the change:** the ansible-operator image takes awhile to build, so it would be nice to build a base image containing the long-running dependency installation steps every so often, ex. when dependencies are updated.

/area dependency

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Comment by estroz** [comment]
The default tag would look like
```
quay.io/operator-framework/ansible-operator-base:v1.4.0-24-g0c75f7af1801373a3c85e3fb728dd2dccfd6a851
```
Which would then be pinned in `images/ansible-operator/Dockerfile` like
```dockerfile
FROM quay.io/operator-framework/ansible-operator-base:v1.4.0-24-g0c75f7af1801373a3c85e3fb728dd2dccfd6a851

ARG BIN=bin/ansible-operator
COPY $BIN /usr/local/bin/ansible-operator

CMD ["/usr/local/bin/ansible-operator", "run", "--watches-file=./watches.yaml"]
```

**Review by camilamacedo86 — APPROVED** [review]
I understand that we are only adding this one because it is required for we speeding the process to build the ansible image. 

It is not required for helm because the only ansible one has many deps. 
I am ok with 👍

**Review by varshaprasad96 — APPROVED** [review]

**Pull request merged**
