### PR TITLE
refac - to reduce complexity in the helm reconcile

### PR DESCRIPTION
**Pull request by camilamacedo86**
**Description of the change:**
Reduced the complexity by centralizing status impl in the model. 

**Motivation for the change:**

```
pkg/helm/controller/reconcile.go:65:1: cyclomatic complexity 35 of func `(HelmOperatorReconciler).Reconcile` is high (> 30) (gocyclo)
func (r HelmOperatorReconciler) Reconcile(request reconcile.Request) (reconcile.Result, error) {
```

Part of :  #2226

### CODE REVIEW

**Comment by shawn-hurley** [comment]
what is the measure of complexity that is being saved here?

**Comment by camilamacedo86** [comment]
Hi @shawn-hurley, 

The "Go Report Card" will report any complexity > 15. See: https://goreportcard.com/report/github.com/operator-framework/operator-sdk#gocyclo

But for us, would be great we are able to enable the gocyclo lint check which is >30(default value, we can customize it in the future if we want). See:

```
pkg/helm/controller/reconcile.go:65:1: cyclomatic complexity 35 of func `(HelmOperatorReconciler).Reconcile` is high (> 30) (gocyclo)
func (r HelmOperatorReconciler) Reconcile(request reconcile.Request) (reconcile.Result, error) { 
```

PS.: It is a very low priority since the goal is to improve the DX and maintenance ability, but I will try to address them in my spare time for we enable the last default check which is missing.

**Comment by jmrodri** [comment]
This is definitely low priority. While I think these tools are valuable, I think this makes things more complex to maintain. Because of the indirection of having to go to yet another method to find where the condition is being set. I don't like the precedence this sets since the previous code wasn't that complex.

**Comment by camilamacedo86** [comment]
Hi @jmrodri, 

> This is definitely low priority. While I think these tools are valuable, I think this makes things more complex to maintain. Because of the indirection of having to go to yet another method to find where the condition is being set. I don't like the precedence this sets since the previous code wasn't that complex.

Thank you for your input. I am not sure if I am following your comment.

The reconcile will setStatusCondionals for each scenario, then when I am looking at the reconcile I would like to understand it by checking for example: 

`If an error in the reconcile occurs which not allow it to continue then the`IrreconcilableConditionalStatus` will be set with the error.`  

So, if I'd like to understand what is required and the minute details of each status implementation I should check the status definitions where its code are centralized. 

So, how it would increase its complexity to maintain instead of otherwise? How to centralize the implementation to handle each kind of status can make it harder to get maintained instead of otherwise? How to remove the duplication in the code by centralizing it can increase its complexity?

**Comment by camilamacedo86** [comment]
Hi @jmrodri,
 
Thank you for your input. I am not sure if I am following your comment.

> This is definitely low priority. While I think these tools are valuable, I think this makes things more complex to maintain. Because of the indirection of having to go to yet another method to find where the condition is being set. I don't like the precedence this sets since the previous code wasn't that complex.

The reconcile will setStatusCondionals for each scenario, then when I am looking at the reconcile I would like to understand it by checking for example: 

> If an error in the reconcile occurs which not allow it to continue then the`IrreconcilableConditionalStatus` will be set with the error.

So, if I’d like to understand what is required and the minute details of each set status implementation I should check the status definitions where its code are centralized. 

So, how it would increase its complexity to maintain instead of otherwise? How to remove the duplication in the code by centralizing it can increase its complexity instead of otherwise? How to encapsulate each status logic required for each possible type where the types and status are defined can make things harder than otherwise? Also, who knows more about the status than the status definer? Who knows more about the types than the types definer?  Please, let me know if it makes more sense now?

**Comment by jmrodri** [comment]
So I looked at the reconcile method and I agree that it is too complex. `gocyclo` uses the following to determine the score:
```
 1 is the base complexity of a function
+1 for each 'if', 'for', 'case', '&&' or '||'
```
Source is from [gocyclo readme](https://github.com/alecthomas/gocyclo/blob/master/README.md)

Refactoring the status conditions is not what has reduced the score of this function, it was the removal of 2 `if` statements that reduces the `gocyclo` score from 35 to 33. The complexity value set by golangci-lint is *30*. So this PR still won't fix the _complexity_.

I think a better approach to reducing the complexity is to re-evalute the entire method and try to remove some of the branches taken by the *27* if statements. Even if we disregard the 14 `if err ` statements, that still leaves *13* `if` statements.

So my recommendation is we CLOSE this PR. Re-evalute the `Reconcile` function and do a much bigger refactor to reduce the branching that is causing the complexity.

@camilamacedo86 @estroz @joelanford thoughts?

**Comment by joelanford** [comment]
@jmrodri :+1: to closing this.

I already have a much larger refactor in the works.

**Comment by joelanford** [comment]
https://github.com/joelanford/helm-operator if you're interested :)

**Comment by jmrodri** [comment]
Closing this per my comment and Joe's larger planned refactor.

**Pull request closed without merging**
