### PR TITLE
WIP: upgrade k8s.io/kube-state-metrics from v1.6.0 to latest version (v1.7.2)

### PR DESCRIPTION
**Pull request by camilamacedo86**
**Description of the change:**
upgrade k8s.io/kube-state-metrics from v1.6.0 to latest version (v1.7.2

**Motivation for the change:**

https://github.com/operator-framework/operator-sdk/issues/1925

### CODE REVIEW

**Comment by camilamacedo86** [comment]
HI folks, 

I am not facing the same issue locally. 

```
$ make tidy
Fetching https://proxy.golang.org/k8s.io/kube-state-metrics/pkg/collector/@v/list
Fetching https://proxy.golang.org/k8s.io/kube-state-metrics/pkg/@v/list
Fetching https://proxy.golang.org/k8s.io/kube-state-metrics/@v/list
Fetching https://proxy.golang.org/k8s.io/@v/list

```

Why the CI is not able to fetch them? What is missing to do here? 

c/c @jmrodri @estroz

**Comment by joelanford** [comment]
@camilamacedo86 I believe there are breaking changes in kube-state-metrics 1.7+ that break our APIs. I was looking at this a little yesterday too, and I have a WIP branch as well that has what I think are the necessary code changes:  https://github.com/joelanford/operator-sdk/compare/fa87ee6942e9...36abccabd4a1

Ideally we get this in before our next release since it already contains a bunch of breaking changes related to the controller-runtime and k8s version bump.

Feel free to apply this patch to your branch, or we can close this PR and I can re-open.

**Comment by camilamacedo86** [comment]
Hi @joelanford, 

I was expecting that something could break, however, the error in the travis is to run the `make tidy`. ee [here](https://travis-ci.org/operator-framework/operator-sdk/jobs/586474551#L1656). 

What I was trying to understand is why I cannot face the same issue. Probably the go cache and the libs installed. I would need clean all to try to reproduce it. 

Really thanks.

**Comment by joelanford** [comment]
Looks like the hash of the fetched `github.com/spf13/pflag@v1.0.4` was different than what `go.sum` was expecting: https://travis-ci.org/operator-framework/operator-sdk/jobs/586474551#L1450

I'm curious what steps you took to bump the `kube-state-metrics` version? There are many updates in `go.mod` that seem unrelated to bumping `kube-state-metrics`.

**Comment by camilamacedo86** [comment]
Hi @joelanford, 

Since you already have a branch with this change and the break changes solved I am closing this one.  Please, feel free to apply it.

**Pull request closed without merging**
