### PR TITLE
remove doc/sdk-cli-reference.md since the cli docs are gen automatica…

### PR DESCRIPTION
**Pull request by camilamacedo86**
**Description of the change:**
Remove doc/sdk-cli-reference.md since the cli docs are gen automatically now. so it is and will be outdated very easily. Also, shows have no longer purpose.

### CODE REVIEW

**Comment by camilamacedo86** [comment]
HI @joelanford and @asmacdo wdyt?

**Comment by joelanford** [comment]
@camilamacedo86 There are some things on the CLI reference that don't exist anywhere else (e.g. the [`operator-sdk new --type=helm` usages](https://github.com/operator-framework/operator-sdk/blob/master/doc/sdk-cli-reference.md#helm-project).

We should probably do a scrub and make sure we don't lose helpful info. It probably makes the most sense to move things like that to the actual cobra examples in the `cmd` subcommand definitions.

**Comment by camilamacedo86** [comment]
Hi @joelanford tks.
I raised this to get your inputs. 
I will track an issue in the repo for we work on that.

**Comment by camilamacedo86** [comment]
Done: https://github.com/operator-framework/operator-sdk/issues/2430

**Pull request closed without merging**
