### PR TITLE
Add missing "controller-tools" update instructions to the v1.25.0 migration guide

### PR DESCRIPTION
**Pull request by tiwalter**
Fixes https://github.com/operator-framework/operator-sdk/issues/6525.

### CODE REVIEW

**Review by OchiengEd — APPROVED** [review]
/lgtm

The default controller-tools version in operator-sdk v1.25.0 is `0.10.0` so this change will make updated repos match newly created operators.

**Review by jberkhahn — APPROVED** [review]

**Comment by jberkhahn** [comment]
this looks good, you just have to sign your commit and then we can merge it

**Comment by tiwalter** [comment]
I will do it next week. Currently, I'm abroad.

**Review by everettraven — APPROVED** [review]

**Pull request merged**
