### PR TITLE
OCPBUGS-11569: Update ubi to ubi-micro:8.7

### PR DESCRIPTION
**Pull request by oceanc80**
Bump to ubi-micro:8.7

### CODE REVIEW

**Review by varshaprasad96 — APPROVED** [review]
/lgtm
This change would bump hybrid operator plugin's commit to include the change in the [scaffolding](https://github.com/operator-framework/helm-operator-plugins/blob/7eacb666f7941ae3f1084c5b01fc26811e715379/testdata/hybrid/memcached-operator/Dockerfile#L20).

**Comment by everettraven** [comment]
closing and reopening to try and pick up CI fixes

**Review by everettraven — APPROVED** [review]
/lgtm

**Pull request merged**
