### PR TITLE
Add different prune options to Gopkg.toml

### PR DESCRIPTION
**Pull request by LiliC**
**Description of the change:**
Add prune options to operator-sdk `Gopkg.toml`.
https://golang.github.io/dep/docs/Gopkg.toml.html#prune

**Motivation for the change:**
Making use of the different prune options saves time and space when vendoring and removes the unused pkgs.

### CODE REVIEW

**Comment by AlexNPavel** [comment]
This makes sense for our repo, but we had issues with keeping pruning on in the generated projects with the controller-runtime refactor. Since the new projects don't have their APIs or controllers on creation, users need to rerun `dep ensure` after the do their first `add api` and `add controller`. It may be worth it in saved time and space, but we got quite a few issues opened which were related to needing to run `dep ensure` even without this change, which might pick up again if this gets merged. This needs a bit more discussion before enabling it for generated project imo.

**Comment by LiliC** [comment]
@AlexNPavel Yes, makes sense! 

Also it seems like the `/home/travis/gopath/src/github.com/example-inc/memcached-operator/vendor/k8s.io/code-generator/hack/boilerplate.go.txt` might have been pruned as well :D

**Comment by LiliC** [comment]
Main reason for this PR is that when the kube-state-metrics gets imported with the operator specific metric PR, I wanted to not import the whole of it but just the parts we will need otherwise it's a lot of pkgs that are not used.

**Comment by AlexNPavel** [comment]
@LiliC If it's just kube-state-metics, you can enable pruning just for that project. That might be a better way to handle this issue.

**Comment by LiliC** [comment]
@AlexNPavel Makes sense, will do that, thanks! Left the operator-sdk prune option as you agreed with that above.

**Pull request merged**
