### PR TITLE
Bumped the Golang version to 1.19 in pre-requisite documentation

### LINKED ISSUE #6385: wrong minimum version of go listed in prereqs in developer-guide
What is the URL of the document?

https://sdk.operatorframework.io/docs/contribution-guidelines/developer-guide/#prerequisites
Which section(s) is the issue in?

prerequisites
What needs fixing?

Doc says prereq is go version 1.18 but the go.mod file in the source says go 1.19.
Additional context

The source will not build if your version of Go is earlier than what is listed in the go.mod file.

### PR DESCRIPTION
**Pull request by ukumar009**
**Description of the change:**
Go.mod is using golang 1.19 and pre-requisite is using 1.18. So Incrementing the developer guide to meet the golang version.

Bumped the Golang version.

**Motivation for the change:**
#6385 

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [x] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [x] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

Closes #6385

### CODE REVIEW

**Review by varshaprasad96 — APPROVED** [review]
Thanks for the contribution @UdayKumar-Ch!

This probably _doesn't_ need a changelog, but its fine having it there!

/lgtm

**Comment by UdayKumar-Ch** [comment]
you're welcome @varshaprasad96

**Review by everettraven — APPROVED** [review]
/lgtm

**Comment by everettraven** [comment]
@ukumar009 Looks like the DCO check is failing. Once that is fixed we can merge this PR in. You should be able to follow the steps given in https://github.com/operator-framework/operator-sdk/pull/6386/checks?check_run_id=12461023493 to resolve this failure

**Comment by ukumar009** [comment]
> @ukumar009 Looks like the DCO check is failing. Once that is fixed we can merge this PR in. You should be able to follow the steps given in https://github.com/operator-framework/operator-sdk/pull/6386/checks?check_run_id=12461023493 to resolve this failure

Thank you @everettraven I fixed the DCO issue now.

**Comment by everettraven** [comment]
Overriding the docs link checker failures as I was able to access all the "failed" links. Merging.

**Pull request merged**
