### PR TITLE
run packagemanifests: registry server should use world-writable directory to write files

### LINKED ISSUE #3863: Operator-sdk run packagemanifests does not work on Openshift
#### What did you do?
Nothing

#### What did you expect to see?
Operator deploy with `run packagemanifests`

#### What did you see instead? Under which circumstances?
Pod crashloopbackoff with the following log
```
Error: unable to open database file
Usage:
   [flags]

Flags:
  -h, --help               help for this command
  -m, --manifests string   relative path to directory of manifests (default "manifests")
  -o, --output string      relative path to a sqlite file to create or overwrite (default "bundles.db")
      --permissive         allow registry load errors

panic: unable to open database file
```

#### Environment

**Operator type:**

**Kubernetes cluster type:**

`$ operator-sdk version`
Latest version

`$ go version` (if language is Go)

1.14.x

`$ kubectl version`

```bash
$ oc version
Client Version: v0.0.0-unknown
Server Version: 4.3.13
Kubernetes Version: v1.16.2
```

#### Possible Solution

Cd into `/tmp` over `/registry`

I also tested it to make sure it works on OCP 4.5.x https://github.com/operator-framework/operator-sdk/compare/master...Doout:fix-ocp-deployment

Another fix will be to give all users write access to `/registry` when building the image. 
#### Additional context

When I debug the pod (oc debug) and found that I get permission denied with touch which I assume the SQL package will also hit this (unable to open database file coming from SQL package)

```
/registry $ touch bundle.db
touch: bundle.db: Permission denied
```

When I run it as root, I face no issues. I assume the permission for /registry folder is not correct when it get deploy on OCP.
On OCP, UID is random while /registry ownership is root and no write access for any user

```
drwxr-xr-x    3 root     root            23 Sep  8 13:12 registry
```

### PR DESCRIPTION
**Pull request by joelanford**
**Description of the change:**
Write the `bundle.db` and `termination.log` file to `/tmp` when running the registry server for the `run packagemanifests` command.

**Motivation for the change:**
Resolves the issue raised [here](https://github.com/operator-framework/operator-sdk/pull/3856#issuecomment-688855166).

Fixes #3863 

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [x] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] ~Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)~

### CODE REVIEW

**Comment by joelanford** [comment]
@Doout can you try this branch out to see if it resolves this issue you brought up [here](https://github.com/operator-framework/operator-sdk/pull/3856#issuecomment-688855166)?

**Review by jmrodri — APPROVED** [review]
/lgtm

**Comment by Doout** [comment]
@joelanford I comment back on the issues, but still hit the permission denied with this PR.

**Comment by joelanford** [comment]
@Doout @jmccormick2001 I updated this PR to set the registry pod working directory to `/tmp`, spun up a 4.5 cluster, and confirmed that the registry pod started successfully with this latest change.

**Review by jmccormick2001 — APPROVED** [review]

**Comment by jmccormick2001** [comment]
one thing I noticed is that when the pod, memcached-operator-registry-server-675559c6d5-6fwm5, is started, it is using imagePullPolicy of Always...I wonder if this is intended?

**Comment by joelanford** [comment]
@jmccormick2001 `imagePullPolicy` defaults to `Always` when the image tag is `latest`; otherwise it defaults to `IfNotPresent`.

There's probably a separate discussion to be had about whether we should keep using `latest`, but this is what we've been using for the `run packagemanifests` command for awhile so that behavior hasn't changed.

**Pull request merged**
