### PR TITLE
OSDK-2303: Scorecard testOutput is tightly coupled with storage mountPath

### PR DESCRIPTION
**Pull request by apodhrad**
Signed-off-by: Andrej Podhradsky <apodhrad@redhat.com>

**Description of the change:**

**Motivation for the change:**

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Comment by jmrodri** [comment]
@apodhrad sorry for the late review. Because you changed the flag, that means the auto-generated CLI docs need to get updated. So if you run `make generate` this should update this file: `website/content/en/docs/cli/operator-sdk_scorecard.md`

**Comment by apodhrad** [comment]
@jmrodri thx, I will do that asap

**Comment by apodhrad** [comment]
Hi @jmrodri I don't know why 6 checks are still waiting for status to be reported. Could you have a look at it, please?

**Comment by apodhrad** [comment]
Hi @rashmigottipati @jmrodri is there something how I can "unblock" this PR, please?

**Review by theishshah — APPROVED** [review]
/lgtm

**Review by laxmikantbpandhare — APPROVED** [review]
/lgtm

**Pull request merged**
