### PR TITLE
pkg/*,internal/pkg/flags: move flags packages to internal/flags

### PR DESCRIPTION
**Pull request by joelanford**
**Description of the change:**
Moving `pkg/internal/flags` to `internal/pkg/flags/watch`

**Motivation for the change:**
We've been moving internal code into the root `internal` subtree, and we've recently created a `internal/pkg/flags` package, which means we've had both `internal/pkg/flags` and `pkg/internal/flags` which is somewhat confusing.

This moves `pkg/internal/flags` to a `internal/pkg/flags/watch` to consolidate internal flag-related code into the `internal/pkg/flags` subtree.

### CODE REVIEW

**Comment by shawn-hurley** [comment]
WDYT of just `internal/flags/watch`?

**Comment by joelanford** [comment]
@shawn-hurley Do you think there's a need for `internal/pkg` still, or should we also move `internal/pkg/scaffold` and `internal/pkg/scorecard` to be direct children of `internal`?

**Comment by shawn-hurley** [comment]
I just realized there was more in `internal/pkg/xxxx`. 

If these are not in pkg for whatever reason it doesn't make sense to add pkg to me. This is a nit though it won't "break" anything it just seems odd to me.

**Comment by joelanford** [comment]
The original thought was that `internal` may grow to contain more than just `pkg` type packages, but it doesn't seem like that's going to happen.  I'll move this to `internal/flags` and we can have follow-on PRs for `internal/pkg/scaffold` and `internal/pkg/scorecard`. WDYT?

**Pull request merged**
