### PR TITLE
removed customer-scorecard-tests binary that was inadvertly added

### PR DESCRIPTION
**Pull request by jmccormick2001**
**Description of the change:**
this PR removes the binary for custom-scorecard-test that was added by mistake into the repo.

**Motivation for the change:**

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Review by joelanford — CHANGES_REQUESTED** [review]
If I run `./hack/image/build-custom-scorecard-tests-image.sh`, it looks like that file comes back.

Can we build stuff in a temp directory and then clean it up as part of that script, similar to `hack/image/build-ansible-image.sh`?

**Comment by jmccormick2001** [comment]
> If I run `./hack/image/build-custom-scorecard-tests-image.sh`, it looks like that file comes back.
> 
> Can we build stuff in a temp directory and then clean it up as part of that script, similar to `hack/image/build-ansible-image.sh`?

I updated all the scorecard image build scripts to work like the ansible image build script (e.g. tmpdir).

**Review by joelanford — APPROVED** [review]
/lgtm

**Review by rashmigottipati — APPROVED** [review]
/lgtm

**Pull request merged**
