### PR TITLE
stop building "scorecard-storage", "scorecard-untar" images

### PR DESCRIPTION
**Pull request by acornett21**
**Description of the change:**
Remove "scorecard-storage", "scorecard-untar" from being built during the release process. I think this is the only place to change, though I am unsure if this is all the places.

**Motivation for the change:**
In order for scorecard tests to work in DCI and disconnected environments, images need to be referenced by `sha` and not a `tag`, this would stop these two testing images from getting rebuilt on release, since the rarely change.

- Relates: #6417 

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Review by tkrishtop — CHANGES_REQUESTED** [review]
Hi @acornett21, thank you for starting the PR.

It would also be nice to remove scorecard-untar and scorecard-storage from the Makefile  to avoid rebuilding the images: 
https://github.com/operator-framework/operator-sdk/blob/af14062577914e4c79c77d8a31d2cf808e5ed76b/Makefile#L95 

We could also fix the digests at the same time by using the current digests for [scorecard-storage](https://quay.io/repository/operator-framework/scorecard-storage?tab=tags) and [scorecard-untar](https://quay.io/repository/operator-framework/scorecard-untar?tab=tags):

```
quay.io/operator-framework/scorecard-storage@sha256:a3bfda71281393c7794cabdd39c563fb050d3020fd0b642ea164646bdd39a0e2

quay.io/operator-framework/scorecard-untar@sha256:2e728c5e67a7f4dec0df157a322dd5671212e8ae60f69137463bd4fdfbff8747
```

[Here is our previous PR](https://github.com/operator-framework/operator-sdk/pull/6393/files) for changing the digests. We need more or less the same here.

**Comment by acornett21** [comment]
@tkrishtop I wasn't sure if the maintainers also wanted the makefile changed or not, was hoping for their feedback on this. I think the `sha` changes should be a separate PR for two reasons, 1) to not confuse the intent of this PR, 2) incase a release is cut before this gets merged and the `shas` change. So the intent is the `sha` changes will be in a separate PR. Hope this makes sense.

**Comment by tkrishtop** [comment]
> @tkrishtop I wasn't sure if the maintainers also wanted the makefile changed or not, was hoping for their feedback on this. I think the `sha` changes should be a separate PR for two reasons, 1) to not confuse the intent of this PR, 2) incase a release is cut before this gets merged and the `shas` change. So the intent is the `sha` changes will be in a separate PR. Hope this makes sense.

1. @acornett21 agree, let's wait for @everettraven approval for Makefile.

2. The shas were already changed while cutting off the 1.28.1 release. The digests, currently used in the code, do not exist anymore, and the master branch is broken 

```
$ podman pull quay.io/operator-framework/scorecard-storage@sha256:f7bd62664a0b91034acb977a8bb4ebb76bc98a6e8bdb943eb84c8e364828f056
Trying to pull quay.io/operator-framework/scorecard-storage@sha256:f7bd62664a0b91034acb977a8bb4ebb76bc98a6e8bdb943eb84c8e364828f056...
Error: initializing source docker://quay.io/operator-framework/scorecard-storage@sha256:f7bd62664a0b91034acb977a8bb4ebb76bc98a6e8bdb943eb84c8e364828f056: reading manifest sha256:f7bd62664a0b91034acb977a8bb4ebb76bc98a6e8bdb943eb84c8e364828f056 in quay.io/operator-framework/scorecard-storage: manifest unknown
```

Since we have nothing to lose, I proposed to fix everything at once, but please do as you think better.

**Comment by tkrishtop** [comment]
Hi @varshaprasad96, can you please check the question about the Makefile above? I usually ask Bryce to help us out but he is off this week.

**Review by everettraven — APPROVED** [review]
/lgtm

@acornett21 the Makefile can be updated as part of this PR if you would like but I don't think it should block this PR from making it in. From what I recall, the Makefile target for building the images is just used for local building and isn't a part of the release pipeline.

**Comment by acornett21** [comment]
@everettraven I updated the makefile as well.

**Pull request merged**
