### PR TITLE
Release v1.12.0

### PR DESCRIPTION
**Pull request by jberkhahn**
This is a release PR for v1.12.0

@jmrodri

### CODE REVIEW

**Review by jmrodri — APPROVED** [review]
/lgtm

**Review by rashmigottipati — APPROVED** [review]
/lgtm

**Comment by rashmigottipati** [comment]
Missed seeing the testdata changes earlier. Looks like they're generated now. 

/lgtm

**Comment by varshaprasad96** [comment]
/lgtm
All the checks are passing now. Please feel free to merge.

**Pull request merged**
