### PR TITLE
remove deprecated github actions from CI workflows

### LINKED ISSUE #6130: CI: fix deprecated set-output and save-state in Github Actions
#### What did you do?
Ran GH Action. Github as deprecated the `set-output` and `save-state`. https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

#### What did you expect to see?
Expected it to run without any warnings

#### What did you see instead? Under which circumstances?

Deprecation errors
* freshen-images errors: https://github.com/operator-framework/operator-sdk/actions/runs/3376988518
* deploy-manual errors: https://github.com/operator-framework/operator-sdk/actions/runs/3370784834
* sanity errors: https://github.com/operator-framework/operator-sdk/actions/runs/3374754930

### PR DESCRIPTION
**Pull request by jberkhahn**
Fixes #6130

### CODE REVIEW

**Comment by jberkhahn** [comment]
/hold
trying to test this on my fork

**Comment by jberkhahn** [comment]
/hold
ok, looks like the check-if-only-run docs one works? so i think i did this right

**Review by everettraven — APPROVED** [review]
/lgtm

**Comment by jberkhahn** [comment]
you can see the run that went with the updated workflows on my fork here:  https://github.com/jberkhahn/operator-sdk/pull/177

Although I already reverted this commit off master on my fork.

**Review by jmrodri — APPROVED** [review]
/lgtm

**Pull request merged**
