### PR TITLE
website: Fix link to the pull requests that implements support for configuring a liveness probe for an Ansible operator.

### PR DESCRIPTION
**Pull request by timflannagan1**
Fix link to that points to the work that implements liveness probe handling for Ansible-based operators that was done during the 0.18 release.

**Description of the change:**

**Motivation for the change:**

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Comment by timflannagan1** [comment]
CC @camilamacedo86 - is the normal workflow for the sdk team to merge against the most recent release branch instead of master?

**Comment by joelanford** [comment]
@timflannagan1 Normal flow is if something is broken on master, merge there, and then backport to affected release branches.

**Comment by timflannagan1** [comment]
Ah, it looks like we may need to go down one more release branch? Still seeing the old PR link to the Ansible liveness probe work.

Screenshot from 2020-07-29 18-35-16

**Comment by timflannagan1** [comment]
I manually cherry-picked against the v0.18.x release branch: https://github.com/operator-framework/operator-sdk/pull/3606

**Pull request merged**
