### PR TITLE
Add bundle quickstart

### LINKED ISSUE #4241: docs: make OLM integration quickstart quick(er)
#### Describe the problem you need a feature to resolve.

The OLM integration "quickstart" is not a quickstart in the same manner as Go/Ansible/Helm quickstarts.

#### Describe the solution you'd like.

The existing OLM integration quickstart needs to be moved to a long-form "tutorial" page, and an actual quickstart needs to be written then linked to/inserted into existing Go/Ansible/Helm quickstarts.

/kind documentation

### PR DESCRIPTION
**Pull request by jberkhahn**
Create a bundle quickstart guide like the building-operators quickstarts. Change the existing bundle "quickstart" into a tutorial section. Change links elsewhere in the docs to point to the new quickstart.

Closes #4241

### CODE REVIEW

**Comment by jberkhahn** [comment]
This is WIP. do not merge

**Comment by jberkhahn** [comment]
This is ready to be reviewed.

**Review by jmrodri — APPROVED** [review]
/lgtm

**Pull request merged**
