### PR TITLE
Migration guide generation improvements

### PR DESCRIPTION
**Pull request by joelanford**
**Description of the change:**
- Change changelog fragment's migration body from single-line string (`>`) to multi-line string (`|`)
- Use 🎉 instead of `:tada:` when migration guide is empty

**Motivation for the change:**
- The current template makes it too easy to accidentally define a single-line string for migration guide bodies. We've accidentally generated changelogs for previous versions that render incorrectly.
   - https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.16.0/
   - https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.14.0/
- When rendered as HTML on the docs site, empty migration guides just render `:tada:` as plain text. The expectation is for `:tada:` to render as 🎉 
   - https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.12.0/
   - https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.8.0/

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Comment by joelanford** [comment]
Fixed rendering preview:
- https://deploy-preview-5494--operator-sdk.netlify.app/docs/upgrading-sdk-version/v1.16.0/
- https://deploy-preview-5494--operator-sdk.netlify.app/docs/upgrading-sdk-version/v1.14.0/

Fixed emoji rendering:
- https://deploy-preview-5494--operator-sdk.netlify.app/docs/upgrading-sdk-version/v1.12.0/
- https://deploy-preview-5494--operator-sdk.netlify.app/docs/upgrading-sdk-version/v1.8.0/

**Review by varshaprasad96 — APPROVED** [review]
/lgtm

**Review by jmrodri — APPROVED** [review]
/lgtm

**Review by danhduykhan-code — APPROVED** [review]

**Review by danhduykhan-code — CHANGES_REQUESTED** [review]
danhduykhan@gmail.com

**Pull request merged**
