### PR TITLE
Update operator-capability-level diagram and file name

### PR DESCRIPTION
**Pull request by tlwu2013**
**Description of the change:**
Updated graphics for Operator Capability Level per the latest consensus. Relevant documentation is updated. Will create separated PRs for other docs that referencing these diagrams in other repos (`operatorhub.io`, `operatorhub-docs`) once this PR got merged.

**Motivation for the change:**
Update operator capability level diagrams to reflect the latest consensus.

### CODE REVIEW

**Comment by tlwu2013** [comment]
cc @dmesser

**Comment by tlwu2013** [comment]
Hey @AlexNPavel , @shawn-hurley , could you help review this PR?  Thanks!  
(cc @dmesser , @jeremylinlin )

**Comment by galletti94** [comment]
@estroz @shawn-hurley @AlexNPavel Anything more needed on our end to get this merged?

**Comment by estroz** [comment]
@galletti94 should be fine, just waiting for one more review from someone with write access.

**Pull request merged**
