### PR TITLE
Auto-generate cncf maintainers file from OWNERS and OWNERS_ALIASES

### PR DESCRIPTION
**Pull request by joelanford**
**Description of the change:**

Automatically generate a flattened maintainers file from the `OWNERS` and `OWNERS_ALIASES` files in the SDK repo.

**Motivation for the change:**

CNCF needs a single file listing individual maintainers to keep mailing lists updated. This requirement is incompatible with our existing `OWNERS` and `OWNERS_ALIASES` mappings.

See: https://github.com/operator-framework/operator-sdk/commit/575412115cd60452f0ee4d2abd04eab76f46741e#commitcomment-43450277

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] ~Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))~
- [ ] ~Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)~

### CODE REVIEW

**Comment by joelanford** [comment]
@amye Is the generated `.cncf-maintainers` file in this PR sufficient to automate the SDK maintainers list for CNCF?

**Comment by amye** [comment]
This should be fine, we just need the list in a readable format, but we need you all to tell us when these change. A comment on [maintainers.cncf.io](maintainers.cncf.io) is fine.

**Review by estroz — APPROVED** [review]
/lgtm

**Review by camilamacedo86 — APPROVED** [review]
/lgtm

**Pull request merged**
