### PR TITLE
(bugfix): `run bundle` and `run bundle-upgrade` - update registry pod index directory

### PR DESCRIPTION
**Pull request by everettraven**
The registry pod index directory now includes the CatalogSource name to prevent conflicts between indexes in the same directory

Signed-off-by: Bryce Palmer <bpalmer@redhat.com>

**Description of the change:**
Update the registry pod index directory to include the `CatalogSource` name.

**Motivation for the change:**
Potential fix for #5870 

`run bundle-upgrade` was not working properly when upgrading a traditionally (OLM) installed  operator for FBC indexes. It seems this issue is due to multiple indexes being in the same directory that have repeating package definitions.

This change makes it so that the directory indexes are stored in correlate to the `CatalogSource` that is created/used for the upgrade. This seems to have resolved the issue.

(This change also affects `run bundle` as it will now use the same directory logic for storing indexes)

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Comment by everettraven** [comment]
/hold 

needs more testing and discussion

**Comment by everettraven** [comment]
I performed some fairly extensive tests to verify that these changes work as expected and resolve the bug. From what I can tell, these changes do resolve the bug and work as expected.

<details>
<summary>
For more details on the tests expand this dropdown (warning this is a lot of stuff, ~400 lines of Markdown)
</summary>

run `make build` before testing to ensure using latest changes

## `run bundle`
1. `kind create cluster`
2. `./build/operator-sdk olm install`
3. `./build/operator-sdk run bundle docker.io/bpalmer/hello-kubernetes-operator-bundle:v0.0.1`
4. `./build/operator-sdk run bundle docker.io/vramaraj/memcached-operator-bundle:v0.0.1`
5. `./build/operator-sdk run bundle docker.io/vramaraj/nginx-operator-bundle:v0.0.1`
6. `kind delete cluster`

**RESULTS**:
`kubectl get pods`:
```
NAME                                                              READY   STATUS      RESTARTS      AGE
0218697a0b6f89b58fdb43fce61d2f6332f17d4ff22fc18ec40be70becdgmrn   0/1     Completed   0             3m
d5c45fcd9b236bdd5984dc447d51e75bcea50fbcd17f0bb582621d99fbnv2j5   0/1     Completed   0             42s
d9a67cc68f7ece68aed6e49e9bac8847d783b08992b6ae214797011696x9v5s   0/1     Completed   0             100s
docker-io-bpalmer-hello-kubernetes-operator-bundle-v0-0-1         1/1     Running     0             3m7s
docker-io-vramaraj-memcached-operator-bundle-v0-0-1               1/1     Running     0             105s
docker-io-vramaraj-nginx-operator-bundle-v0-0-1                   1/1     Running     0             48s
hello-kubernetes-controller-manager-c5ccf8c5f-6fjmg               2/2     Running     1 (38s ago)   2m44s
memcached-operator-controller-manager-54f5f89956-m2rvs            2/2     Running     0             89s
nginx-operator-controller-manager-769c985b56-mxwzq                2/2     Running     0             26s
```

`kubectl get csv`:
```
NAME                        DISPLAY            VERSION   REPLACES   PHASE
hello-kubernetes.v0.0.1     hello-kubernetes   0.0.1                Succeeded
memcached-operator.v0.0.1   memcached          0.0.1                Succeeded
nginx-operator.v0.0.1       nginx              0.0.1                Succeeded
```

`kubectl get sub`:
```
NAME                            PACKAGE              SOURCE                       CHANNEL
hello-kubernetes-v0-0-1-sub     hello-kubernetes     hello-kubernetes-catalog     alpha
memcached-operator-v0-0-1-sub   memcached-operator   memcached-operator-catalog   alpha
nginx-operator-v0-0-1-sub       nginx-operator       nginx-operator-catalog       alpha
```

## `run bundle` with `--index-image`
1. `kind create cluster`
2. `./build/operator-sdk olm install`
3. `./build/operator-sdk run bundle docker.io/bpalmer/hello-kubernetes-operator-bundle:v0.0.1 --index-image quay.io/rashmigottipati/memcached-catalog-index:0.0.1`
4. `./build/operator-sdk run bundle docker.io/vramaraj/nginx-operator-bundle:v0.0.1 --index-image quay.io/rashmigottipati/memcached-catalog-index:0.0.1`
5. `kind delete cluster`

**RESULTS**:

`kubectl get pods`:
```
NAME                                                              READY   STATUS      RESTARTS      AGE
0218697a0b6f89b58fdb43fce61d2f6332f17d4ff22fc18ec40be70becdbnxk   0/1     Completed   0             2m44s
d5c45fcd9b236bdd5984dc447d51e75bcea50fbcd17f0bb582621d99fbxjxwh   0/1     Completed   0             79s
docker-io-bpalmer-hello-kubernetes-operator-bundle-v0-0-1         1/1     Running     0             3m10s
docker-io-vramaraj-nginx-operator-bundle-v0-0-1                   1/1     Running     0             84s
hello-kubernetes-controller-manager-c5ccf8c5f-smkwx               2/2     Running     1 (20s ago)   2m27s
nginx-operator-controller-manager-769c985b56-vwv66                2/2     Running     0             63s
```

`kubectl get csv`:
```
NAME                      DISPLAY            VERSION   REPLACES   PHASE
hello-kubernetes.v0.0.1   hello-kubernetes   0.0.1                Succeeded
nginx-operator.v0.0.1     nginx              0.0.1                Succeeded
```

`kubectl get sub`:
```
NAME                          PACKAGE            SOURCE                     CHANNEL
hello-kubernetes-v0-0-1-sub   hello-kubernetes   hello-kubernetes-catalog   alpha
nginx-operator-v0-0-1-sub     nginx-operator     nginx-operator-catalog     alpha
```

## `run bundle` with large FBC `--index-image`
1. `kind create cluster`
2. `./build/operator-sdk olm install`
3. `./build/operator-sdk run bundle docker.io/bpalmer/hello-kubernetes-operator-bundle:v0.0.1 --index-image quay.io/operatorhubio/catalog:latest`
4. `./build/operator-sdk run bundle docker.io/vramaraj/memcached-operator-bundle:v0.0.1 --index-image quay.io/operatorhubio/catalog:latest`
5. `./build/operator-sdk run bundle docker.io/vramaraj/nginx-operator-bundle:v0.0.1 --index-image quay.io/operatorhubio/catalog:latest`
6. `kind delete cluster`

**RESULTS**:

`kubectl get pods`:
```
NAME                                                              READY   STATUS      RESTARTS      AGE
0218697a0b6f89b58fdb43fce61d2f6332f17d4ff22fc18ec40be70becf55s8   0/1     Completed   0             3m46s
d5c45fcd9b236bdd5984dc447d51e75bcea50fbcd17f0bb582621d99fbrc858   0/1     Completed   0             74s
d9a67cc68f7ece68aed6e49e9bac8847d783b08992b6ae2147970116968lmfv   0/1     Completed   0             2m37s
docker-io-bpalmer-hello-kubernetes-operator-bundle-v0-0-1         1/1     Running     0             3m50s
docker-io-vramaraj-memcached-operator-bundle-v0-0-1               1/1     Running     0             2m42s
docker-io-vramaraj-nginx-operator-bundle-v0-0-1                   1/1     Running     0             79s
hello-kubernetes-controller-manager-c5ccf8c5f-stng5               2/2     Running     1 (87s ago)   3m33s
memcached-operator-controller-manager-54f5f89956-5hpqf            2/2     Running     0             2m21s
nginx-operator-controller-manager-769c985b56-ss2xr                2/2     Running     0             58s
```

`kubectl get csv`:
```
NAME                        DISPLAY            VERSION   REPLACES   PHASE
hello-kubernetes.v0.0.1     hello-kubernetes   0.0.1                Succeeded
memcached-operator.v0.0.1   memcached          0.0.1                Succeeded
nginx-operator.v0.0.1       nginx              0.0.1                Succeeded
```

`kubectl get sub`:
```
NAME                            PACKAGE              SOURCE                       CHANNEL
hello-kubernetes-v0-0-1-sub     hello-kubernetes     hello-kubernetes-catalog     alpha
memcached-operator-v0-0-1-sub   memcached-operator   memcached-operator-catalog   alpha
nginx-operator-v0-0-1-sub       nginx-operator       nginx-operator-catalog       alpha
```

NOTE: for `run bundle-upgrade` tests you may have to manually approve `InstallPlans`

## `run bundle-upgrade` from `run bundle`
1. `kind create cluster`
2. `./build/operator-sdk olm install`
3. `./build/operator-sdk run bundle docker.io/bpalmer/hello-kubernetes-operator-bundle:v0.0.1`
4. `./build/operator-sdk run bundle-upgrade docker.io/bpalmer/hello-kubernetes-operator-bundle:v0.0.2`
5. `./build/operator-sdk run bundle docker.io/vramaraj/memcached-operator-bundle:v0.0.1`
6. `./build/operator-sdk run bundle-upgrade docker.io/vramaraj/memcached-operator-bundle:v0.0.2`
7. `./build/operator-sdk run bundle docker.io/vramaraj/nginx-operator-bundle:v0.0.1`
8. `./build/operator-sdk run bundle-upgrade docker.io/vramaraj/nginx-operator-bundle:v0.0.2`
9. `kind delete cluster`

**RESULTS**:

`kubectl get pods`:
```
NAME                                                              READY   STATUS      RESTARTS      AGE
0218697a0b6f89b58fdb43fce61d2f6332f17d4ff22fc18ec40be70bec8b9jk   0/1     Completed   0             9m55s
5027f4ecd29d0c58e1edb80f0103b1f56e8e6d81cee44a89a506f074d5tb9pf   0/1     Completed   0             8m58s
9af806535d5d66fe7fe15963d1ee5fc93aef80cf1122150bacf51d4062t8wmh   0/1     Completed   0             77s
d5c45fcd9b236bdd5984dc447d51e75bcea50fbcd17f0bb582621d99fbmkttn   0/1     Completed   0             4m24s
d9a67cc68f7ece68aed6e49e9bac8847d783b08992b6ae214797011696c2nls   0/1     Completed   0             7m14s
docker-io-bpalmer-hello-kubernetes-operator-bundle-v0-0-2         1/1     Running     0             9m
docker-io-vramaraj-memcached-operator-bundle-v0-0-2               1/1     Running     0             6m29s
docker-io-vramaraj-nginx-operator-bundle-v0-0-2                   1/1     Running     0             81s
fa7ca32af5857066b6263b5619868c7d5a5418cb2254ab735bb6577c5c2k2t2   0/1     Completed   0             6m27s
hello-kubernetes-controller-manager-655f585c9b-qlnn8              2/2     Running     3 (86s ago)   8m44s
memcached-operator-controller-manager-66575c5bb6-hh2ll            2/2     Running     0             5m2s
nginx-operator-controller-manager-b548bc6b5-kc4nm                 2/2     Running     0             44s
```

`kubectl get csv`:
```
NAME                        DISPLAY            VERSION   REPLACES                    PHASE
hello-kubernetes.v0.0.2     hello-kubernetes   0.0.2     hello-kubernetes.v0.0.1     Succeeded
memcached-operator.v0.0.2   memcached          0.0.2     memcached-operator.v0.0.1   Succeeded
nginx-operator.v0.0.2       nginx              0.0.2     nginx-operator.v0.0.1       Succeeded
```

`kubectl get sub`:
```
NAME                            PACKAGE              SOURCE                       CHANNEL
hello-kubernetes-v0-0-1-sub     hello-kubernetes     hello-kubernetes-catalog     alpha
memcached-operator-v0-0-1-sub   memcached-operator   memcached-operator-catalog   alpha
nginx-operator-v0-0-1-sub       nginx-operator       nginx-operator-catalog       alpha
```

## `run bundle-upgrade` from OLM traditional case with `replaces` field in the upgrade CSV
1. `kind create cluster`
2. `./build/operator-sdk olm install`
3. Create the traditional `CatalogSource`:
```sh
cat << EOF | kubectl apply -f -
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: hello-kubernetes-operator-catalog
  namespace: operators
spec:
  displayName: Hello Kubernetes Operator
  image: docker.io/bpalmer/hello-kubernetes-sqlite-index:latest
  sourceType: grpc
EOF
```
4. Create the traditional `Subscription`:
```sh
cat << EOF | kubectl apply -f -
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: hello-kubernetes
  namespace: operators
spec:
  channel: "alpha"
  installPlanApproval: Automatic
  name: hello-kubernetes
  source: hello-kubernetes-operator-catalog
  sourceNamespace: operators
  startingCSV: hello-kubernetes.v0.0.1
EOF
```
5. Wait for CSV state to be `Succeeded` by using `watch -n 5 kubectl -n operators get csv`
6. `./build/operator-sdk run bundle-upgrade docker.io/bpalmer/hello-kubernetes-operator-bundle-replace:v0.0.2 -n operators`
6. `kind delete cluster`

**RESULTS**:

`kubectl -n operators get pods`:
```
NAME                                                              READY   STATUS      RESTARTS   AGE
0218697a0b6f89b58fdb43fce61d2f6332f17d4ff22fc18ec40be70bec9kptx   0/1     Completed   0          6m33s
b5baced527f486f89f6136c35b3c9745abba3c7f4a3ccd6eb8eb09f7dbqmrrr   0/1     Completed   0          108s
cker-io-bpalmer-hello-kubernetes-operator-bundle-replace-v0-0-2   1/1     Running     0          117s
hello-kubernetes-controller-manager-8566477c4f-25thh              2/2     Running     0          87s
hello-kubernetes-operator-catalog-4vh8s                           1/1     Running     0          7m49s
```

`kubectl -n operators get csv`:
```
NAME                      DISPLAY            VERSION   REPLACES                  PHASE
hello-kubernetes.v0.0.2   hello-kubernetes   0.0.2     hello-kubernetes.v0.0.1   Succeeded
```

`kubectl -n operators get sub`:
```
NAME               PACKAGE            SOURCE                              CHANNEL
hello-kubernetes   hello-kubernetes   hello-kubernetes-operator-catalog   alpha
```

## `run bundle-upgrade` from OLM traditional case with `--mode semver`
1. `kind create cluster`
2. `./build/operator-sdk olm install`
3. Create the traditional `CatalogSource`:
```sh
cat << EOF | kubectl apply -f -
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: hello-kubernetes-operator-catalog
  namespace: operators
spec:
  displayName: Hello Kubernetes Operator
  image: docker.io/bpalmer/hello-kubernetes-sqlite-index:latest
  sourceType: grpc
EOF
```
4. Create the traditional `Subscription`:
```sh
cat << EOF | kubectl apply -f -
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: hello-kubernetes
  namespace: operators
spec:
  channel: "alpha"
  installPlanApproval: Automatic
  name: hello-kubernetes
  source: hello-kubernetes-operator-catalog
  sourceNamespace: operators
  startingCSV: hello-kubernetes.v0.0.1
EOF
```
5. Wait for CSV state to be `Succeeded` by using `watch -n 5 kubectl -n operators get csv`
6. `./build/operator-sdk run bundle-upgrade docker.io/bpalmer/hello-kubernetes-operator-bundle:v0.0.2 -n operators --mode semver`
7. `kind delete cluster`

**RESULTS**:

`kubectl -n operators get pods`:
```
NAME                                                              READY   STATUS      RESTARTS   AGE
0218697a0b6f89b58fdb43fce61d2f6332f17d4ff22fc18ec40be70bec5j2m7   0/1     Completed   0          4m55s
5027f4ecd29d0c58e1edb80f0103b1f56e8e6d81cee44a89a506f074d56v2bl   0/1     Completed   0          38s
docker-io-bpalmer-hello-kubernetes-operator-bundle-v0-0-2         1/1     Running     0          43s
hello-kubernetes-controller-manager-977d868c9-4r6jg               2/2     Running     0          24s
hello-kubernetes-operator-catalog-8zdm8                           1/1     Running     0          5m14s
```

`kubectl -n operators get csv`:
```
NAME                      DISPLAY            VERSION   REPLACES                  PHASE
hello-kubernetes.v0.0.2   hello-kubernetes   0.0.2     hello-kubernetes.v0.0.1   Succeeded
```

`kubectl -n operators get sub`:
```
NAME               PACKAGE            SOURCE                              CHANNEL
hello-kubernetes   hello-kubernetes   hello-kubernetes-operator-catalog   alpha
```

## sequential `run bundle-upgrade` from `run bundle`
1. `kind create cluster`
2. `./build/operator-sdk olm install`
3. `./build/operator-sdk run bundle docker.io/bpalmer/hello-kubernetes-operator-bundle:v0.0.1`
4. `./build/operator-sdk run bundle-upgrade docker.io/bpalmer/hello-kubernetes-operator-bundle:v0.0.2`
5. `./build/operator-sdk run bundle-upgrade docker.io/bpalmer/hello-kubernetes-operator-bundle:v0.0.3`
6. `./build/operator-sdk run bundle docker.io/vramaraj/memcached-operator-bundle:v0.0.1`
7. `./build/operator-sdk run bundle-upgrade docker.io/vramaraj/memcached-operator-bundle:v0.0.2`
8. `./build/operator-sdk run bundle-upgrade docker.io/vramaraj/memcached-operator-bundle:v0.0.3`
9. `./build/operator-sdk run bundle docker.io/vramaraj/nginx-operator-bundle:v0.0.1`
10. `./build/operator-sdk run bundle-upgrade docker.io/vramaraj/nginx-operator-bundle:v0.0.2`
11. `./build/operator-sdk run bundle-upgrade docker.io/vramaraj/nginx-operator-bundle:v0.0.3`
12. `kind delete cluster`

**RESULTS**:

`kubectl get pods`:
```
NAME                                                              READY   STATUS      RESTARTS       AGE
0218697a0b6f89b58fdb43fce61d2f6332f17d4ff22fc18ec40be70becg785k   0/1     Completed   0              14m
461cd7fc535a0c48bff67543834ad617c9a3dd7a66093c4d00aac35a2bqmsl4   0/1     Completed   0              2m9s
5027f4ecd29d0c58e1edb80f0103b1f56e8e6d81cee44a89a506f074d5km8tt   0/1     Completed   0              13m
9af806535d5d66fe7fe15963d1ee5fc93aef80cf1122150bacf51d4062r9pjj   0/1     Completed   0              3m56s
a2b0380e5e2b579202936f3609c7557681273187c9ac0dcc69871cc695d4rkn   0/1     Completed   0              12m
d5c45fcd9b236bdd5984dc447d51e75bcea50fbcd17f0bb582621d99fbcw69p   0/1     Completed   0              4m47s
d9a67cc68f7ece68aed6e49e9bac8847d783b08992b6ae214797011696wgnd7   0/1     Completed   0              11m
docker-io-bpalmer-hello-kubernetes-operator-bundle-v0-0-3         1/1     Running     0              12m
docker-io-vramaraj-memcached-operator-bundle-v0-0-3               1/1     Running     0              5m46s
docker-io-vramaraj-nginx-operator-bundle-v0-0-3                   1/1     Running     0              2m11s
fa11d19190f3997c5393cb0ec623a0cae7a4e93d151f0611a958097e3a9wfcj   0/1     Completed   0              5m43s
fa7ca32af5857066b6263b5619868c7d5a5418cb2254ab735bb6577c5cf7czh   0/1     Completed   0              10m
hello-kubernetes-controller-manager-7cbb6b667b-tjv5f              2/2     Running     4 (113s ago)   11m
memcached-operator-controller-manager-69f48468d4-d9ktl            2/2     Running     0              5m28s
nginx-operator-controller-manager-8548564b7c-j544r                2/2     Running     0              102s
```

The 4 restarts on the `hello-kubernetes-controller-manager-7cbb6b667b-tjv5f` seem to be due to an error in the hello-kuberenetes operator itself and has nothing to do with
`run bundle` or `run bundle-upgrade`

`kubectl get csv`:
```
NAME                        DISPLAY            VERSION   REPLACES                    PHASE
hello-kubernetes.v0.0.3     hello-kubernetes   0.0.3     hello-kubernetes.v0.0.2     Installing
memcached-operator.v0.0.3   memcached          0.0.3     memcached-operator.v0.0.2   Succeeded
nginx-operator.v0.0.3       nginx              0.0.3     nginx-operator.v0.0.2       Succeeded
```

`hello-kuberenetes.v0.0.3` is stuck in the `Installing` phase due to an error in the `v0.0.3` version of the hello-kubernetes operator itself and has nothing to do with 
`run bundle` or `run bundle-upgrade`

`kubectl get sub`:
```
NAME                            PACKAGE              SOURCE                       CHANNEL
hello-kubernetes-v0-0-1-sub     hello-kubernetes     hello-kubernetes-catalog     alpha
memcached-operator-v0-0-1-sub   memcached-operator   memcached-operator-catalog   alpha
nginx-operator-v0-0-1-sub       nginx-operator       nginx-operator-catalog       alpha
```


## sequential `run bundle-upgrade` from OLM traditional case with `--mode semver`
1. `kind create cluster`
2. `./build/operator-sdk olm install`
3. Create the traditional `CatalogSource`:
```sh
cat << EOF | kubectl apply -f -
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: hello-kubernetes-operator-catalog
  namespace: operators
spec:
  displayName: Hello Kubernetes Operator
  image: docker.io/bpalmer/hello-kubernetes-sqlite-index:latest
  sourceType: grpc
EOF
```
4. Create the traditional `Subscription`:
```sh
cat << EOF | kubectl apply -f -
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: hello-kubernetes
  namespace: operators
spec:
  channel: "alpha"
  installPlanApproval: Automatic
  name: hello-kubernetes
  source: hello-kubernetes-operator-catalog
  sourceNamespace: operators
  startingCSV: hello-kubernetes.v0.0.1
EOF
```
5. Wait for CSV state to be `Succeeded` by using `watch -n 5 kubectl -n operators get csv`
6. `./build/operator-sdk run bundle-upgrade docker.io/bpalmer/hello-kubernetes-operator-bundle:v0.0.2 -n operators --mode semver`
7. `./build/operator-sdk run bundle-upgrade docker.io/bpalmer/hello-kubernetes-operator-bundle:v0.0.3 -n operators --mode semver`
8. `kind delete cluster`


**RESULTS**:

`kubectl -n operators get pods`:
```
NAME                                                              READY   STATUS      RESTARTS   AGE
0218697a0b6f89b58fdb43fce61d2f6332f17d4ff22fc18ec40be70bec7p2kn   0/1     Completed   0          5m7s
5027f4ecd29d0c58e1edb80f0103b1f56e8e6d81cee44a89a506f074d5jznzs   0/1     Completed   0          106s
a2b0380e5e2b579202936f3609c7557681273187c9ac0dcc69871cc695kb2fq   0/1     Completed   0          50s
docker-io-bpalmer-hello-kubernetes-operator-bundle-v0-0-3         1/1     Running     0          57s
hello-kubernetes-controller-manager-54c96fcb97-t24r7              2/2     Running     0          41s
hello-kubernetes-operator-catalog-j8bnr                           1/1     Running     0          5m54s
```

`kubectl -n operators get csv`:
```
NAME                      DISPLAY            VERSION   REPLACES                  PHASE
hello-kubernetes.v0.0.3   hello-kubernetes   0.0.3     hello-kubernetes.v0.0.2   Succeeded
```

`kubectl -n operators get sub`:
```
NAME               PACKAGE            SOURCE                              CHANNEL
hello-kubernetes   hello-kubernetes   hello-kubernetes-operator-catalog   alpha
```


</details>

**Review by rashmigottipati — APPROVED** [review]
/lgtm

Tested various scenarios extensively and these changes don't break any existing scenarios and also fixes a traditional upgrade use-case bug.

**Pull request merged**
