### PR TITLE
docs: fix typo in golang/webhooks.md

### PR DESCRIPTION
**Pull request by FrankYang0529**
fix typo for error link

**Description of the change:**

Fix typo for error link in docs/building-operators/golang/webhooks.md

**Motivation for the change:**

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Comment by camilamacedo86** [comment]
Hi @FrankYang0529, 

Thank you for your contribution. However, we ought to do this change against the master. It could be a cherry-pick against 1.0 branch. Could you please check it?

**Review by camilamacedo86 — CHANGES_REQUESTED** [review]
we need to fix in the master and do a cherry-pick to 1.0

**Comment by estroz** [comment]
@camilamacedo86 this document was removed in master, so this PR is fine.

**Review by camilamacedo86 — APPROVED** [review]
/lgtm 

based on the @eric comment

**Pull request merged**
