### PR TITLE
Support test selection in scorecard-kuttl integration

### LINKED ISSUE #5743: test selection in kuttl scorecard image is ignored and all the test are actually run
#### What did you do?

I am using the kuttl scorecard image (i.e., `quay.io/operator-framework/scorecard-test-kuttl:v2.0.0`) and in my config.yaml I have two test suites. When I run the scorecard command using the test selection, the scorecard actually runs all the tests regardless the selection I specify.
```operator-sdk scorecard ./bundle --selector='suite=sanity-suite' --namespace=<ns_name> --skip-cleanup --wait-time <timeout> --service-account <SA_name>```

This is the config.yaml:
```
apiVersion: scorecard.operatorframework.io/v1alpha3
kind: Configuration
metadata:
  name: config
stages:
- parallel: true
  tests:
  - entrypoint:
    - entrypoint
    - 00-ods-ci-settings
    - 01-smoke
    image: quay.io/operator-framework/scorecard-test-kuttl:v2.0.0
    labels:
      cluster-product: ocp
      cluster-size: small
      phase: msp-main
      test: smoke
      suite: smoke-suite
    storage:
      spec:
        mountPath: {}
  - entrypoint:
    - entrypoint
    - 00-ods-ci-settings
    - 02-sanity
    image: quay.io/operator-framework/scorecard-test-kuttl:v2.0.0
    labels:
      cluster-product: ocp
      cluster-size: small
      phase: msp-main
      test: sanity
      suite: sanity-suite
    storage:
      spec:
        mountPath: {}
```
#### What did you expect to see?

I would expect to see only  `00-ods-ci-settings` and `02-sanity` running

#### What did you see instead? Under which circumstances?

I see instead both the test suites running:
image

#### Environment

**Operator type:**

**Kubernetes cluster type:**

Openshift 4.10.12

`$ operator-sdk version`

operator-sdk version: "v1.19.1", commit: "079d8852ce5b42aa5306a1e33f7ca725ec48d0e3"

`$ go version` (if language is Go)

go version: "go1.17.8"

`$ kubectl version`

kubectl version: "1.21"

#### Possible Solution

One possiblesolution would invole replacing lines from 6 to 9 in the [entrypoint](https://github.com/operator-framework/operator-sdk/blob/d162b0bae248c07aa8257e641b11a235ac07dff2/images/scorecard-test-kuttl/entrypoint#L6 ) script with:

```
if [ $# -eq 0 ]
  then
    kubectl-kuttl test ${KUTTL_PATH} \
      --config=${KUTTL_CONFIG} \
      --namespace=${SCORECARD_NAMESPACE} \
      --report=JSON --artifacts-dir=/tmp > /tmp/kuttl.stdout 2> /tmp/kuttl.stderr
  else
    for i in $*; do 
      kubectl-kuttl test ${KUTTL_PATH} \
      --test $i  \
      --config=${KUTTL_CONFIG} \
      --namespace=${SCORECARD_NAMESPACE} \
      --report=JSON --artifacts-dir=/tmp > /tmp/kuttl.stdout 2> /tmp/kuttl.stderr
    done
fi
```
One problem to address would be to make the scorecard able to handle more than one kuttl result file

### PR DESCRIPTION
**Pull request by jmrodri**
**Description of the change:**
Update the `entrypoint` to use the test name passed in from the test config. 

**Motivation for the change:**
Fixes #5743 

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [x] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Comment by jmrodri** [comment]
We're going to need a new release of the `scorecard-test-kuttl` image for folks to be able to use the changes in this PR.

**Comment by jmrodri** [comment]
```
[jesusr@transam memcached-operator{kuttl-debug-commits}]$ operator-sdk scorecard ./bundle  --service-account kuttl-user --wait-time 60s --selector='suite=smoke-suite' --skip-cleanup
--------------------------------------------------------------------------------
Image:      quay.io/jesusr/scorecard-test-kuttl:dev
Entrypoint: [entrypoint common smoke]
Labels:
        "cluster-size":"small"
        "phase":"msp-main"
        "suite":"smoke-suite"
        "test":"smoke"
        "cluster-product":"ocp"
Results:
        Name: smoke
        State: pass
```

**Review by everettraven — APPROVED** [review]
These changes make sense to me. Not to familiar with the scorecard stuff though so I will leave any LGTMs up to others that are more familiar with it.

**Review by laxmikantbpandhare — APPROVED** [review]
/lgtm

**Pull request merged**
