### PR TITLE
Revert "Pipenv (#4494)"

### PR DESCRIPTION
**Pull request by estroz**
This reverts commit 4c0a60dcb4ce41ea58cac2336f36659290c9266b.

#4494 was merged prematurely. Builds for s390x, ppc64le, arm64 are [broken](https://travis-ci.com/github/operator-framework/operator-sdk/builds/217019403) due to gcc (and other deps) not being installed, but during some testing I also discovered that the Pipfile.lock's hashes don't resolve on s390x builds (at least) and I can't debug the issue. #4494 should be reverted until builds on all platforms can be tested using Github Actions for each PR, since we're moving away from Travis completely soon. This is something I'm working on right now using `docker buildx`.

### CODE REVIEW

**Review by varshaprasad96 — APPROVED** [review]

**Review by jmrodri — APPROVED** [review]
/lgtm

**Comment by reinvantveer** [comment]
Yikes!

**Comment by joelanford** [comment]
@estroz This github actions workflow may be of interest to you:

https://github.com/joelanford/helm-operator/blob/main/.github/workflows/deploy.yml

It runs the goreleaser and docker builds on all PRs, but only publishes on tags.

**Comment by reinvantveer** [comment]
I can see pipenv retrying a couple of times on some hashes, but so far I can see builds failing only on missing gcc. So perhaps if we install and de-install gcc as a build dependency for the python dependency phase, things will be OK?

**Comment by estroz** [comment]
>So perhaps if we install and de-install gcc as a build dependency for the python dependency phase, things will be OK?

It doesn't appear to be the only issue. After adding gcc (along with `redhat-lsb-core`) and trying to build with `docker buildx build -f ./images/ansible-operator/Dockerfile --platform linux/s390x ./images/ansible-operator` you see other errors on `pipenv install --deploy`.

**Comment by reinvantveer** [comment]
OK I' ll give it a try

**Comment by reinvantveer** [comment]
https://github.com/operator-framework/operator-sdk/pull/4543 is where I intend to get things going again, if possible

**Pull request merged**
