### PR TITLE
release: push scorecard-test-kuttl images on `scorecard-kuttl/v*` tags

### PR DESCRIPTION
**Pull request by estroz**
**Description of the change:**
- .github/workflows: release scorecard-test-kuttl images on `scorecard-kuttl/v*` tags, and only run image deploy jobs for code changes and appropriate tag patterns

**Motivation for the change:** breaking changes to kuttl happen, and the accepted solution is to version the scorecard-test-kuttl version independently, starting at v2.0.0 (see #4557 for details). Releases will be tagged with `scorecard-kuttl/vX.Y.Z`. operator-sdk releases will still have tags like `vA.B.C`, but will not cause scorecard-test-kuttl images to be published.

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Comment by estroz** [comment]
Testing this on my fork. Will post a test run when complete.

**Review by camilamacedo86 — DISMISSED** [review]
I shows fine. However, why 2.0.?

**Comment by estroz** [comment]
Successful builds:
- `master`: https://github.com/estroz/operator-sdk/actions/runs/641130830
- tag `scorecard-kuttl/v2.0.0`: https://github.com/estroz/operator-sdk/actions/runs/641131181

**Comment by estroz** [comment]
@camilamacedo86 because the next release of this image will contain a breaking change, thus it cannot be in v1.

**Review by camilamacedo86 — APPROVED** [review]
I have no objection to the idea.
It shows fine for me 👍

**Pull request merged**
