### PR TITLE
(actions): update link-checker for https://docs.github.com

### PR DESCRIPTION
**Pull request by everettraven**
**Description of the change:**
- Update the GitHub docs link for how to fork a repo within the OSDK Contributing documentation
- Update the link check config file to set the `User-Agent` HTTP header to `Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0` only when making requests to URLs that start with `https://docs.github.com`
- Update the `hack/check-links.sh` to ignore the URL `https://docs.github.com/en/get-started/quickstart/fork-a-repo`

**Motivation for the change:**
The static link checker has been receiving a `403 Forbidden` status code when attempting to reach the GitHub docs. Seemingly this is related to the `User-Agent` HTTP header and GitHub's server blocking it if it isn't a browser (failing when using `curl` without changing the `User-Agent` header but succeeding when the `User-Agent` header is set to `Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0`)

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Review by ryantking — COMMENTED** [review]
What does the `User-Agent` header accomplish if we are now ignoring the problematic link?

**Comment by everettraven** [comment]
> What does the `User-Agent` header accomplish if we are now ignoring the problematic link?

It is for the second link checker that is a GitHub action. See https://github.com/operator-framework/operator-sdk/blob/70b1bf7c4c5d5882d7a9a1419f9bde2b25eacd98/.github/workflows/test-sanity.yml#L48

**Comment by jberkhahn** [comment]
/lgtm

nice to have a fix for this. I would have assumed we were getting rate limited by something.

**Review by jmrodri — APPROVED** [review]
/lgtm

**Pull request merged**
