### PR TITLE
Close #5594: Ansible reconcile-period CLI flag

### LINKED ISSUE #5594: Reconcile period CLI flag for Ansible operators not working
#### What did you do?

Used the `--reconcile-period` flag while running an Ansible-based operator. 

#### What did you expect to see?

Reconciliation in the specified intervals of time.

#### What did you see instead? Under which circumstances?

Reconciliations do not get requeued.

**Operator type:**

/language ansible

#### Possible Solution

[Here](https://github.com/operator-framework/operator-sdk/blob/master/internal/cmd/ansible-operator/run/cmd.go#L226), it looks like _only_ the watches reconcile period is used in the controller. The reconcile period from the CLI flag (`f.reconcilePeriod`) does not get used at all.

Fix: Check for both `f.reconcilePeriod` and `w.reconcilePeriod`.

#### Additional context

I just wanted to make sure that this wasn't intentional. The fix for this would follow the same precedence order for the reconcile period speciication that was [discussed](https://github.com/operator-framework/operator-sdk/pull/5585#discussion_r823223775) for Helm: CLI flag < `watches.yaml` < CR annotations.

### PR DESCRIPTION
**Pull request by VenkatRamaraju**
Signed-off-by: Venkat Ramaraju <vramaraj@redhat.com>

**Description of the change:**
Added the usage of the reconcile-period CLI flag in Ansible

**Motivation for the change:**
Close #5594

### CODE REVIEW

**Review by varshaprasad96 — APPROVED** [review]
/lgtm

**Review by rashmigottipati — APPROVED** [review]
/lgtm

**Comment by VenkatRamaraju** [comment]
remove /hold

**Review by varshaprasad96 — APPROVED** [review]

**Pull request merged**
