### PR TITLE
Fix markup

### PR DESCRIPTION
**Pull request by porridge**
**Description of the change:**

Separate a sentence which incorrectly was rendered as part of bullet list.

**Motivation for the change:**

Screenshot 2021-04-13 at 13 42 00

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] ~Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))~
- [ ] ~Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)~

### CODE REVIEW

**Review by camilamacedo86 — APPROVED** [review]
/lgtm

**Comment by jberkhahn** [comment]
Looks like you need to sign your commit

**Comment by jmrodri** [comment]
@porridge this PR is failing a DCO check which requires the commit to be signed. You can do that locally with `git rebase HEAD~1 --signoff` then force push the branch again.

**Review by jmrodri — APPROVED** [review]
/lgtm

**Pull request merged**
