### PR TITLE
Update quickstart.md

### PR DESCRIPTION
**Pull request by akgerber**
**Description of the change:**
replace --plugins=go/v4-alpha with --plugins=go/v4 to reflect "Move go/v4 plugin from alpha to stable " in v1.33 https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.33.0/

**Motivation for the change:**
docs are out of date

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Review by OchiengEd — APPROVED** [review]
/lgtm

**Comment by jberkhahn** [comment]
still need you to sign your commit so this can be merged

**Comment by acornett21** [comment]
Closing as duplicate.

**Pull request closed without merging**
