### PR TITLE
Create SA for the operator

### PR DESCRIPTION
**Pull request by camilocot**
ref: #189

### CODE REVIEW

**Comment by CSdread** [comment]
@camilocot can you get the conflict fixed up? @spahl @hasbro17 any chance we can push this one up, we have code that does this but could be removed if we pull this in ;)

**Comment by camilocot** [comment]
@CSdread conflicts fixed.

**Comment by CSdread** [comment]
do we know what the side effects are for folks not yet using SA and RBAC would the functionality be the same?

**Comment by CSdread** [comment]
@camilocot so a few things, first if you would read the contributor document in the repo root, the format for naming commits and PRs, can we get you to fix that part?

**Comment by hasbro17** [comment]
@CSdread Sorry I've been busy with other reviews and the controller-runtime refactoring work. Will try to prioritize this in this week.
/cc @AlexNPavel we need to consider how this affects the test-framework.

**Comment by AlexNPavel** [comment]
The comment on line 58 of commands/operator-sdk/cmd/test.go should be updated: https://github.com/operator-framework/operator-sdk/blob/c84b1a90fcd918ddcdbe2c56ae78b6a15285a86f/commands/operator-sdk/cmd/test.go#L58

**Comment by AlexNPavel** [comment]
The user guide (`doc/user-guide.md`) needs to be updated as well

**Comment by AlexNPavel** [comment]
lgtm

**Comment by CSdread** [comment]
lgtm as well

**Comment by CSdread** [comment]
@hasbro17 this is ready for merge we believe

**Comment by hasbro17** [comment]
LGTM

**Pull request merged**
