### PR TITLE
registry_pod: Avoid grace period delay

### PR DESCRIPTION
**Pull request by avisiedo**
**Description of the change:**

Substitute shell by the last command that serve the registry pod.

**Motivation for the change:**

The shell script does not propagate the SIGTERM signal that is sent to
the pod when it is terminated; to avoid this, we run the last command to
substitute the shell process, so that the pod stop immediately instead of
waiting the 30 default seconds of the grace period when an user uninstall
the operator by using 'operator-sdk cleanup ...' command.

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

**issue**: https://github.com/operator-framework/operator-sdk/issues/5866

### CODE REVIEW

**Comment by jmrodri** [comment]
@avisiedo is there a github issue that explains the problem you were having?

**Comment by avisiedo** [comment]
@jmrodri No, there is not. What am I missing to propose a change into the repository?

- I don't see the change as a user-facing change, as the operations and interactions are the same, just improve the time the registry_pod to terminate. Should documentation about this to be provided for the changeling anyway?
- The same for '[website/content/en/docs](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)', as I don't see changes into the user interaction with this change.

Please correct me on the above if I were wrong in something, and if an issue is required, let me know and I will create it, and I will update this PR to reference the issue.

Thanks

**Comment by avisiedo** [comment]
@jmrodri  In the pipeline I get [here](https://github.com/operator-framework/operator-sdk/runs/6719319742?check_suite_focus=true#step:4:133) and issue related with an external link.

I have checked the link manually and it worked, probably network transitory situations; I can not relaunch the test to check it. :sweat_smile:

If further changes are necessary, or an issue ticket is necessary for the change, please let me know and I will do it

Cheers! :slightly_smiling_face:

**Comment by avisiedo** [comment]
I have added an issue at: https://github.com/operator-framework/operator-sdk/issues/5866

**Pull request closed without merging**
