### PR TITLE
typo

### PR DESCRIPTION
**Pull request by kevburnsjr**
**Description of the change:**

    Minuscule doc update

**Motivation for the change:**

    Grammar police

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Comment by jmrodri** [comment]
@kevburnsjr would you please sign your commit? `git rebase HEAD~1 --signoff` should fix it. thanks for the PR submission

**Comment by kevburnsjr** [comment]
@jmrodri Done!

**Review by asmacdo — APPROVED** [review]
/lgtm

**Review by everettraven — APPROVED** [review]
/lgtm

**Pull request merged**
