### PR TITLE
Fix Ansible CI

### PR DESCRIPTION
**Pull request by everettraven**
**Description of the change:**
- Update molecule version in CI and the default ansible scaffolds to support a newer molecule version.

**Motivation for the change:**
- Fix the ansible CI failures

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Review by rashmigottipati — APPROVED** [review]
/lgtm

**Comment by scotRinga-MayaDog** [comment]
Replied

**Pull request merged**
