### PR TITLE
Disable the AllNamespaces InstallMode

### LINKED ISSUE #2173: Should disable the AllNamespaces installMode
## Bug Report

**What did you do?**
I create the CSV files by using `operator-sdk olm-catalog gen-csv` command.
```console
mac:learn-operator jianzhang$ operator-sdk olm-catalog gen-csv --operator-name learn-operator --csv-version 0.0.1 --csv-channel alpha 
INFO[0000] Generating CSV manifest version 0.0.1        
INFO[0000] Fill in the following required fields in file deploy/olm-catalog/learn-operator/0.0.1/learn-operator.v0.0.1.clusterserviceversion.yaml:
	spec.keywords
	spec.maintainers
	spec.provider 
INFO[0000] Created deploy/olm-catalog/learn-operator/0.0.1/learn-operator.v0.0.1.clusterserviceversion.yaml 
INFO[0000] Created deploy/olm-catalog/learn-operator/learn-operator.package.yaml 
```
But, failed to install the CSV.
```console
mac:learn-operator jianzhang$ oc get csv
NAME                                        DISPLAY                  VERSION              REPLACES                                    PHASE
learn-operator.v0.0.1                       Learn Operator           0.0.1                learn-operator.v0.0.0                       Pending

mac:learn-operator jianzhang$ oc describe csv learn-operator.v0.0.1 
...
  Install Modes:
    Supported:  true
    Type:       OwnNamespace
    Supported:  true
    Type:       SingleNamespace
    Supported:  false
    Type:       MultiNamespace
    Supported:  true
    Type:       AllNamespaces
...
  Normal   RequirementsUnknown  31m                 operator-lifecycle-manager  InstallModes now support target namespaces
```

**What did you expect to see?**
Should set the `AllNamespaces` to `false` as default since I didn't use the cluster CRD. 

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**Environment**
* operator-sdk version:
```console
mac:operator-sdk jianzhang$ operator-sdk version
operator-sdk version: "v0.12.0", commit: "2445fcda834ca4b7cf0d6c38fba6317fb219b469", go version: "go1.13.4 darwin/amd64"
```

* go version:
```console
mac:operator-sdk jianzhang$ go version
go version go1.13.1 darwin/amd64
```

* Kubernetes version information:

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?

**Possible Solution**

**Additional context**

### PR DESCRIPTION
**Pull request by jianzhangbjz**
**Description of the change:**

Closes #2173 

**Motivation for the change:**

The generated CSV files can be installed successfully.

### CODE REVIEW

**Comment by hasbro17** [comment]
LGTM but need a second look from @estroz on whether we should disable the `AllNamespaces` by default since our default scaffolding is for namespace scoped operators.

**Comment by camilamacedo86** [comment]
Hi @jianzhangbjz, 

 @estroz made a question in https://github.com/operator-framework/operator-sdk/issues/2173#issuecomment-552686138 could you please check out?

**Comment by camilamacedo86** [comment]
HI @jianzhangbjz, 

It has open for a while whiteout interactions. See that @estroz made a question in #2173 (comment) could you please check out? Let's first understand why it should be done and be in the agreement.

So, I  hope that you do not mind about we close this one until we achieve it. However, please feel free to re-open if you think that it is required and note that it also can always be done when and if we came to the conclusion that it is the best approach in the #2173.

**Comment by jianzhangbjz** [comment]
Hi, @camilamacedo86 

Yes, sorry for the late to reply. I answers @estroz question. 
I think we should we should disable the `AllNamespaces` by default since our default scaffolding is for `namespace` scoped operators. Reopen it.

**Comment by estroz** [comment]
This PR needs documentation updates in the [cluster scoping guide](https://github.com/operator-framework/operator-sdk/blob/7cc38cc/doc/operator-scope.md), since a cluster-scoped operator will want to enable `AllNamespaces`.

**Comment by estroz** [comment]
@jianzhangbjz if you aren't able to continue working on this PR, I can take it over.

**Comment by camilamacedo86** [comment]
> This PR needs documentation updates in the cluster scoping guide, since a cluster-scoped operator will want to enable AllNamespaces.

It is true. Currently, we have none info over the CSV config and operator scope doc. 
Would be great we have it. However, I think that we may do follow-up PR as well. wddyt @estroz? 

>  This is also a breaking change and needs a changelog update.

@jianzhangbjz  see here: [CHANGELOG](https://github.com/operator-framework/operator-sdk/blob/master/CHANGELOG.md)

It would be in the `Changed` section.  Something such as:

> **Breaking change:** All CSVs will be generated with the support of `AllNamespaces` as `false` since the default init project is namespaced scope. If your operator is cluster-scoped and has support for all namespace in its integration with OLM then, ensure that you checked this metadata. ([#2174](https://github.com/operator-framework/operator-sdk/pull/2174))

**Comment by joelanford** [comment]
@estroz @camilamacedo86 @jianzhangbjz Since we are imminently switching our scaffolding to use Kubebuilder's Go operator scaffolding (which defaults to cluster-scoped operators), I think we should close this since AllNamespaces will be supported by default going forward. Thoughts?

**Comment by camilamacedo86** [comment]
Agree 100% @joelanford.

**Pull request closed without merging**
