### PR TITLE
Replace non-existing manifests and prevent them from changing in the future

### PR DESCRIPTION
**Pull request by tkrishtop**
**Description of the change:**

This PR is to be merged after the PR @acornett21 : https://github.com/operator-framework/operator-sdk/pull/6422 

- Fix: Replace non-existing manifests for scorecard-storage and scorecard-untar that were accidentally overridden during the release 1.28.1.
- Makefile: Prevent scorecard-storage and scorecard-untar from being rebuilt in the future.

**Motivation for the change:**

To support the integration of DCI, Preflight, and Operator-SDK in disconnected environments, we have to use the digests and not tags for scorecard-storage and scorecard-untar. We also have to protect these digests from being overwritten during the release process. All the details are here: https://github.com/operator-framework/operator-sdk/issues/6417.

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Review by everettraven — APPROVED** [review]
Thanks @tkrishtop !  The changes look good to me.

/lgtm

Placing a hold until https://github.com/operator-framework/operator-sdk/pull/6422 is merged

/hold

**Comment by everettraven** [comment]
Closing and reopening to try and pick up the changes that were merged in #6422

**Comment by tkrishtop** [comment]
hi @everettraven I merged the master branch into fix_digests to pick the change of @acornett21

**Review by everettraven — APPROVED** [review]
/lgtm

**Comment by everettraven** [comment]
Merging as the sanity docs check failures are expected and should be resolved by #6414 . Created a new issue for the ansible molecule e2e: https://github.com/operator-framework/operator-sdk/issues/6433

**Pull request merged**
