### PR TITLE
fix: generate required bin in the tests

### PR DESCRIPTION
**Pull request by camilamacedo86**
**Description**
- Add command to build sdk to allow the go-tests using a binary generated with the code changes made

PS.: By testing it locally I notice that the changes made for the sdk tool were was not reflecting in the tests when they were executed by the command line since it was not getting a binary generated with the code changes.

### CODE REVIEW

**Comment by estroz** [comment]
I'm ok with this, and I would rather see the build step encoded in test files than in `.travis.yml` so tests can be more easily run locally. Therefore this change should be done to all test files and not just this one, while also removing `make install` from the travis config.

**Comment by joelanford** [comment]
The one benefit of the current way is that we _could_ run `make install` once, and then have all tests use it. But in practice, we run each test in a separate VM, so each test has to run its own `make install`. So I'm good with this too and agree with @estroz that we should make all tests that depend on the SDK binaries to do this.

Also, should we update the `build_sdk` function to build all of the binaries?

I am interested in what happens if I run the e2e test multiple times without changing the sdk binaries. After the first run, I assume this step is fast because it takes advantage of the Go build cache?

**Comment by camilamacedo86** [comment]
Hi @joelanford @estroz, 

Applied all suggestions. Regards `Also, should we update the build_sdk function to build all of the binaries? `
I think we can build them just when/where they are required as well which was done here.

**Comment by camilamacedo86** [comment]
Hi @joelanford and @estroz, 

I started to check it and I agree with your suggestion but just after the migrate the tests. Note that they will be able to be called with but not the legacy ones. So, IMO we can keep it in mind start to do this for the new ones and then, after all, we can clean up and remove it from the Travis. Could we agree to move in this way? 


Regards. `Also, should we update the build_sdk function to build all of the binaries?` I think we can funcs for them and just call where/when is required too.

**Comment by camilamacedo86** [comment]
Hi @joelanford and @estroz, 

Coul we agree on todo the suggested cleanup in the future when all be migrated?

Regards. `Also, should we update the build_sdk function to build all of the binaries?` I think we can funcs for them and just call where/when is required too.

**Comment by camilamacedo86** [comment]
I will come up with the cleanup again when we port all tests. it will be more assertive. 
Closing it for now.

**Pull request closed without merging**
