### PR TITLE
OLM client: Wait till the deployment appear

### PR DESCRIPTION
**Pull request by avalluri**
**Description of the change:**

Sometimes OLM installation fails with below error:
```
INFO[0028] Waiting for deployment/packageserver rollout to complete
FATA[0028] Failed to install OLM version "latest": deployment/packageserver failed to rollout: deployments.apps "packageserver" not found# Please enter the commit message for your changes. Lines starting
```

The reason might be that the deployment object we are waiting for is not
yet registered with the API server. So, continue the polling and do not
treat this as an error.

**Motivation for the change:**
Observed OLM installation failed occasionally.

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:

- [ ] Add a new changelog fragment in changelog/fragments (see changelog/fragments/00-template.yaml)
- [ ]  Add or update relevant sections of the docs website in website/content/en/docs

### CODE REVIEW

**Comment by jberkhahn** [comment]
Is a single wait period of 1 second enough time for this? I figure the reason it's mostly likely to take for the deployment to not be up immediately is the cluster has to pull the image on a fresh install - that could take a while depending on the connection.

**Comment by avalluri** [comment]
> Is a single wait period of 1 second enough time for this? I figure the reason it's mostly likely to take for the deployment to not be up immediately is the cluster has to pull the image on a fresh install - that could take a while depending on the connection.

Yes, I agree 1-second timeout might be too small in some environments. But I didn't observe any failure on a clean install.

**Comment by avalluri** [comment]
Can someone help understand the CI failure with this change: 

```
- /target/docs/contribution-guidelines/release/index.html
  *  External link https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work failed: got a time out (response code 0)
htmlproofer 3.15.0 | Error:  HTML-Proofer found 1 failure!
Makefile:267: recipe for target 'test-links' failed
make: *** [test-links] Error 1
The command "make test-links" exited with 2.
cache.2
store build cache
0.00s1.88snothing changed
```

**Comment by avalluri** [comment]
> > Is a single wait period of 1 second enough time for this? I figure the reason it's mostly likely to take for the deployment to not be up immediately is the cluster has to pull the image on a fresh install - that could take a while depending on the connection.
> 
> Yes, I agree 1-second timeout might be too small in some environments. But I didn't observe any failure on a clean install.

Ooops, I misunderstood the comment. The 1-second was not timeout, wait period. Please ignore my earlier comment.

But this change is more about not exiting with failure if the deployment is not yet appeared.

**Comment by camilamacedo86** [comment]
Hi @avalluri, 

Thank you for your contribution 🥇 . The changes made by you are not passing in the CI because it broke the command/feature. See:         

`time="2020-09-06T19:19:31Z" level=fatal msg="Failed to run packagemanifests: create catalog: error creating registry resources: error registering package: error waiting for Deployment \"default/e2e-deqk-registry-server\" to roll out: timed out waiting for the condition\n"
`
 
WDYT about raise an issue with all steps for we are able to reproduce it or with more detailed info? Shows that the scenario issue is not clear as well by following the comments. Also, I never saw the error `FATA[0028] Failed to install OLM version "latest": deployment/packageserver failed to rollout: deployments.apps "packageserver" not found# Please enter the commit message for your changes. Lines starting
` as a flake of the CI whcih lead to me think that it is a specific scenario and might have another way to be solved. 

Since the fix is not working and it is open for a while without interation I hope that is fine we close this one. However, few free to re-open if you would like to still work on it and/or raise new contributions. Also, feel free to ping us in the slack if you need any help to contribute to the project.

**Comment by avalluri** [comment]
> Also, I never saw the error `FATA[0028] Failed to install OLM version "latest": deployment/packageserver failed to rollout: deployments.apps "packageserver" not found# Please enter the commit message for your changes. Lines starting ` 

It was my bad, the comments part shouldn't be added to the commit message :(.  The original failure message was: 
 `FATA[0028] Failed to install OLM version "latest": deployment/packageserver failed to rollout: deployments.apps "packageserver" not found`. 

The full logs:
```
operator-sdk olm install --verbose --timeout=5m
DEBU[0000] Debug logging is set                         
INFO[0000] Fetching CRDs for version "latest"           
INFO[0004] Fetching resources for version "latest"      
I1031 01:00:33.011939   34188 request.go:621] Throttling request took 1.047948147s, request: GET:https://172.17.0.2:6443/apis/storage.k8s.io/v1beta1?timeout=32s
INFO[0011] Creating CRDs and resources                  
INFO[0011]   Creating CustomResourceDefinition "catalogsources.operators.coreos.com" 
INFO[0011]   Creating CustomResourceDefinition "clusterserviceversions.operators.coreos.com" 
INFO[0011]   Creating CustomResourceDefinition "installplans.operators.coreos.com" 
INFO[0011]   Creating CustomResourceDefinition "operatorgroups.operators.coreos.com" 
INFO[0012]   Creating CustomResourceDefinition "operators.operators.coreos.com" 
INFO[0012]   Creating CustomResourceDefinition "subscriptions.operators.coreos.com" 
INFO[0012]   Creating Namespace "olm"                   
INFO[0012]   Creating Namespace "operators"             
INFO[0013]   Creating ServiceAccount "olm/olm-operator-serviceaccount" 
INFO[0013]   Creating ClusterRole "system:controller:operator-lifecycle-manager" 
INFO[0013]   Creating ClusterRoleBinding "olm-operator-binding-olm" 
INFO[0013]   Creating Deployment "olm/olm-operator"     
INFO[0013]   Creating Deployment "olm/catalog-operator" 
INFO[0014]   Creating ClusterRole "aggregate-olm-edit"  
INFO[0014]   Creating ClusterRole "aggregate-olm-view"  
INFO[0014]   Creating OperatorGroup "operators/global-operators" 
INFO[0015]   Creating OperatorGroup "olm/olm-operators" 
INFO[0016]   Creating ClusterServiceVersion "olm/packageserver" 
INFO[0016]   Creating CatalogSource "olm/operatorhubio-catalog" 
INFO[0017] Waiting for deployment/olm-operator rollout to complete 
INFO[0017]   Waiting for Deployment "olm/olm-operator" to rollout: 0 of 1 updated replicas are available 
INFO[0023]   Deployment "olm/olm-operator" successfully rolled out 
INFO[0023] Waiting for deployment/catalog-operator rollout to complete 
INFO[0023]   Waiting for Deployment "olm/catalog-operator" to rollout: 0 of 1 updated replicas are available 
INFO[0028]   Deployment "olm/catalog-operator" successfully rolled out 
INFO[0028] Waiting for deployment/packageserver rollout to complete 
FATA[0028] Failed to install OLM version "latest": deployment/packageserver failed to rollout: deployments.apps "packageserver" not found
```

In fact, though it reports that the installation failed, actually installation was successful. The immediate `operator-sdk status` shows that:

```
$ operator-sdk olm status
INFO[0001] Fetching CRDs for version "0.16.1"           
INFO[0005] Fetching resources for version "0.16.1"      
INFO[0009] Successfully got OLM status for version "0.16.1" 

NAME                                            NAMESPACE    KIND                        STATUS
operators.operators.coreos.com                               CustomResourceDefinition    Installed
operatorgroups.operators.coreos.com                          CustomResourceDefinition    Installed
installplans.operators.coreos.com                            CustomResourceDefinition    Installed
clusterserviceversions.operators.coreos.com                  CustomResourceDefinition    Installed
olm-operator                                    olm          Deployment                  Installed
subscriptions.operators.coreos.com                           CustomResourceDefinition    Installed
olm-operator-binding-olm                                     ClusterRoleBinding          Installed
operatorhubio-catalog                           olm          CatalogSource               Installed
olm-operators                                   olm          OperatorGroup               Installed
aggregate-olm-view                                           ClusterRole                 Installed
catalog-operator                                olm          Deployment                  Installed
aggregate-olm-edit                                           ClusterRole                 Installed
olm                                                          Namespace                   Installed
global-operators                                operators    OperatorGroup               Installed
operators                                                    Namespace                   Installed
packageserver                                   olm          ClusterServiceVersion       Installed
olm-operator-serviceaccount                     olm          ServiceAccount              Installed
catalogsources.operators.coreos.com                          CustomResourceDefinition    Installed
system:controller:operator-lifecycle-manager                 ClusterRole                 Installed
```

This is what the issue the PR supposed to address.

**Comment by avalluri** [comment]
@camilamacedo86  Is there any chance to reopen this PR, it is a must to have change to use `operator-sdk` in our [PMEM-CSI](https://https://github.com/intel/pmem-csi) project's CI. Currently,  we had to build the `operator-sdk` binary from the source by applying this patch.

**Pull request closed without merging**
