### PR TITLE
[docs] Introduce algolia search for doc site

### PR DESCRIPTION
**Pull request by sujil02**
This PR is in favor of 4001

Description of the change:

This PR implements algolia search for https://sdk.operatorframework.io

Motivation for the change:

Algolia is a powerful search API that is being used in a majority
of open source documentation site. Besides creating a index for the site that is updated every
hour, we get analytics like so:

The OLM doc site currently uses algolia search too.

Checklist

If the pull request includes user-facing changes, extra documentation is required:

 Add a new changelog fragment in changelog/fragments (see changelog/fragments/00-template.yaml)
 Add or update relevant sections of the docs website in website/content/en/docs

### CODE REVIEW

**Comment by theishshah** [comment]
The logic to enable search looks good - do we need to directly commit the search API key, or is this something that we should be sheilding? @jmrodri thoughts?

**Comment by camilamacedo86** [comment]
Hi @sujil02, 

We are unable to test that in the preview. Could you do any small change in the docs for we check the preview and see if it is working?

**Comment by sujil02** [comment]
@camilamacedo86 @theishshah @marc-obrien @anik120 
I updated the API keys on my local build the site on the Hugo server and did multiple searches the search keywords and indexes reflects back on algolia account... hence I can validate the key and indices are correct... we need to merge the PR so the search can we available on the hosted site.

Once this PR is merged I have to work on enhancing our config with the algolia here https://github.com/algolia/docsearch-configs/blob/94e1ab95801416f829cbbab8dfb8b45c7aa7434e/configs/sdk-operatorframework.json to enhance search results

**Comment by anik120** [comment]
@sujil02 I think @camilamacedo86's ask is to introduce a small change in any of the doc (a simple new line will probably do the job) so that folks who can lgtm/approve the PR can test it out before they lgtm/approve.

**Comment by jmrodri** [comment]
> The logic to enable search looks good - do we need to directly commit the search API key, or is this something that we should be sheilding? @jmrodri thoughts?

Seems like we need to to create a search API key not sure what the indices we have but looks like we can narrow it down pretty well, based on this documentation https://www.algolia.com/doc/guides/security/api-keys/

**Review by theishshah — APPROVED** [review]

**Pull request merged**
