### PR TITLE
.github/workflows: add rerun-actions action to rerun other actions by comment

### LINKED ISSUE #3712: I would like to be able to rerun my own travis jobs.
## Feature Request
To manually restart jobs in travis, you need admin privileges on the linked github repo. It would be great if non-admin developers (such as myself), had a mechanism to rerun tests in the event of a flake or what have you. I know the main kube repos have a git robot that can do this if you comment '/retest'.

**Is your feature request related to a problem? Please describe.**
I can't rerun my own tests without forcefully changing the commit SHA somehow. I cannot rerun tests on others PRs at all.

**Describe the solution you'd like**
Some way to kick travis tests.

### PR DESCRIPTION
**Pull request by estroz**
**Description of the change:** rerun failed actions with `/test <action name>` or all failed actions with `/retest` (same commands as prow)

**Motivation for the change:** closes #3712 

See [test PR](https://github.com/estroz/operator-sdk/pull/14) and corresponding [actions runs](https://github.com/estroz/operator-sdk/runs/1581202133?check_suite_focus=true).

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Comment by estroz** [comment]
We may want to move this action from my namespace to an `operator-framework/release-tools` repo.

/cc @jberkhahn

**Comment by estroz** [comment]
The rerunner will need to respect OWNERS/OWNERS_ALIAS files before merging, so `ok-to-test` does not have to be applied to approver/reviewer PRs.

/hold

**Comment by estroz** [comment]
The rerunner now respects org/repo membership and privileged status.

/hold cancel

**Review by jmrodri — APPROVED** [review]
/lgtm

**Pull request merged**
