### PR TITLE
images/scorecard-test-kuttl: re-add entrypoint script

### PR DESCRIPTION
**Pull request by estroz**
**Description of the change:** add images/scorecard-test-kuttl/entrypoint

**Motivation for the change:** was removed in #4069 but shouldn't have been.

/cc @jmccormick2001 

/kind bug

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Review by jmccormick2001 — APPROVED** [review]

**Review by jmrodri — APPROVED** [review]
This used to be in `images/scorecard-test-kuttl/bin/entrypoint` do we care?

**Comment by estroz** [comment]
Going to test this locally first

/hold

**Comment by estroz** [comment]
I changed image builds around a bit. Previously they built in the context of the binary build directory (`build/_image`). Now they build in the `images/` subdirectory pertaining to that image so that any files that need to be `COPY`d into the image can be; binaries are copied from `build/_image` to `images/<binary name>/bin` the `COPY`d into the image.

**Pull request merged**
