### PR TITLE
readme.md shell command bug fix

### PR DESCRIPTION
**Pull request by claud-kim**
set go env gopath
build mod command

**Description of the change:**

**Motivation for the change:**

### CODE REVIEW

**Comment by hasbro17** [comment]
@claud-kim Can you please explain what is the bug that you're seeing without these two changes?

The `$GOPATH` env should already be set since it's a prerequisite that you're working on a Go project.

And we don't make the choice of creating a vendor directory for users by default. You can choose to do that yourself with `operator-sdk new <project-name> --vendor=true`.

See: https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md#vendoring

**Comment by claud-kim** [comment]
> @claud-kim Can you please explain what is the bug that you're seeing without these two changes?
> 
> The `$GOPATH` env should already be set since it's a prerequisite that you're working on a Go project.
> 
> And we don't make the choice of creating a vendor directory for users by default. You can choose to do that yourself with `operator-sdk new <project-name> --vendor=true`.
> 
> See: https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md#vendoring


When I only had quick start, it did not work properly.

**Comment by LiliC** [comment]
@claud-kim were you using master or a release when this did not work for you?

**Comment by hasbro17** [comment]
@claud-kim Can you please provide the exact steps, output and operator-sdk version for which the README instructions did not work for you.

Or better yet can you please open a bug report first.
https://github.com/operator-framework/operator-sdk/issues/new?assignees=&labels=&template=bug-report.md&title=

**Pull request closed without merging**
