### PR TITLE
Makefile: add help to major targets.

### PR DESCRIPTION
**Pull request by jmrodri**
Makefiles can sometimes be cumbersome to read. This little patch allows
you to run `make help` and see what targets do and what's available.

Right now I didn't document the ones with / in them but we can certainly
add support for that. I hope I got the help messages right.

### CODE REVIEW

**Comment by estroz** [comment]
/hold
@jmrodri thanks for opening a PR. I do not think these additions are necessary though. `make` semantics are fairly well known and recipe names are indicative of what they execute, so reading the `Makefile` should give you an idea of what recipes are available. These additions clutter the makefile unnecessarily as well.
@hasbro17 @AlexNPavel WDYT

**Comment by AlexNPavel** [comment]
I agree with @estroz, I don't think these additions are necessary. Also, `make image` is not intended to be run outside of travis (technically, `make image/push` can't be run outside of travis; `make image/build` can be run outside of travis).

**Comment by jmrodri** [comment]
@estroz I agree `Makefile` semantics are fairly well known. Just found this helpful especially since I opened it up and was curious what contributors would run.

@AlexNPavel That's actually why we added it to our Makefile because there were tasks that weren't really useful to most folks outside the team. https://github.com/openshift/ansible-service-broker/blob/master/Makefile

I'll let others respond, but if it's not needed or wanted I can just close it at that time.

Thanks for looking at it.

**Comment by shawn-hurley** [comment]
So, you mentioned that some targets are ok to run(image/build)  while others are not (image/push), and the high-level target is not(image). This all seems fairly confusing to me. 

I would think cleaning this up so that there are targets for developers and targets for CI makes a ton of sense, and this PR could at least document what was in your head in the makefile so that new contributors understand IMO.

**Comment by jmrodri** [comment]
The docs are required to explain the `Makefile`.
https://github.com/operator-framework/operator-sdk/blob/master/doc/dev/testing/running-the-tests.md#running-the-tests

While `make help` is not a replacement for good documentation, it is a good reminder of 'hrm which target was it again?'

**Comment by jmrodri** [comment]
Too old and not wanted.

**Pull request closed without merging**
