### PR TITLE
Revert "*: Replace 'docker build . -t ${IMG}' with '-t ${IMG} .' 

### PR DESCRIPTION
**Pull request by jmrodri**
This reverts commit 34e4a359b8fd643d1f06808ca3b6f2179a1e77f5.

Signed-off-by: jesus m. rodriguez <jmrodri@gmail.com>

### CODE REVIEW

**Comment by jmrodri** [comment]
Looks like e2e-ansible passes so we need this in to fix master.

**Comment by estroz** [comment]
#4478 is also passing though.

**Comment by jmrodri** [comment]
/hold 
If master is broken then merge this. Otherwise, we can close.

**Comment by estroz** [comment]
@jmrodri looks like master is fine, can you close this?

**Comment by jmrodri** [comment]
@estroz great. Closing this out.

**Pull request closed without merging**
