### PR TITLE
change rerun github action to point at the operator-framework repo

### LINKED ISSUE #5239: Move rerun actions repo into OF org
CI uses Eric's action to give contributors the ability to rerun their actions. Since its part of CI, we should move it into the org.

https://github.com/estroz/rerun-actions

### PR DESCRIPTION
**Pull request by jberkhahn**
Fixes #5239

Hopefully the github release has gone through pipes so this works.

### CODE REVIEW

**Review by everettraven — APPROVED** [review]
/lgtm

Just need to sign the commit to make DCO happy :)

**Comment by jberkhahn** [comment]
/do-not-merge

something weird is going on with the e2e test

**Comment by everettraven** [comment]
@jberkhahn Which e2e test? There is one that is flaky that fails due to some metric counter being off. I am going to create an issue for it and discuss it during triage on monday. In the past I have just reran it until it has passed but I think we can probably move forward with this PR even if that check is failing.

**Comment by jberkhahn** [comment]
the go/v3 e2e one that checks that scaling the size of the memcached increases the deployment size

**Review by everettraven — APPROVED** [review]
/lgtm

**Review by laxmikantbpandhare — APPROVED** [review]
/lgtm

**Pull request merged**
