### PR TITLE
Add migration docs to website

### PR DESCRIPTION
**Pull request by bharathi-tenneti**
Description: Add migration docs to website.

Closes: #2694

### CODE REVIEW

**Comment by estroz** [comment]
Is there a way to prevent subsection headers from becoming side menu sections? The side section is pretty cluttered. There should still be subsections in the version section itself, just not in the side menu.
Screenshot from 2020-03-31 14-12-16
It would be nice to see just the `vX.Y.Z` sections.

**Comment by jmrodri** [comment]
> Is there a way to prevent subsection headers from becoming side menu sections? The side section is pretty cluttered. There should still be subsections in the version section itself, just not in the side menu.
> Screenshot from 2020-03-31 14-12-16
> It would be nice to see just the `vX.Y.Z` sections.

I suspect it's picking them up by their markdown header tags. We might have to wait for @asmacdo to come back. I'll see if I can find out more info tomorrow.

**Comment by jmrodri** [comment]
I think we need to update the _index.md page which has a Warning in it. We forgot to do that in PR #2750

**Comment by jmrodri** [comment]
@asmacdo do you know the answers to @estroz and @jmrodri questions?

**Comment by asmacdo** [comment]
AFAICT the right side navigation goes through the md headers like @jmrodri suggested. It looks like demotion (`##` -> `###`, etc) isn't going to do the trick. Instead I suggest we leave the version numbers as they are, but replace the md headers from the subsections with `**bold**`

**Comment by asmacdo** [comment]
Changes look awesome. lgtm.

**Pull request merged**
