### PR TITLE
Docs: Clarification about the use of index image in run bundle(-upgrade)

### PR DESCRIPTION
**Pull request by VenkatRamaraju**
**Description of the change:**
Added a clarification to docs about the use of `--index-image` flag while invoking run bundle.

**Motivation for the change:**
More precise. If an author runs an upgrade on a bundle that was installed with an index image, the default bundle add mode is "replaces" instead of "semver". This means that the upgraded CSV must have a replaces field that points to an older version of the operator, otherwise the upgrade process will timeout.

### CODE REVIEW

**Review by rashmigottipati — COMMENTED** [review]
Will it be better if we add this clarification to [quickstart bundle docs](https://github.com/operator-framework/operator-sdk/blob/38abdb7d9c8c4431a8ecbd0ef34f0936f70ead72/website/content/en/docs/olm-integration/quickstart-bundle.md) or [bundle tutorial](https://github.com/operator-framework/operator-sdk/blob/38abdb7d9c8c4431a8ecbd0ef34f0936f70ead72/website/content/en/docs/olm-integration/tutorial-bundle.md) since that's where we have relevant content for both `run bundle`  and `run bundle-upgrade` commands?

**Comment by VenkatRamaraju** [comment]
@rashmigottipati Quickstart and Tutorial seem to only detail the default case, i.e., without the use of the index image flag. That's why I added this to the bundle generation docs. I'm okay with adding it to the tutorial if you think this should be there.

**Comment by rashmigottipati** [comment]
@VenkatRamaraju I think that would be better. In [bundle tutorial](https://github.com/operator-framework/operator-sdk/blob/38abdb7d9c8c4431a8ecbd0ef34f0936f70ead72/website/content/en/docs/olm-integration/tutorial-bundle.md), we can add some context of `run bundle` with the `--index-image` flag and add this clarification to it. We don't have to capture the command logs for this, since it will be the same as the default case.

Users are most likely going to refer to this doc when trying to test their bundles using these commands.

**Review by rashmigottipati — APPROVED** [review]
/lgtm

**Review by asmacdo — APPROVED** [review]
/lgtm

**Pull request merged**
