### PR TITLE
bump java plugins

### PR DESCRIPTION
**Pull request by jmrodri**
**Description of the change:**
Bump the java plugin so that it picks up the recent `Makefile` changes.

**Motivation for the change:**
The java plugin now has a `Makefile` which we'd like to include in the first release of the plugin with the SDK.

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Comment by jmrodri** [comment]
```
[jesusr@transam java-op]$ ls
[jesusr@transam java-op]$ operator-sdk init --plugins quarkus  --domain zeusville.com --project-name java-op
[jesusr@transam java-op]$ ls
Makefile  pom.xml  PROJECT  src/
```

**Review by rashmigottipati — APPROVED** [review]
/lgtm

**Review by laxmikantbpandhare — APPROVED** [review]
/lgtm

**Review by estroz — APPROVED** [review]
/lgtm

**Pull request merged**
