### PR TITLE
Add OchiengEd to sdk-approvers

### PR DESCRIPTION
**Pull request by OchiengEd**
**Description of the change:**

Add @OchiengEd  to operator sdk approvers

**Motivation for the change:**

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Review by varshaprasad96 — APPROVED** [review]
/lgtm
/approve

**Review by everettraven — APPROVED** [review]
/approve
/lgtm

**Comment by everettraven** [comment]
Sanity check is a flake. Forcing the merge

**Comment by grokspawn** [comment]
Unfortunately, these changes didn't update the .cncf_maintainers file as part of updating OWNERS_ALIASES.  Such changes need to re-run `make generate`. 😞

**Pull request merged**
