### PR TITLE
snap

### PR DESCRIPTION
**Pull request by mikeroyal**
Added snapcraft.yaml to build a [snap](https://snapcraft.io/).

**Description of the change:**
Added snapcraft.yaml to build a snap package to install operator-sdk on Linux.

**Motivation for the change:**
Snap package's support installing applications across 41 Linux distributions.

### CODE REVIEW

**Comment by hasbro17** [comment]
@mikeroyal Thanks for the PR. I'm not too familiar with snap packages but in general I'm not sure we have a consensus on whether we're intending to maintain deb/rpm/snap pkgs for each release.

Mostly I don't see a reason not to just curl the SDK release binary directly from the release page.

@joelanford We should probably discuss if we want to maintain release packages going forward.

So far we do have a process to update the brew formula for the operator-sdk but that's pretty much sourcing the operator-sdk binary from each release.
https://github.com/Homebrew/homebrew-core/blob/master/Formula/operator-sdk.rb

**Comment by mikeroyal** [comment]
Hi @hasbro17, I will say snaps are easier to maintain than deb/rpm because snaps can auto-update to new versions or auto-revert back to a previous version if something breaks on the system. I would also do my part in making sure the snap stayed up to date if there was a interest. So just think about it with other team members and see if there any interest.

**Comment by estroz** [comment]
I'm in the camp of maintaining a release binary and nothing more for now. We should not commit to a particular package manager without more discussion. There should be a proposal doc submitted first detailing which managers we'll maintain configs for and a discussion in that PR.

**Comment by hasbro17** [comment]
@mikeroyal Sorry, I forgot to follow up on this.

While snap does seem like it would be easier to maintain, our general consensus is that we would rather not put package manager specific code in the core SDK repo. While it may not be too much work to update now, it opens the door for maintaining more ways to install the SDK in the future. 

Perhaps we can have add a snap repo for the SDK to https://github.com/snapcrafters
And hopefully if you're interested we can keep that updated after every release.

**Comment by mikeroyal** [comment]
Hi @hasbro17,

Thanks for getting to back me. I think the idea of adding a snap repo for the SDK to https://github.com/snapcrafters is great :100: and I'll help out in anyway I can!

**Pull request closed without merging**
