### PR TITLE
add link to compilation prerequisites

### PR DESCRIPTION
**Pull request by arve0**
**Description of the change:**
Link to compilation prerequisites.

**Motivation for the change:**
Link is missing.

**Checklist**

Pull request does not include user-facing changes.

### CODE REVIEW

**Comment by arve0** [comment]
> The currently supported Kubernetes version will always be listed in the SDK [prerequisites section][doc-readme-prereqs].

Version of kubernetes is not mentioned in the documentation, though version of kubectl is. Maybe I've linked to the wrong place?

**Review by camilamacedo86 — APPROVED** [review]
/lgtm

**Review by camilamacedo86 — CHANGES_REQUESTED** [review]
IMO we need to add 2 links:

- (a) https://sdk.operatorframework.io/docs/installation/install-operator-sdk/#prerequisites-for-compilation
- (b) https://sdk.operatorframework.io/docs/installation/install-operator-sdk/#prerequisites

So, we would need to : 

Replace `Release binaries will be built with the Go compiler version specified in the Operator SDK's prerequisites section.` with `Release binaries will be built with the Go compiler version specified in the Operator SDK's prerequisites for compilation section` and add the link (a)

And then the link (b) would be for `As the Operator SDK interacts directly with the Kubernetes API, certain API features are assumed to exist in the target cluster. The currently supported Kubernetes version will always be listed in the SDK prerequisites section.`

WDYT?

**Comment by arve0** [comment]
Haha, the links are already 404. What a mess 🙈

**Pull request closed without merging**
