### PR TITLE
hack/ci/setup-build-dependencies.sh: add setup script in SDK repo

### PR DESCRIPTION
**Pull request by joelanford**
**Description of the change:**
Adds a setup script that can be used in OpenShift CI

**Motivation for the change:**
We currently [hard-code the `dep` setup commands](https://github.com/openshift/release/blob/master/ci-operator/config/operator-framework/operator-sdk/operator-framework-operator-sdk-master.yaml#L8) in the openshift/release repo.

Once this script is merged into master, we can update the OpenShift CI configuration to use it, which then gives us the flexibility to change the test setup from the SDK repo, rather than having to make coordinating changes in openshift/release.

This will be helpful in migrating the SDK from using `dep` to go modules (see #1566)

/cc @AlexNPavel

### CODE REVIEW

**Comment by joelanford** [comment]
@LiliC Probably just because the original command hasn't been updated in awhile. I'll bump the version.

**Comment by LiliC** [comment]
> @LiliC Probably just because the original command hasn't been updated in awhile. I'll bump the version.

To test it you can try to bump it in our [.travis.yaml](https://github.com/operator-framework/operator-sdk/blob/master/.travis.yml#L20) to see if we run into any problems. I wanted to suggest calling this script there, but since we are moving away from travis doesn't make much sense I guess.

**Comment by joelanford** [comment]
@LiliC I bumped to `v0.5.3`. Looks like `v0.5.4` isn't quite released or something. There are no binaries on the dep release page for it.

I also updated `.travis.yml` so we can make sure it still works. I also thought about using this script in `.travis.yml`, but we also do things slightly different there (e.g. use `travis_retry dep ensure -v` instead of `make dep`)

**Comment by LiliC** [comment]
@joelanford yes noticed that as well, not sure what happened in that "release".

Still lgtm on green of course 👍

**Pull request merged**
