### PR TITLE
Fix wrong GH download URL

### PR DESCRIPTION
**Pull request by mmuzikar**
**Description of the change:**

**Motivation for the change:**
The original link leads to 404 page.

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Review by varshaprasad96 — APPROVED** [review]
/lgtm

**Comment by everettraven** [comment]
@mmuzikar You are correct that using the exact link `https://github.com/operator-framework/operator-sdk/releases/download/v1.23.0` results in a 404. 

However we use that as a base url for specifying which binary to download using that link. For example, `curl -LO https://github.com/operator-framework/operator-sdk/releases/download/v1.23.0/operator-sdk_linux_amd64` will result in downloading the binary named `operator-sdk_linux_amd64` while `curl -LO https://github.com/operator-framework/operator-sdk/releases/tag/v1.23.0/operator-sdk_linux_amd64` will download the HTML contents of the page https://github.com/operator-framework/operator-sdk/releases/tag/v1.23.0/operator-sdk_linux_amd64

Due to this, we should not merge this as it actually breaks the installation steps in the docs by installing the HTML of the release page instead of the actual binary.

/hold

**Comment by everettraven** [comment]
CC @varshaprasad96 see: https://github.com/operator-framework/operator-sdk/pull/6043#issuecomment-1261174508

**Comment by varshaprasad96** [comment]
good catch @everettraven!
@mmuzikar as @everettraven mentioned `OPERATOR_SDK_DL_URL` is the base URL, and the specific OS and ARCH are further used to determine which binary is to be downloaded. As this is what is expected, I'm closing this PR. Please feel free to create an issue/PR if you find anything unexpected in docs. Thanks for your contribution, we do appreciate it!

**Pull request closed without merging**
