### PR TITLE
(refactor): switch the ansible plugin to use github.com/operator-framework/ansible-operator-plugins, remove ansible code

### LINKED ISSUE #6355: Ansible Operator Plugin Extraction
## Motivation
The extraction of the Ansible Operator Plugin (and other associated items) is meant to help simplify the maintenance burden of the Operator-SDK by only keeping the components that are essential to the core Operator-SDK CLI in the Operator-SDK repository.

By extracting the Ansible Operator Plugin from the Operator-SDK repository and moving it to it's own repository, we ensure that we can iterate and make changes to the Ansible Operator Plugin's master branch without causing the Operator-SDK CI and/or releases to break.

## Goals

- The Ansible Operator Plugin and it's related components no longer live in https://github.com/operator-framework/operator-sdk and instead live in it's own repository under the Operator Framework GitHub Organization (maybe operator-framework/ansible-operator-plugin?)

## How can we accomplish this?
After some discussion in the community, there are a few open questions that this section will provide potential solutions for:
- What code do we actually need to move?
- How can we test the Ansible Operator Plugin?
- How are we going to version and release the Ansible Operator Plugin?

### Component Extraction
At a high level, the following would need to be extracted:
- Ansible Operator binary
- Ansible Operator images
- Ansible Operator Plugin
- Ansible Operator Controller code

At a lower level, the following sections of code would likely need to be moved:
- Binary:
    - https://github.com/operator-framework/operator-sdk/tree/master/cmd/ansible-operator
    - https://github.com/operator-framework/operator-sdk/tree/master/internal/cmd/ansible-operator
- Images:
    - https://github.com/operator-framework/operator-sdk/tree/master/images/ansible-operator
    - https://github.com/operator-framework/operator-sdk/tree/master/images/ansible-operator-2.11-preview
- Plugin:
    - https://github.com/operator-framework/operator-sdk/tree/master/internal/plugins/ansible/v1
- Controller:
    - https://github.com/operator-framework/operator-sdk/tree/master/internal/ansible

We would also need to remove from the Operator-SDK:
- Testdata generation:
    - https://github.com/operator-framework/operator-sdk/tree/master/hack/generate/samples/molecule
    - https://github.com/operator-framework/operator-sdk/tree/master/hack/generate/samples/internal/ansible
- Testdata:
    - https://github.com/operator-framework/operator-sdk/tree/master/testdata/ansible/memcached-operator
- Ansible related CI:
    - https://github.com/operator-framework/operator-sdk/blob/master/.github/workflows/test-ansible.yml
    - https://github.com/operator-framework/operator-sdk/blob/master/.github/workflows/deploy-manual.yml
- Makefile targets:
    - https://github.com/operator-framework/operator-sdk/blob/9d2f672c8e5bb0af8d0b5955cfa673aad21f1281/Makefile#L98-L101
    - https://github.com/operator-framework/operator-sdk/blob/9d2f672c8e5bb0af8d0b5955cfa673aad21f1281/Makefile#L196-L201

>**Note**: We shouldn't remove anything from the main Operator-SDK repository until the extraction of the Ansible Operator Plugin is completed.

### Testing
An important part of extracting this plugin is ensuring that we are still able to test the plugin and the associated components. Unit testing things like the Ansible Operator binary and the controller implementations should be relatively easy as it should be a direct port.

E2E testing is where it gets a little trickier but I think can be done in a couple different ways.

#### Building the SDK from source, substituting the plugin dependency
One way in which we can e2e test the plugin is to clone the Operator-SDK source, substitute the plugin dependency with a local version in the go.mod, build the Operator-SDK and then continue on testing the same way the Operator-SDK currently does.

To substitute the plugin dependency we would need to inject a dependency replacement in the go.mod that looks like:
```go
replaces (
    github.com/operator-framework/ansible-operator-plugin@v1 => /path/to/local/ansible-operator-plugin
)
```

This process is a fairly complex e2e workflow, but ensures that the ansible operator plugin changes will work with the current changes in the Operator-SDK repository.

#### Using Kubebuilder CLI library
Since the Operator-SDK utilizes the the Kubebuilder CLI library to actually handle the scaffolding logic and plugins, we could use the same Kubebuilder CLI library to create our testdata. While this means it doesn't get built into the Operator-SDK binary for testing, it would be following a very similar (if not identical) flow. This would keep the e2e workflow much more simple and entirely contained to the ansible operator plugin repository.

This would mean implementing a testdata generation script that creates and runs the testdata CLI. This could look something like:
```go
// Keeping this very simple, but for higher confidence in our testing we
// could ensure the bundle uses all the same plugins the Operator-SDK uses
ansibleBundle, _ := plugin.NewBundle("ansible"+plugins.DefaultNameQualifier, plugin.Version{Number: 1},
	ansiblev1.Plugin{},
)

c, err := cli.New(
	cli.WithCommandName("ansible-plugin-tester"),
	cli.WithVersion("v1"),
	cli.WithPlugins(
		ansibleBundle,
	),
	cli.WithDefaultPlugins(cfgv3.Version, ansibleBundle),
	cli.WithDefaultProjectVersion(cfgv3.Version),
)

if err != nil {
	log.Fatal(err)
}

```

This way we have a minimal CLI that closely mimics the Operator-SDK used specifically for our testdata generation. Once the testdata is generated, we can follow the same process that is used by the Operator-SDK  for it's current e2e testing.

### Versioning and Releasing
Moving the Ansible Operator Plugin to it's own repository would mean we need to release and version this repository separately from the Operator-SDK.

The majority of the effort would be around creating the release process, which would likely require writing automation and release scripts to create a release based on a pushed tag. For a particular release version the following artifacts should be produced:
- Ansible Operator binary
- Ansible Operator images

A potential versioning strategy for this separate repository would be to start the first release after extraction at v1.0.0 (the current version of the ansible plugin) and follow semver for future releases. Ideally there are no changes made to the core of the ansible operator plugin during the extraction process and a v1.0.0 release is cut immediately after the extraction is finalized.

### PR DESCRIPTION
**Pull request by everettraven**
**Description of the change:**
- Removes ansible plugin and ansible-operator logic in favor of using the new https://github.com/operator-framework/ansible-operator-plugins repo for housing this logic. We now import the ansible plugin from this new repo
- There should be no user facing changes

**Motivation for the change:**
- resolves #6355 

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Comment by everettraven** [comment]
Not sure why the e2e-molecule check still shows up as expected. Going to try closing and re-opening to see if it clears it up

**Review by grokspawn — APPROVED** [review]

**Comment by oceanc80** [comment]
Might want to remove deploy-manual step from the releasing guide. Otherwise lgtm

**Comment by everettraven** [comment]
@oceanc80  done in https://github.com/operator-framework/operator-sdk/pull/6583/commits/9e103097b89cf63b64203cd3647af90d1a94d946

**Pull request merged**
