### PR TITLE
Release v1.3.0

### PR DESCRIPTION
**Pull request by estroz**
Release PR

### CODE REVIEW

**Comment by estroz** [comment]
The sanity check is failing because netlify hasn't updated its branch mappings yet. After that it should pass.

**Review by jmrodri — APPROVED** [review]
;lgtm

**Comment by jmrodri** [comment]
@estroz feel free to merge

**Review by varshaprasad96 — APPROVED** [review]

**Comment by estroz** [comment]
Force-merging this since netlify's branch-DNS name mappings are not working right now.

**Pull request merged**
