### PR TITLE
log error for url verification failure

### PR DESCRIPTION
**Pull request by germondc**
**Description of the change:**
Simply logs the already generated error prior to exiting

**Motivation for the change:**
Prevent silent exit of ansible-operator when URL fails verification.

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

Apologies if I haven't followed the process correctly.

### CODE REVIEW

**Review by varshaprasad96 — APPROVED** [review]
/lgtm

**Comment by varshaprasad96** [comment]
@germondc Thanks for the PR! Could you please sign the commit with `git commit --amend --no-edit --signoff`

**Comment by germondc** [comment]
> @germondc Thanks for the PR! Could you please sign the commit with `git commit --amend --no-edit --signoff`

Sure thing. I have done so and pushed.

**Comment by camilamacedo86** [comment]
Is not it missing the changelog with the fix?

**Comment by germondc** [comment]
> Is not it missing the changelog with the fix? (see [changelog/fragments/00-template.yaml](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
> 
> WDYT about adding this one for we have this fix in the release notes?

Such a small change, hardly seemed worth a changelog :) I have added one.

**Pull request merged**
