### PR TITLE
[v1.2.x] Post-release v1.2.0

### PR DESCRIPTION
**Pull request by estroz**
**Description of the change:** see #4211 

**Motivation for the change:** #4211

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Review by jmrodri — APPROVED** [review]
/lgtm

**Review by rashmigottipati — APPROVED** [review]
/lgtm

**Comment by estroz** [comment]
Superseded by #4213

**Pull request closed without merging**
