### PR TITLE
Scorecard kuttl image

### PR DESCRIPTION
**Pull request by jmccormick2001**
**Description of the change:**
this PR adds the scorecard-test-kuttl image to the travis configuration.  It will deploy the scorecard-test-kuttl (amd64) image to quay.io.  Other architectures will require kuttl base images to also support more than just amd64 architectures and will be added in follow on work if required.

**Motivation for the change:**
a new scorecard-test-kuttl image is made available and meant to be released.

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Comment by jmccormick2001** [comment]
https://travis-ci.com/github/jmccormick2001/operator-sdk/builds/174678026
this is the all green from the Travis CI build on the forked branch used for this PR.

**Comment by camilamacedo86** [comment]
Hi @jmccormick2001, 

Just a few nits.
- It shows missing the other arch types. See: 
Screenshot 2020-07-08 at 11 03 48
- This image is useful to users. Am I right? So, should we not have fragment and docs to let them know how and when using it?

**Comment by jmccormick2001** [comment]
> Hi @jmccormick2001,
> 
> Just a few nits.
> 
> * It shows missing the other arch types. See:
> 
> Screenshot 2020-07-08 at 11 03 48
> 
> - This image is useful to users. Am I right? So, should we not have fragment and docs to let them know how and when using it?

the other architectures are not available at the moment due to the kuttl image only supports amd64 currently.  The user docs were already merged.  Since this was a new image I didn't think a changelog fragment was necessary given the new user facing documentation, but could add one if you think that is still necessary.

**Comment by jmccormick2001** [comment]
https://github.com/operator-framework/operator-sdk/blob/master/changelog/fragments/3278-add-scorecard-kuttl-image.yaml  

I had added that changelog it appears in PR 3278.

**Pull request merged**
