### PR TITLE
Pipenv

### PR DESCRIPTION
**Pull request by reinvantveer**
**Description of the change:**
Use [Pipenv](https://pipenv.pypa.io/en/latest/) - the Python packaging authority recommended way - as a dependency resolution managemente system and vulnerability checker to install Python dependencies. 

This PR is part of #4237 to work towards a more user-friendly way of doing reproducible local builds

**Motivation for the change:**
Python package dependency is best managed using a fit-for-purpose package manager that checks for dependency conflicts, separates wanted dependencies from required subdependencies and that is able to check for vulnerabilities. The proposed solution is fully backwards compatible.

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [x] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Comment by reinvantveer** [comment]
https://github.com/operator-framework/operator-sdk/pull/4477#discussion_r570484392 was accepted here

**Comment by reinvantveer** [comment]
I guess 5 commits in a PR is better than 380 😆

**Review by estroz — COMMENTED** [review]
@reinvantveer wdyt about `pip freeze`-ing all deps, to avoid issues [like this](https://github.com/operator-framework/operator-sdk/pull/4510)?

**Comment by reinvantveer** [comment]
> 
> 
> @reinvantveer wdyt about `pip freeze`-ing all deps, to avoid issues [like this](https://github.com/operator-framework/operator-sdk/pull/4510)?

@estroz 👍  This question couldn't have come at a better time. This PR already solves this, in https://github.com/operator-framework/operator-sdk/pull/4494/files#diff-82452578a3e817b3b4dc5c154471041589c4b535216c59dbd8982bc18e2f8d32R125 and using `pipenv install --deploy`, which will only install the versions from Pipfile.lock

So in short: yes I think pinning is good here and pipenv provides a solid method to implement this.

**Comment by reinvantveer** [comment]
@estroz I'd consider pinning `cryptography` in the Pipfile, but only if future versions of the package are expected to break: looks like 3.4.4 still requires a Rust compiler. But instead of pinning, we could also consider adding (and uninstalling) the Rust compiler to the Dockerfile. It just wouldn't help things along in having a local (i.e. non-dockerized) environment, with an extra compiler added to the mix. I guess it's up to you to choose either way. Would you rather
- pin the version in the Pipfile to prevent `pipenv update`-ing to `cryptography` versions requiring a Rust compiler or
- add the Rust compiler to the Dockerfile recipe to be able to follow along with updates on `cryptography`
?

**Comment by estroz** [comment]
@reinvantveer I totally missed the lock file, awesome!

>add the Rust compiler to the Dockerfile recipe

I’m in favor of this option.

**Comment by reinvantveer** [comment]
> 
> 
> @reinvantveer I totally missed the lock file, awesome!
> 
> > add the Rust compiler to the Dockerfile recipe
> 
> I’m in favor of this option.

@estroz Cool. I do some Rust programming in my spare time and it's awesome. If it's OK with you I'd like to process this PR first before diving into the Rust compiler to upgrade the cryptography package. This PR is pretty much self-contained (with the whole pinning business through the lockfile) so it should be the first next step I think.

**Review by estroz — APPROVED** [review]
/lgtm

**Comment by estroz** [comment]
@varshaprasad96 you can just make the bump on [this line](https://github.com/operator-framework/operator-sdk/blob/v1.4.x/images/ansible-operator/Dockerfile#L20) in a new PR.

**Comment by estroz** [comment]
@reinvantveer this PR might've been merged prematurely. Builds for s390x, ppc64le, arm64 are [broken](https://travis-ci.com/github/operator-framework/operator-sdk/builds/217019403) due to gcc (and other deps) not being installed, but during some testing I also discovered that the Pipfile.lock's hashes don't resolve on s390x builds (at least) and I can't debug the issue. I'd like to revert this PR until we can test builds on all platforms using Github Actions for each PR since we're moving away from Travis soon. This is something I'm working on right now using `docker buildx`.

**Pull request merged**
