### PR TITLE
Add a hook to provide a custom rest config

### PR DESCRIPTION
**Pull request by nicolaferraro**
Why is this needed?
We are developing a Kubernetes runtime for Apache Camel based on operator-sdk in https://github.com/apache/camel-k (early stage).

We have the operator taking care of the resources inside the cluster, but we need also to develop a client tool (named `kamel`) that simplify the creation of such custom resources.

Users can create the custom resources directly, or with the client tool like: `kamel run <the-file>`.
The client tool needs to transform the file and create custom resources, reusing some logic from the operator code.

So, in order to reuse the operator code, we need to be able to initialize the kubernetes client differently in the `kamel` binary, but operator-sdk allows to initialize it only with specific environment variables, that are not suitable for our case (env var are not under our control, we want to use app flags).

With this change, I'm able to inject a config at boot (only for the `kamel` binary).

### CODE REVIEW

**Comment by nicolaferraro** [comment]
Ping!
We're working on a custom branch currently because we miss a feature like this.

**Comment by estroz** [comment]
@nicolaferraro is there a reason you cannot use `outOfClusterConfig` functionality, i.e. set `KUBERNETES_CONFIG`?

**Comment by estroz** [comment]
Tests fail because your branch is out of date with master. Please rebase/merge and push. Thanks!

**Comment by hasbro17** [comment]
@nicolaferraro What part of the SDK code are you using for your `kamel` client binary? Are you just using the SDK's generic client?

If so then since we're refactoring the SDK to use the controller-runtime anyway #382 I would suggest looking into using the controller-runtime's generic client since the SDK client will be replaced in favor of the controller-runtime's client after the refactor. 
Both of them are quite similar since the runtime client was designed based on the SDK's current client.

With the controller-runtime's client you should be able to instantiate a new client object based on your own kubeconfig and other options like your own scheme(so the client can recognize your custom types).
```Go
import (
    cgoscheme "k8s.io/client-go/kubernetes/scheme"
    "sigs.k8s.io/controller-runtime/pkg/client"
    camelv1alpha1 "<projectroot>/pkg/apis/camel/v1alpha1"
    "k8s.io/apimachinery/pkg/runtime"
)
...

kubeconfig := InitCustomKubeConfig()

scheme := runtime.NewScheme()
cgoscheme.AddToScheme(scheme)
// Add your custom type to the scheme
camelv1alpha.AddToScheme(scheme)

client, err := client.New(kubeconfig, dynclient.Options{Scheme: scheme})
if err != nil {
	return fmt.Errorf("failed to create the controller-runtime client: %v", err)
}
```
https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/client.go#L44
https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/client.go#L98-L140

We should have more docs on the controller-runtime client soon.
While we can include this fix temporarily you will eventually have to do the above since the SDK client will be removed in the future.

**Comment by nicolaferraro** [comment]
Thanks @estroz and @hasbro17. Having a Java background, I couldn't imagine there was a `os.setenv` function that could solve my issue...

Thank you for the update about the client upgrade. I think we'll move to the controller-runtime client as soon as you integrate it in the sdk.

Closing this.

**Pull request closed without merging**
