### PR TITLE
Add documentation for operator version

### PR DESCRIPTION
**Pull request by bvwells**
**Description of the change:**
Add documentation for generated operator version.

**Motivation for the change:**

Motivation is to add documentation on the operation version so users of the SDK know what this version is. Happy to change wording if needed.

### CODE REVIEW

**Comment by bvwells** [comment]
Thanks for the review @camilamacedo86. Will push an update to the doc comment later today.

**Comment by bvwells** [comment]
@camilamacedo86 - updated Version comment.

**Comment by bvwells** [comment]
Looks like travis build failed with a goveralls failure:

$ $GOPATH/bin/goveralls -service=travis-ci -coverprofile=coverage.out -repotoken=$COVERALLS_TOKEN
Bad response status from coveralls: 422
{"message":"service_job_id (684389024) must be unique for Travis Jobs not supplying a Coveralls Repo Token","error":true}

@estroz is it possible to re-run the build?

**Comment by camilamacedo86** [comment]
Hi @bvwells, 

Just rebase it with the master. It started to occurs when the project is outdated. It might be solved with an upgrade in the module used.  I will track this need an issue in the repo. Really tks.

**Comment by bvwells** [comment]
Thanks for the merge @camilamacedo86!

**Pull request merged**
