### PR TITLE
commands/.../cmdutil: deduplicate updateRoleForResource and support ClusterRole

### PR DESCRIPTION
**Pull request by AlexNPavel**
**Description of the change:** This moves updateRoleForResource to cmdutil so all of the command libraries can use it and also adds support for ClusterRoles in said function.

**Motivation for the change:** Deduplication of code and supporting users who want to use ClusterRole

### CODE REVIEW

**Comment by hasbro17** [comment]
@shawn-hurley For more context this is to support updating `deploy/role.yaml` if the type is ClusterRole.
We don't generate that to be a ClusterRole by default but a user may change that. 
Some operators using the SDK already do that.
https://github.com/operator-framework/operator-marketplace/blob/master/deploy/rbac.yaml#L1

And we still want the `add api` command to successfully update the rbac rule for that resource.

**Comment by hasbro17** [comment]
Seems good to me. Although I'm thinking we should move `commands/operator-sdk/cmd/cmdutil/util.go` to `commands/operator-sdk/cmd/internal/cmdutil/util.go`.
Since we don't want to expose these utils outside of the SDK.

**Comment by AlexNPavel** [comment]
@shawn-hurley Do you think this is good for now until we decide how to handle the util packages?

**Comment by hasbro17** [comment]
@shawn-hurley `updateRoleForResource()` could possibly go in `pkg/scaffold/util.go` or probably better `pkg/scaffold/rbac/rbac.go`. Or we can revisit this later if you think it doesn't fit there.

**Comment by AlexNPavel** [comment]
We will follow up on moving the cmdutil files in #649

**Pull request merged**
