### PR TITLE
updating logrus dependency to latest to resolve CVE

### PR DESCRIPTION
**Pull request by acornett21**
**Description of the change:**
Updating logrus to latest version.

**Motivation for the change:**
- Closes: #6502 

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Review by rashmigottipati — APPROVED** [review]
/lgtm

**Review by everettraven — COMMENTED** [review]
The logrus changes look good to me, but does this also address the go-restful vulnerability mentioned in the issue? I'd be hesitant to close out that issue if there is still an outstanding dependency that needs updating unless we can verify we aren't affected by the CVE.

**Comment by acornett21** [comment]
@everettraven You already addressed the `go-restful` issues in another PR, I linked that PR to the issue.

**Comment by everettraven** [comment]
>You already addressed the go-restful issues in another PR, I linked that PR to the issue.
@acornett21 Ah thanks - I totally forgot I did that :sweat_smile:

**Review by everettraven — APPROVED** [review]
/lgtm

**Pull request merged**
