### PR TITLE
(docs) Remove Red Hat links

### PR DESCRIPTION
**Pull request by anik120**
**Description of the change:**

This PR removes a RedHat specific script and the RedHat
Privacy statement link from the documentation site.

**Motivation for the change:**

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Review by rashmigottipati — APPROVED** [review]
/lgtm

**Comment by jmrodri** [comment]
@anik120 so what is our privacy policy now? Is there a replacement link we should link to?

**Comment by jmrodri** [comment]
/hold
waiting for questions to be answered

**Review by jmrodri — APPROVED** [review]
/lgtm

**Pull request merged**
