### PR TITLE
docs: fix custom scorecard test code sample

### PR DESCRIPTION
**Pull request by perdasilva**
**Description of the change:**

Updates the code sample in the custom scorecard test documentation replacing the `github.com/operator-framework/operator-registry/pkg/registry`  import for `apimanifests "github.com/operator-framework/api/pkg/manifests"` and  making the required fixes. Also changes the function signature to take a pointer to a bundle.

**Motivation for the change:**

Was going through the documentation and noticed that it wasn't working. Then checked against sample code from the repo, e.g. https://github.com/operator-framework/operator-sdk/blob/master/internal/scorecard/tests/basic.go#L19

### CODE REVIEW

**Review by theishshah — APPROVED** [review]
Good catch on the documentation update, thank you. /lgtm

**Review by camilamacedo86 — APPROVED** [review]
/lgtm

**Comment by perdasilva** [comment]
@camilamacedo86 if it helps, the changes in the docs match code that is currently found in the repo, e.g. https://github.com/operator-framework/operator-sdk/blob/master/internal/scorecard/tests/basic.go#L19

**Review by camilamacedo86 — APPROVED** [review]
/lgtm

**Pull request merged**
