### PR TITLE
Release v1.24.0

### PR DESCRIPTION
**Pull request by jberkhahn**
Hope this works

### CODE REVIEW

**Review by laxmikantbpandhare — CHANGES_REQUESTED** [review]
We updated OLM versions in docs in another PR but looks like we missed updating at a few places.

Please check Bryce's PR for the 1.22 release - https://github.com/operator-framework/operator-sdk/pull/5876/files

Missing places:
```
internal/bindata/olm/versions.go
internal/testutils/olm.go
```

**Review by laxmikantbpandhare — CHANGES_REQUESTED** [review]
Also, run `make test-sanity` locally, and if you found any changes in the files then push it. It will solve `test-sanity` failure.

**Comment by jmrodri** [comment]
> Also, run `make test-sanity` locally, and if you found any changes in the files then push it. It will solve `sanity` failures.

I have 2 patches to fix sanity. You have to run it with go 1.18 for this to work. If you run it with 1.19 you will get what's in this PR.

**Comment by jmrodri** [comment]
Okay it was only one patch. That is run with go 1.18.

[0001-Fix-test-sanity-formatting.txt](https://github.com/operator-framework/operator-sdk/files/9746529/0001-Fix-test-sanity-formatting.txt)

**Review by laxmikantbpandhare — APPROVED** [review]
/lgtm

**Pull request merged**
