### PR TITLE
doc: fix link to memcached cr

### PR DESCRIPTION
**Pull request by jmrodri**

### CODE REVIEW

**Comment by camilamacedo86** [comment]
Hi @joelanford,

It just happens because the name of the cr/crds gen were changed. Should not occur frequently anyway.  I did not get `While we're on the subject, should we move the go memcached-operator into a go subdirectory?`?

**Comment by joelanford** [comment]
In `operator-sdk-samples`, I was asking if we should move the go memcached-operator into a `go` subdirectory since there are `ansible` and `helm` subdirectories. It would make that repo more symmetric.

/cc @estroz @hasbro17

**Comment by estroz** [comment]
I'm in agreement.

**Comment by camilamacedo86** [comment]
Hi @estroz and @joelanford, 

I added in my backlog list to do it. However, I think will be easier to merge the upgrade first https://github.com/operator-framework/operator-sdk-samples/pull/90 . wdyt?

**Pull request merged**
