### PR TITLE
Remove unused Go operator scaffold code

### PR DESCRIPTION
**Pull request by hasbro17**
**Description of the change:**
Remove unused scaffolding code for Go operators.

**Motivation for the change:**
Follow up from https://github.com/operator-framework/operator-sdk/pull/3190#pullrequestreview-426306689

### CODE REVIEW

**Comment by hasbro17** [comment]
Ah whoops, removed too much.
Going to add back the bits that we actually still need.

**Comment by camilamacedo86** [comment]
yes, we still need the scaffold used in the add command. otherwise, it shows good.

**Comment by hasbro17** [comment]
Turns out pretty much everything in `internal/scaffold` is still being used by one cmd or the other in the legacy CLI.
So not a whole lot here until that gets removed.

**Comment by hasbro17** [comment]
@estroz I'm not opposed but I imagine scaffolding a `version/version.go` for operator projects is one of those things that Kubebuilder probably won't want to be opinionated about since it doesn't have much to do with the workflow of writing controllers/operators.

Plus other projects in the wild each have their own preference of where to place the version information.
https://github.com/jetstack/cert-manager/blob/master/cmd/ctl/pkg/version/version.go
https://github.com/coreos/prometheus-operator/blob/master/VERSION
https://github.com/oracle/mysql-operator/blob/master/pkg/version/version.go
https://github.com/zalando/postgres-operator/blob/master/kubectl-pg/cmd/version.go
https://github.com/rook/rook/blob/master/pkg/version/version.go#L19
https://github.com/vmware-tanzu/velero/blob/master/pkg/buildinfo/version.go#L26

So I imagine that might be out of scope for Kubebuilder.

**Pull request merged**
