### PR TITLE
Bug 2037208: handle arm64

### PR DESCRIPTION
**Pull request by jmrodri**
* update Makefiles
* regenerate samples using the new update

Signed-off-by: jesus m. rodriguez <jesusr@redhat.com>

**Description of the change:**

**Motivation for the change:**

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [x] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Comment by jmrodri** [comment]
/hold

needs changelog

**Review by ryantking — COMMENTED** [review]
LGTM, tested with darwin's default sed, which is different from GNU's.

**Review by asmacdo — APPROVED** [review]
/lgtm

**Comment by jmrodri** [comment]
/hold
there is one scenario that I think is broken. Will verify and remove hold.

**Comment by jmrodri** [comment]
The scenario is that we try to download opm and there was no arm64 opm until release 1.20.

**Comment by jmrodri** [comment]
I will retest this PR and reopen.

**Pull request merged**
