### PR TITLE
Typo fix for definitons to definitions

### PR DESCRIPTION
**Pull request by dunefro**
**Description of the change:**

**Motivation for the change:**

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Review by jmrodri — APPROVED** [review]
/lgtm

**Comment by jmrodri** [comment]
@dunefro 

You only have one commit incorrectly signed off! To fix, first ensure you have a local copy of your branch by checking out the pull request locally via command line. Next, head to your local branch and run:

`git commit --amend --no-edit --signoff`

Now your commits will have your sign off. Next run

`git push --force-with-lease origin patch-1`

**Comment by dunefro** [comment]
@jmrodri Signed-off

**Review by camilamacedo86 — APPROVED** [review]
/lgtm

**Pull request merged**
