### PR TITLE
deps: fix upstream JSON patch issues

### PR DESCRIPTION
**Pull request by meyskens**
**Description of the change:**

Bumps the Helm version as well as the underlying Kubernetes version.

**Motivation for the change:**
Adding a fix for https://github.com/helm/helm/issues/8594 which is a fix for https://github.com/kubernetes/kubernetes/issues/91615 which causes complex CRD updates to hang,

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Comment by estroz** [comment]
@meyskens can you run `make tidy` then push? Thanks.

**Comment by meyskens** [comment]
@estroz done!

**Review by joelanford — APPROVED** [review]
Thanks @meyskens 

/lgtm

Once this passes/merges, I think we should backport it to v1.0.x and v0.19.x

**Review by estroz — APPROVED** [review]
Helm 3.2.x and 3.3.x both support the same [k8s version range](https://helm.sh/docs/topics/version_skew/), and there are no breaking changes afaict.

/lgtm

**Pull request merged**
