### PR TITLE
Remove metering from deep insights capability

### PR DESCRIPTION
**Pull request by sradco**
Signed-off-by: Shirly Radco <sradco@redhat.com>

**Description of the change:**
Since metering is a deprecated feature, removed it from the Deep Insights capability level requirements.
Links to deprecation notice: 
 - https://github.com/kube-reporting/metering-operator
 - https://docs.openshift.com/container-platform/4.8/metering/metering-about-metering.html

**Motivation for the change:**
Incorrect requirements for Deep Insights capability level creates confusion.

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Comment by sradco** [comment]
@camilamacedo86 please review

**Comment by sradco** [comment]
@dmesser Please review this PR

**Review by camilamacedo86 — APPROVED** [review]
/lgtm

**Pull request merged**
