### PR TITLE
crd: set the scope based on the operator role

### PR DESCRIPTION
**Pull request by xcoulon**
**Description of the change:**

add a function that parses the `deploy/role.yaml`
manifest to find which kind of role is associated
with the operator. If it is a `ClusterRole`, then
the function returns a `Cluster` value for the scope
of the CRD to create. Otherwise, it's a `Namespaced`
scope.

**Motivation for the change:**
The goal of this change is to have the CRD scope correctly set to `Namespaced` or `Cluster`. Since there is no "dot config file" where we can determine the type of the operator (ie, if the `--cluster-scoped` flag was used when bootstrapping the project), this PR attempts to read the `deploy/role.yaml` file to determine which scope to set. 
See also https://github.com/operator-framework/operator-sdk/issues/890#issuecomment-469263803

Updates #890

### CODE REVIEW

**Comment by xcoulon** [comment]
> @xcoulon: PR needs rebase.
> 
> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md). If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.

done.

**Comment by xcoulon** [comment]
oops... let me fix the test failures 😬

**Comment by LiliC** [comment]
Thanks for your PR, I think in the https://github.com/operator-framework/operator-sdk/issues/890#issuecomment-452809400 @joelanford suggested to add the `--cluster-scoped` flag to the `add` command, instead of extracting the scope from already existing files. Pinging him to have a look at this implementation.

**Comment by xcoulon** [comment]
> Thanks for your PR, I think in the [#890 (comment)](https://github.com/operator-framework/operator-sdk/issues/890#issuecomment-452809400) @joelanford suggested to add the `--cluster-scoped` flag to the `add` command, instead of extracting the scope from already existing files. Pinging him to have a look at this implementation.

ah right @LiliC, I missed that @joelanford's comment details and headed down into a solution that may have been wrong in the end. Yet, I would be happy to refactor/redo my work to match with the expected solution ;)

**Comment by xcoulon** [comment]
@LiliC @joelanford I will try to implement options 1 and 2 as described in https://github.com/operator-framework/operator-sdk/issues/890#issuecomment-452809400. Please if that's ok for you.

**Comment by xcoulon** [comment]
closing in favor of https://github.com/operator-framework/operator-sdk/pull/1172

**Pull request closed without merging**
