### PR TITLE
Change image pull policy to pull always

### PR DESCRIPTION
**Pull request by theishshah**
**Description of the change:**

Changes Image Pull Policy on the testpod in scorecard. 

**Motivation for the change:**

#4423

### CODE REVIEW

**Review by camilamacedo86 — COMMENTED** [review]
Hi @theishshah, 

It is missing the changelog with the change.
Otherwise, it seems ok.

**Comment by theishshah** [comment]
>  See that we cannot download always the images there because we gen them with the code to allow test it in the PR. So, you need to change it for the test.


So the issue we are hitting here is that even with an increased time limit we cannot pull the image, and it's not configurable on a per run basis - either we have to commit to not always pulling, or being able to pull images from quay and dockerhub during CI. The way this is currently configured in testpod.go I believe it would take some large changes within scorecard to make the imagepullpolicy easily editable at scorecard runtime (without manually changing the testpod definition beforehand).

**Comment by jmrodri** [comment]
I thought this was going to be fixed by PR #5191

**Comment by jmrodri** [comment]
/hold
I'm not sold on this being a good idea. I'd like to chat more about this.

**Comment by jmrodri** [comment]
Debugging e2e tests locally I noticed that it is failing to pull the `scorecard-test:dev` image.
```
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                 From               Message
  ----     ------     ----                ----               -------
  Normal   Scheduled  2m7s                default-scheduler  Successfully assigned default/scorecard-test-pxqt to kind-control-plane
  Normal   Pulled     2m5s                kubelet            Container image "registry.access.redhat.com/ubi8/ubi:8.4" already present on machine
  Normal   Created    2m5s                kubelet            Created container scorecard-untar
  Normal   Started    2m4s                kubelet            Started container scorecard-untar
  Normal   Pulling    42s (x4 over 2m4s)  kubelet            Pulling image "quay.io/operator-framework/scorecard-test:dev"
  Warning  Failed     42s (x4 over 2m3s)  kubelet            Failed to pull image "quay.io/operator-framework/scorecard-test:dev": rpc error: code = NotFound desc = failed to pull and unpack image "quay.io/operator-framework/scorecard-test:dev": failed to resolve reference "quay.io/operator-framework/scorecard-test:dev": quay.io/operator-framework/scorecard-test:dev: not found
  Warning  Failed     42s (x4 over 2m3s)  kubelet            Error: ErrImagePull
  Normal   BackOff    28s (x5 over 2m3s)  kubelet            Back-off pulling image "quay.io/operator-framework/scorecard-test:dev"
  Warning  Failed     28s (x5 over 2m3s)  kubelet            Error: ImagePullBackOff
```

We are building it and loading it in `kind`:
```
docker buildx build  -t quay.io/operator-framework/scorecard-test:dev -f ./images/scorecard-test/Dockerfile --load .

...

running: kind load docker-image quay.io/example/e2e-msit:v0.0.1 --name operator-sdk-e2e                                                                                                                                                       
running: kind load docker-image --name operator-sdk-e2e quay.io/operator-framework/scorecard-test:dev                                                                                                                                         
running: kind load docker-image --name operator-sdk-e2e quay.io/operator-framework/custom-scorecard-tests:dev 
```

But I think because we're setting the pull policy to *Always* we will ALWAYS pull from quay. But that image does not exist on quay:

```
docker pull quay.io/operator-framework/scorecard-test:dev
Error response from daemon: unknown: Tag dev was deleted or has expired. To pull, revive via time machine
```

**Comment by rashmigottipati** [comment]
I guess we could add https://github.com/operator-framework/operator-sdk/issues/4423 to triage discussion on Monday. Looks like from the previous discussions, the consensus was to switch the default to "Always".

**Comment by jmrodri** [comment]
I'm closing this PR based on my comment https://github.com/operator-framework/operator-sdk/pull/5054#issuecomment-926877564

**Pull request closed without merging**
