### PR TITLE
Vscode plugin

### PR DESCRIPTION
**Pull request by germanodasilva**
**Description of the change:**
The purpose of this plugin is to create a component that makes it easy for the developer to build operators using the VS Code IDE, this helps to spread the use and adoption of the technology by the Enterprise community and organizations.

**Motivation for the change:**
The desire to contribute to the community

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Comment by jmrodri** [comment]
@germanodasilva Hello thank you for your submission. Is there supposed to be a plugin in this PR? Is this intended to be a plugin to VS Code? or an SDK plugin that generates something for use with VS Code?

**Comment by jmrodri** [comment]
@germanodasilva also I think an issue would be a better venue for initiating discussion.

**Comment by germanodasilva** [comment]
Hello Jesus and team, thanks for the discussion window.
My goal is to be able to bring this theme so that it can be delivered as a
facilitator to the use of operator-sdk by developers. The objective is to
develop a plugin that can be added like any other within vscode and this
plugin can help in the development with sample codes for the pattern to be
supported by the operator-sdk, this I have already worked on, as well as
the implementation of the apis of marketplace for use in openshift with
quarkus. I'm a hatter and this need to contribute led to adoption by some
clients in Brazil.

**Comment by jmrodri** [comment]
Closing this PR as there has been no movement in a long time.

**Pull request closed without merging**
