### PR TITLE
Makes run command version details in sync with the version command

### LINKED ISSUE #5006: Wrong version in ansible-operator with "run" command
hi,

i've installed the 1.9.0 version of `ansible-operator` as you can see with the `version` command it shows `v1.9.0`:
~~~
# ansible-operator version
ansible-operator version: "v1.9.0", commit: "205e0a0c2df0715d133fbe2741db382c9c75a341", kubernetes version: "1.20.2", go version: "go1.16.5", GOOS: "linux", GOARCH: "amd64"
~~~

But when i use the `run` command, i get this output:
~~~
# ansible-operator run
{"level":"info","ts":1624431850.9744582,"logger":"cmd","msg":"Version","Go Version":"go1.16.5","GOOS":"linux","GOARCH":"amd64","ansible-operator":"v1.8.0+git","commit":"205e0a0c2df0715d133fbe2741db382c9c75a341"}
~~~

but here the operator version is `v1.8.0+git`. this is confusing and one might ghink there are different versions of the operator installed.

### PR DESCRIPTION
**Pull request by sujil02**
Makes run command version details in sync with the version command
Fixes #5006 

Signed-off-by: sujil02 <sujil.shah@gmail.com>

**Description of the change:**

**Motivation for the change:**

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Comment by jmrodri** [comment]
@sujil02 please post the output with this PR applied as a comment.

**Comment by jmrodri** [comment]
`operator-sdk version` seems to use `GitVersion`. https://github.com/operator-framework/operator-sdk/blob/master/internal/cmd/operator-sdk/cli/version.go#L25-L26 though there seems to have been something that caused this during the release.

**Comment by sujil02** [comment]
```
Output Post PR:

$ ansible-operator version
ansible-operator version: "v1.9.0-1-g3643a72b", commit: "3643a72b5025b30a137ee2cf22a2599c4bc7d20b", kubernetes version: "v1.20.2", go version: "go1.16.4", GOOS: "darwin", GOARCH: "amd64"
$ ansible-operator run
{"level":"info","ts":1625070521.7572968,"logger":"cmd","msg":"Version","Go Version":"go1.16.4","GOOS":"darwin","GOARCH":"amd64","ansible-operator":"v1.9.0-1-g3643a72b","commit":"3643a72b5025b30a137ee2cf22a2599c4bc7d20b"}
$ operator-sdk version
operator-sdk version: "v1.9.0-1-g3643a72b", commit: "3643a72b5025b30a137ee2cf22a2599c4bc7d20b", kubernetes version: "v1.20.2", go version: "go1.16.4", GOOS: "darwin", GOARCH: "amd64"
```

**Comment by sujil02** [comment]
@jmrodri 

Output release v1.8.0
```
#ansible-operator version
ansible-operator version: "v1.8.0", commit: "d3bd87c6900f70b7df618340e1d63329c7cd651e", kubernetes version: "1.20.2", go version: "go1.16.4", GOOS: "linux", GOARCH: "amd64"
#ansible-operator run
{"level":"info","ts":1623719128.772884,"logger":"cmd","msg":"Version","Go Version":"go1.16.4","GOOS":"linux","GOARCH":"amd64","ansible-operator":"v1.7.1+git","commit":"d3bd87c6900f70b7df618340e1d63329c7cd651e"}

```
Output release v1.7.2
```
#ansible-operator version
ansible-operator version: "v1.7.2", commit: "6db9787d4e9ff63f344e23bfa387133112bda56b", kubernetes version: "1.19.4", go version: "go1.15.5", GOOS: "linux", GOARCH: "amd64"

# ansible-operator run
{"level":"info","ts":1623730652.3575754,"logger":"cmd","msg":"Version","Go Version":"go1.15.5","GOOS":"linux","GOARCH":"amd64","ansible-operator":"v1.7.1+git","commit":"6db9787d4e9ff63f344e23bfa387133112bda56b"}

**Comment by jmrodri** [comment]
@sujil02 Okay, that looks like it's always been broken.

**Review by jmrodri — APPROVED** [review]
/lgtm

**Comment by estroz** [comment]
What about helm-operator?

**Comment by sujil02** [comment]
@estroz  Verified that looks in sync

```
$ helm-operator version
helm-operator version: "v1.9.0", commit: "205e0a0c2df0715d133fbe2741db382c9c75a341", kubernetes version: "v1.20.2", go version: "go1.16.5", GOOS: "darwin", GOARCH: "amd64"
$ helm-operator run
{"level":"info","ts":1626904201.4236002,"logger":"cmd","msg":"Version","Go Version":"go1.16.5","GOOS":"darwin","GOARCH":"amd64","helm-operator":"v1.9.0","commit":"205e0a0c2df0715d133fbe2741db382c9c75a341"}
```

**Comment by estroz** [comment]
`ansible-operator` and `helm-operator` have the exact same [`printVersion()`](https://github.com/sujil02/operator-sdk/blob/v1.9.0-branch/internal/cmd/helm-operator/run/cmd.go#L49-L56) implementations, so why wouldn't the latter suffer from the same issue at some point in the future?

**Comment by sujil02** [comment]
Hi @estroz ,

The previously posted output was from the new build after the patch and can be ignored I tested it 1.8.0 helm-operator and the issue persist with the same as well 
```
$ helm-operator_linux_amd64 version
helm-operator version: "v1.8.0", commit: "d3bd87c6900f70b7df618340e1d63329c7cd651e", kubernetes version: "1.20.2", go version: "go1.16.4", GOOS: "linux", GOARCH: "amd64"
$ helm-operator_linux_amd64 run
{"level":"info","ts":1626935123.1183627,"logger":"cmd","msg":"Version","Go Version":"go1.16.4","GOOS":"linux","GOARCH":"amd64","helm-operator":"v1.7.1+git","commit":"d3bd87c6900f70b7df618340e1d63329c7cd651e"}

```

**Review by estroz — APPROVED** [review]
/lgtm

**Pull request merged**
