### PR TITLE
Update OLM version to 0.24.0

### PR DESCRIPTION
**Pull request by oceanc80**
**Description of the change:**
Updates OLM version in places missed by `make bindata` target.

**Motivation for the change:**

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Review by varshaprasad96 — CHANGES_REQUESTED** [review]
@oceanc80 We need to update the [docs](https://github.com/operator-framework/operator-sdk/blob/master/website/content/en/docs/overview/_index.md#olm-version-compatibility) and the [e2e](https://github.com/operator-framework/operator-sdk/blob/484013d1865c35df2bc5dfea0ab6ea6b434adefa/internal/testutils/olm.go#L29) test to use the updated OLM version.

**Comment by oceanc80** [comment]
The docs and e2e test were updated in these PRs:  https://github.com/operator-framework/operator-sdk/pull/6360 and https://github.com/operator-framework/operator-sdk/pull/6359
I forgot that the `make bindata` command misses some files so I didn't manually fix them the first go round and needed this follow-up PR.

**Review by rashmigottipati — APPROVED** [review]
/lgtm

**Review by varshaprasad96 — APPROVED** [review]
/lgtm

**Pull request merged**
