### PR TITLE
fix(code gen) : Fix group obtained to gen and open api (ISSUE 1812)

### PR DESCRIPTION
**Pull request by camilamacedo86**
**Description of the change:**
- Make all commands use the group var in order to allow the tool to generated compatible files. 

**Motivation for the change:**

- https://github.com/operator-framework/operator-sdk/issues/1812
- https://github.com/operator-framework/operator-sdk/issues/1368

**Following the test performed locally**

- Create the project

```
$ operator-sdk new test-group
INFO[0000] Creating new Go operator 'test-group'.       
INFO[0000] Created go.mod                               
INFO[0000] Created tools.go                             
INFO[0000] Created cmd/manager/main.go                  
INFO[0000] Created build/Dockerfile                     
INFO[0000] Created build/bin/entrypoint                 
INFO[0000] Created build/bin/user_setup                 
INFO[0000] Created deploy/service_account.yaml          
INFO[0000] Created deploy/role.yaml                     
INFO[0000] Created deploy/role_binding.yaml             
INFO[0000] Created deploy/operator.yaml                 
INFO[0000] Created pkg/apis/apis.go                     
INFO[0000] Created pkg/controller/controller.go         
INFO[0000] Created version/version.go                   
INFO[0000] Created .gitignore                           
INFO[0000] Validating project                           
go: finding github.com/operator-framework/operator-sdk master
INFO[0005] Project validation successful.               
INFO[0005] Project creation complete.          
```         
- Create the API ( CR/CRD ) 

```
$ cd test-group/
$ operator-sdk add api --api-version=test-group.test-com.com/v1alpha1 --kind=App
INFO[0000] Generating api version test-group.test-com.com/v1alpha1 for kind App. 
INFO[0000] Created pkg/apis/test-group/group.go         
INFO[0004] Created pkg/apis/test-group/v1alpha1/app_types.go 
INFO[0004] Created pkg/apis/addtoscheme_test-group_v1alpha1.go 
INFO[0004] Created pkg/apis/test-group/v1alpha1/register.go 
INFO[0004] Created pkg/apis/test-group/v1alpha1/doc.go  
INFO[0004] Created deploy/crds/test-group_v1alpha1_app_cr.yaml 
INFO[0010] Created deploy/crds/test-group_v1alpha1_app_crd.yaml 
INFO[0010] Running deepcopy code-generation for Custom Resource group versions: [test-group:[v1alpha1], ] 
INFO[0017] Code-generation complete.                    
INFO[0017] Running OpenAPI code-generation for Custom Resource group versions: [test-group:[v1alpha1], ] 
INFO[0030] Created deploy/crds/test-group_v1alpha1_app_crd.yaml 
INFO[0030] Code-generation complete.                    
INFO[0030] API generation complete.  
```    

-- Creating controller

```
$ operator-sdk add controller --api-version=test-group.test-com.com/v1alpha1 --kind=App
INFO[0000] Generating controller version test-group.test-com.com/v1alpha1 for kind App. 
INFO[0000] Created pkg/controller/app/app_controller.go 
INFO[0000] Created pkg/controller/add_app.go            
INFO[0000] Controller generation complete.     
```         

- Check generate openapi

```
camilamacedo@Camilas-MacBook-Pro ~/go/src/test/test-group $ operator-sdk generate openapi
INFO[0000] Running OpenAPI code-generation for Custom Resource group versions: [test-group:[v1alpha1], ] 
INFO[0013] Created deploy/crds/test-group_v1alpha1_app_crd.yaml 
INFO[0013] Code-generation complete.    
```                

- Check generate k8s

```
camilamacedo@Camilas-MacBook-Pro ~/go/src/test/test-group $ operator-sdk generate k8s
INFO[0000] Running deepcopy code-generation for Custom Resource group versions: [test-group:[v1alpha1], ] 
INFO[0008] Code-generation complete.     
```      

- Applying the CRD
         
```
$ kubectl apply -f deploy/crds/test-group_v1alpha1_app_crd.yaml 
customresourcedefinition.apiextensions.k8s.io/apps.test-group.test-com.com created
```

- Applying the CR

```
$ kubectl apply -f deploy/crds/test-group_v1alpha1_app_cr.yaml 
app.test-group.test-com.com/example-app created
camilamacedo@Camilas-MacBook-Pro ~/go/src/test/test-group $ 
```

- Checking commands with specs and status

Screenshot 2019-08-14 at 16 00 39

 ```
$ operator-sdk generate k8s
INFO[0000] Running deepcopy code-generation for Custom Resource group versions: [test-group:[v1alpha1], ] 
INFO[0009] Code-generation complete.                    
 $  operator-sdk generate openapi
INFO[0000] Running OpenAPI code-generation for Custom Resource group versions: [test-group:[v1alpha1], ] 
INFO[0016] Created deploy/crds/test-group_v1alpha1_app_crd.yaml 
INFO[0016] Code-generation complete.        
```        

OpenAPI worked with success:

Screenshot 2019-08-14 at 16 01 56

### CODE REVIEW

**Comment by camilamacedo86** [comment]
Hi folks

Please, could you give a hand and check if you are able to reproduce any one of these both issues with this PR? 

c/c @estroz, @joelanford

**Comment by estroz** [comment]
@camilamacedo86 a few more changes are needed:

```diff
diff --git a/internal/pkg/scaffold/addtoscheme.go b/internal/pkg/scaffold/addtoscheme.go
index 5dbddf34..3ff5c937 100644
--- a/internal/pkg/scaffold/addtoscheme.go
+++ b/internal/pkg/scaffold/addtoscheme.go
@@ -44,7 +44,7 @@ func (s *AddToScheme) GetInput() (input.Input, error) {
 const addToSchemeTemplate = `package apis
 
 import (
-       "{{ .Repo }}/pkg/apis/{{ .Resource.GoImportGroup}}/{{ .Resource.Version }}"
+       "{{ .Repo }}/pkg/apis/{{ .Resource.Group | lower }}/{{ .Resource.Version }}"
 )
 
 func init() {
diff --git a/internal/pkg/scaffold/controller_kind.go b/internal/pkg/scaffold/controller_kind.go
index 0f8f4160..9e5fdd04 100644
--- a/internal/pkg/scaffold/controller_kind.go
+++ b/internal/pkg/scaffold/controller_kind.go
@@ -69,7 +69,8 @@ func (s *ControllerKind) setImports() (err error) {
                        return err
                }
        } else {
-               importPath = path.Join(s.Repo, "pkg", "apis", s.Resource.GoImportGroup, s.Resource.Version)
+               importPath = path.Join(s.Repo, "pkg", "apis",
+                       strings.ToLower(s.Resource.Group), s.Resource.Version)
                s.GoImportIdent = s.Resource.GoImportGroup + s.Resource.Version
        }
        // Import identifiers must be unique within a file.
diff --git a/internal/pkg/scaffold/group.go b/internal/pkg/scaffold/group.go
index 563c3092..ef0df1b9 100644
--- a/internal/pkg/scaffold/group.go
+++ b/internal/pkg/scaffold/group.go
@@ -15,8 +15,10 @@
 package scaffold
 
 import (
-       "github.com/operator-framework/operator-sdk/internal/pkg/scaffold/input"
        "path/filepath"
+       "strings"
+
+       "github.com/operator-framework/operator-sdk/internal/pkg/scaffold/input"
 )
 
 const GroupFile = "group.go"
@@ -31,13 +33,13 @@ var _ input.File = &Group{}
 
 func (s *Group) GetInput() (input.Input, error) {
        if s.Path == "" {
-               s.Path = filepath.Join(ApisDir, s.Resource.Group, GroupFile)
+               s.Path = filepath.Join(ApisDir, strings.ToLower(s.Resource.Group), GroupFile)
        }
        s.TemplateBody = groupTmpl
        return s.Input, nil
 }
 
-const groupTmpl = `// Package {{.Resource.GoImportGroup}} contains {{.Resource.GoImportGroup}} API versions.
+const groupTmpl = `// Package {{.Resource.GoImportGroup}} contains {{.Resource.Group | lower}} API versions.
 //
 // This file ensures Go source parsers acknowledge the {{.Resource.GoImportGroup}} package
 // and any child packages. It can be removed if any other Go source files are
```

Also this is a breaking change for all users that have a hyphenated group. We need to discuss whether we want this change, over modifying CRD group/name after generation.

IMO we should make this change since it is the correct way to respect group names. We only need to use the import group in package identifiers.

This basically reverts #998 and #1374 

/cc @joelanford @hasbro17 @jmrodri @fabianvf

**Comment by camilamacedo86** [comment]
Hi @estroz,

Really thank you for the reply and so helpful info provided so far. 

I believe that I could address the points. However, note that we cannot do a 100% revert. The `GoImportGroup` introduced still required since we have now the `group.go` template. Note that it is required for we are able to create the name of the package since go will not accept a package as `name-name`. Following an image to illustrate. (Also, check that the changes raised was addressed in the template as well, but the pkg needs to still be as `package {{.Resource.GoImportGroup}}`)  

Screenshot 2019-08-15 at 10 26 59

Please, let me know if it makes sense and if you are ok with the changes here. 

/cc @joelanford @hasbro17 @jmrodri @fabianvf

**Comment by joelanford** [comment]
So my understanding is that we need hyphens in the directory name to satisfy controller-tool's CRD generation, but we can't use hyphens in package names because the Go spec disallows it. Is that what it boils down to?

I just checked to see how kubebuilder handles this as a point of comparison, and they just disallow groups with hyphens in the name to avoid the directory/package mismatch. That would be a bigger breaking change, but would probably lead to less confusion. If CRD generation is broken for hyphenated group names anyway, maybe that new restriction would be reasonable?

Technically, Kubernetes allows groups with hyphens though, so it's a little odd that we would not support that.

Would it be possible to use `GoImportGroup` for both directory and package name and update controller-tools to get the group name via some other mechanism? It looks like there's a `+groupName` comment annotation that both SDK and Kubebuilder scaffold into API go files that could be useful.

**Comment by camilamacedo86** [comment]
HI @joelanford, 

All places are using the  `Group` var ( which means with `-`). Just the pkg name of the new template `group.go` which was introduced in the latest version that cannot be created with `-` since it is not allowed in the Go language. Note that the old projects are facing issues related to the code gen features since it was supported before and that olm commands never stop to support that and generate the files/paths with `-` so far creating an inconsistence in the projects. 

In this way, following my IMHO:

I think that we should come back this supportability with this PR and fixes the current issues and keep the files gen consistents. Then, in the future, if we'd like to create any limitation it should be done by a validation feature which will not allow the tool continue and will inform the user what is not supportable before doing any action. In POV is NOT a good approach to change the group name without the consent of the user at all.

**Comment by camilamacedo86** [comment]
HI @joelanford,

I opened the issue https://github.com/kubernetes-sigs/kubebuilder/issues/954 for kubebuilder allow `-` in the group names. It is a small change in the regex only. Next week I will try working on in a PR for it + add here the same regex validation for we do not allow other characters and keep both compatible. WDYT?  

c/c @estroz @hasbro17 @jmrodri @fabianvf @estroz

**Comment by joelanford** [comment]
@camilamacedo86 I think we should try to align our Go scaffolding and implementation as much as possible with Kubebuilder, so I agree with pursuing this change upstream.

Also, @estroz does `controller-tools` v0.2.0 help us in any way with this? Maybe a better way of figuring out the group name than directory traversal?

/ok-to-test

/hold
Since the controller-tools v0.2.0 update should be imminent and it looks like this could conflict.

**Comment by camilamacedo86** [comment]
HI @joelanford,

The PR for the kubebuilder is done:  https://github.com/kubernetes-sigs/kubebuilder/pull/977
Also, the same validation/regex used to check the name done there was add here.

It is important to highlight that this PR will just affect(break change) the projects which have `-` in the group name which is NOT working well as expected with operator-sdk >= 8. I mean that it would NOT impact any project which currently is working well and it should just allow solving this issue for that ones which are facing problems. Also, after this PR we will ensure that the group names should match with ` "^[a-z -]+$"`. 

So, I think we could move forward here. WDYT? 

c/c @estroz

**Comment by camilamacedo86** [comment]
HI @joelanford,

The PR for kubebuilder, kubernetes-sigs/kubebuilder#977,  was accepted and merged.

c/c @estroz

**Comment by camilamacedo86** [comment]
Since it is outdated and has a conflict. Let's broken/split it in 2 new PRs as follows. 
- https://github.com/operator-framework/operator-sdk/pull/1951 (for the validation)
-

**Pull request closed without merging**
