### PR TITLE
Fix typo from the Go operation building tutorial

### PR DESCRIPTION
**Pull request by bLuka**
**Description of the change:**
Fix a typo

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- ~~Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))~~
- ~~Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)~~

### CODE REVIEW

**Comment by bLuka** [comment]
Hello, found this little typo on [the online documentation](https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/#controller-configurations).

Hope this helps!

**Review by rashmigottipati — APPROVED** [review]
DCO needs to be added to the commit message. 

Otherwise /lgtm

**Comment by rashmigottipati** [comment]
You can sign-off by doing `git commit --amend --no-edit --signoff`

**Review by varshaprasad96 — APPROVED** [review]
/lgtm

**Comment by varshaprasad96** [comment]
@bLuka looking forward to get this PR merged :). Can you please sign the commit?

**Review by camilamacedo86 — APPROVED** [review]
/lgtm

**Pull request merged**
