### PR TITLE
chore: fix function names

### PR DESCRIPTION
**Pull request by depthlending**
**Description of the change:**

**Motivation for the change:**

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Review by grokspawn — APPROVED** [review]

**Comment by grokspawn** [comment]
Looks like you need to update [testdata](https://github.com/operator-framework/operator-sdk/actions/runs/8388597206/job/23711738256?pr=6709#step:5:153) as well.

**Comment by depthlending** [comment]
friendly ping~

**Comment by acornett21** [comment]
@depthlending Can you rebase, so we can make sure all tests pass? Thanks.

**Pull request closed without merging**
