### PR TITLE
Use controllerutil.ContainsFinalizer in delete example

### PR DESCRIPTION
**Pull request by rearl-scwx**
Replacing the custom `contains` implementation with
the version in controllerutil.

**Description of the change:**

**Motivation for the change:**

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [x] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Comment by jmrodri** [comment]
@rearl-scwx did you forget to commit the changes? I don't see any changes in this PR.

**Comment by jmrodri** [comment]
@rearl-scwx also can you signoff your commits so the DCO check will be green? You can do that by `git commit --signoff` when you commit your files or if you already committed them you can do `git rebase HEAD~n --signoff` where `n` is the number of commits you already committed.

**Comment by rearl-scwx** [comment]
@jmrodri I have a feeling I've made a mess of this and will need to start again.

**Pull request closed without merging**
