### PR TITLE
docs: fix Ansible metrics reference

### PR DESCRIPTION
**Pull request by vkrizan**
**Description of the change:**

Adds appropriate metadata to Ansible's metrics doc to have it linked on
the website.

https://sdk.operatorframework.io/docs/building-operators/ansible/reference/internal_metrics/

**Motivation for the change:**

Linking on navbar.

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
  - not required
- [X] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Comment by vkrizan** [comment]
The CI errors do not seem to be relevant to this change:
```
   *  External link https://gohugo.io/templates/404/ failed: got a time out (response code 0)
  *  External link https://v1-14-x.sdk.operatorframework.io failed: got a time out (response code 0)
- /target/docs/building-operators/ansible/reference/webhooks/index.html
  *  External link https://v1-21.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#mutatingwebhookconfiguration-v1-admissionregistration-k8s-io failed: got a time out (response code 0)
  *  External link https://v1-21.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#validatingwebhookconfiguration-v1-admissionregistration-k8s-io failed: got a time out (response code 0)
- /target/docs/contribution-guidelines/documentation/index.html
  *  External link https://gohugo.io/ failed: got a time out (response code 0)
```

**Review by everettraven — APPROVED** [review]
Hi @vkrizan ! Thanks for the contribution!

We definitely want to make sure that these docs are visible so thank you for updating it!

/lgtm

**Comment by everettraven** [comment]
I'm going to close and reopen this PR to rerun the checks.

**Review by asmacdo — APPROVED** [review]
/lgtm

**Pull request merged**
