### PR TITLE
jberkhahn for operator-sdk approver

### PR DESCRIPTION
**Pull request by jberkhahn**
Per the discussion at the meeting today, here's my application for approver. I'm apparently already a maintainer on the CNCF side of things so I think(?) this is the only thing to do, as the lists in operator-framework/community don't seem like they need to change.

Also I sorted the lists because I couldn't stand them not being in alphabetical order, sorry.

@asmacdo

### CODE REVIEW

**Comment by jmrodri** [comment]
@jberkhahn looks like this PR failed DCO so please sign the commit.

**Comment by jberkhahn** [comment]
lol woops, fixed

**Review by jmrodri — APPROVED** [review]
/lgtm

**Pull request merged**
