### PR TITLE
Fix: Spelling mistake in packagemanifests deprecation message

### PR DESCRIPTION
**Pull request by jjkiely**
**Description of the change:**
A spelling mistake "packagemanifes" has been fixed in two places

**Motivation for the change:**
The spelling was incorrect

### CODE REVIEW

**Review by camilamacedo86 — APPROVED** [review]
You need to assign your commit `git commit --amend --no-edit --signoff`. Otherwise, that shows fine. Could you please do taht?

**Comment by jjkiely** [comment]
@camilamacedo86 That should be done now, thanks!

**Review by rashmigottipati — APPROVED** [review]
/lgtm

**Review by jmrodri — APPROVED** [review]
/lgtm

**Comment by camilamacedo86** [comment]
Hi @jjkiely, 

It gets lost and seems that is failing because is missing a rebase. Could you please rebase it with the master for we get it merged? Also, please feel free to ping me in the slack to merge when it be passing in all tests.

**Pull request merged**
