### PR TITLE
Prerequisite: install kubebuilder

### PR DESCRIPTION
**Pull request by ErezArbell**
**Description of the change:**
Add 'install kubebuilder' to list of prerequisites.

**Motivation for the change:**
I see that there is assumption that kubebuilder is installed.  
The command
```
make docker-build docker-push IMG=<some-registry>/<project-name>:<tag>
```
will fail with error 
```failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory```
otherwise.

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Review by camilamacedo86 — CHANGES_REQUESTED** [review]
/hold 

Install Kubebuilder is NOT a pre-requisite for SDK. Also, the future versions of KB will NOT have the EnvTest binaries shipped with the KB binary. Please, see the master version of the doc linked here. 

Then, note that if you use SDK to scaffold your project then all targets which require the binaries will call the tests one. The test target will stall them locally when/if required. See: 

https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/v3/memcached-operator/Makefile#L45-L50

So, if you scaffold the project with an SDK version before the fix then, the solution would fix your Makefile. You can check the samples in the testdata of SDK dir instead. More info: https://github.com/operator-framework/operator-sdk/issues/3461

In this way, IMO we should not move forward with this change. Please, let us know if it makes sense for you and if you are ok in close this PR.

**Comment by ErezArbell** [comment]
Thank you @camilamacedo86.
I am new to operator-framework so I can't even tell I understood all your reply.
(Saying that, I guess I should have search the issues or open one before adding a PR.)

For the issue itself, I followed the tutorial in <https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/> **today** and installed the SDK today. I got the error I wrote in the PR description and it was solved after I installed kubebuilder. So something is still not correct here, right?

You may close this PR if you think this is not the best solution.

**Comment by camilamacedo86** [comment]
Hi @ErezArbell, 

Could you please help us to identify your scenario? Can you raise an issue with that? 
Also, can you provide the versions and etc? It is important for we check out. 

Really thank you for all your collab.
Please, not hesitate to contact us with your problem, ideas and suggestions.
Your collab is more than welcome.  

I hope that it is fine we close this one.

**Comment by ErezArbell** [comment]
I opened issue: https://github.com/operator-framework/operator-sdk/issues/4432

**Pull request closed without merging**
