### PR TITLE
*: updating k8s version references, follow-up from #2083

### PR DESCRIPTION
**Pull request by joelanford**
**Description of the change:**
Update various docs and test scripts to use Kubernetes 1.15

**Motivation for the change:**
Following up on comments from #2083

### CODE REVIEW

**Comment by joelanford** [comment]
/hold
Don't merge until `quay.io/estroz/node:v1.15.4` exists

/cc @estroz

**Comment by estroz** [comment]
@joelanford perhaps the metrics issue wasn't fixed in 1.14?

**Pull request merged**
