### PR TITLE
deps: enable Dependabot to upgrade base images

### PR DESCRIPTION
**Pull request by kd7lxl**
**Description of the change:**

This configures Dependabot (Github feature) to automatically create PRs whenever a newer base image is available.

**Motivation for the change:**

This simplifies the process of switching to a new base image after security patches are released.

Relates to #4763

### CODE REVIEW

**Review by drewwells — APPROVED** [review]

**Comment by jmrodri** [comment]
/hold 

Once this is reviewed by @fabianvf and @estroz we can remove the hold.

**Comment by jmrodri** [comment]
For the record, I am not against this PR :) just don't want it to have any adverse affects on things.

**Comment by estroz** [comment]
@kd7lxl how does dependabot look up viable replacements? For example, ansible-operator's image uses `registry.access.redhat.com/ubi8/ubi:8.3-227` as a base; when `8.3-228` becomes available, would a PR be automatically created? Or when `8.4` is available? More generally, what is the granularity for updates?

**Comment by kd7lxl** [comment]
> @kd7lxl how does dependabot look up viable replacements? For example, ansible-operator's image uses `registry.access.redhat.com/ubi8/ubi:8.3-227` as a base; when `8.3-228` becomes available, would a PR be automatically created? Or when `8.4` is available? More generally, what is the granularity for updates?

I'm just a user, but what I've observed is it seems to pretty well figure out what the greatest version number available following typical SemVer patterns. Here are some example of PRs it created in a repo that uses operator-sdk: https://github.com/infobloxopen/konk/pulls?q=is%3Apr+is%3Aclosed+label%3Adocker

The exact logic is here: https://github.com/dependabot/dependabot-core/blob/main/docker/lib/dependabot/docker/update_checker.rb#L110

Using the dependabot-core dev tools, I ran a dry run and the diff it spit out looks like this:
```
[dependabot-core-dev] ~/dependabot-core $ bin/dry-run.rb --dir images/helm-operator docker operator-framework/operator-sdk
warning: parser/current is loading parser/ruby26, which recognizes
warning: 2.6.7-compliant syntax, but you are running 2.6.6.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
=> fetching dependency files
=> dumping fetched dependency files: ./dry-run/operator-framework/operator-sdk/images/helm-operator
=> parsing dependency files
=> updating 2 dependencies: golang, ubi8/ubi-minimal

=== golang (1.15)
 => checking for updates 1/2
 => latest available version is 1.16.3
 => latest allowed version is 1.16.3
 => requirements to unlock: own
 => requirements update strategy: 
 => updating golang from 1.15 to 1.16.3

    ± Dockerfile
    ~~~
    2c2
    < FROM --platform=$BUILDPLATFORM golang:1.15 as builder
    ---
    > FROM --platform=$BUILDPLATFORM golang:1.16.3 as builder
    ~~~

=== ubi8/ubi-minimal (8.3-230)
 => checking for updates 2/2
 => latest available version is 8.3-298
 => latest allowed version is 8.3-298
 => requirements to unlock: own
 => requirements update strategy: 
 => updating ubi8/ubi-minimal from 8.3-230 to 8.3-298

    ± Dockerfile
    ~~~
    20c20
    < FROM registry.access.redhat.com/ubi8/ubi-minimal:8.3-230
    ---
    > FROM registry.access.redhat.com/ubi8/ubi-minimal:8.3-298
    ~~~
```

**Comment by estroz** [comment]
Daily updates to a version containing a build number happen too frequently. It is probably fine to just pin to major+minor (and patch if available). Then I expect update PRs from this config to happen at an acceptable frequency, and I'd be ok with merging. @jmrodri thoughts?

**Comment by kd7lxl** [comment]
Actual change frequency of these image tags appears to be once every few months, not a daily build:
<a href="https://catalog.redhat.com/software/containers/ubi8/ubi-minimal/5c359a62bed8bd75a2c3fba8?tag=8.3-298&push_date=1617725384000">Screen Shot 2021-04-15 at 4 27 15 PM</a>

`golang` images are released for each patch version.

The `daily` part of the Dependabot config means that it will check for the latest version once per day. If you prefer weekly PRs, `weekly` is another option. More details: https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#scheduleinterval

**Comment by estroz** [comment]
Ah I thought the build number was sequential, but it looks like it skips ahead. In that case I'm fine with this addition as-is. Thanks!

/retest

**Review by estroz — APPROVED** [review]
/lgtm

**Pull request merged**
