### PR TITLE
changelog release 0.15.2

### PR DESCRIPTION
**Pull request by camilamacedo86**
**Description of the change:**
changelog release 0.15.2

### CODE REVIEW

**Comment by joelanford** [comment]
Can you also bump the version number in the SDK installation guide?

**Comment by camilamacedo86** [comment]
Hi @joelanford,

Should we not bump the `version/version.go` as well?

**Comment by joelanford** [comment]
> Should we not bump the version/version.go as well?

No, when doing a patch release, we only need to change that (and change it back) in the release branch, in this case, `v0.15.x`.

**Pull request merged**
