### PR TITLE
refactor cmd/cleanup/packagemanifests to be more testable

### PR DESCRIPTION
**Pull request by jberkhahn**
**Description of the change:**
Refactor cmd/cleanup/packagemanifests to be more testable. This includes breaking up the functionality into validate and run method that can be individually tested.

**Motivation for the change:**
Ongoing work for #3246

### CODE REVIEW

**Comment by jmrodri** [comment]
@jberkhahn can you rebase this PR.

**Comment by jberkhahn** [comment]
@jmrodri done

**Comment by jberkhahn** [comment]
hmm, the PR isn't picking up the updated branch for some reason...

**Comment by jberkhahn** [comment]
Well, this is so much worse

**Comment by camilamacedo86** [comment]
Hi @jberkhahn, 

GH issues :  https://www.githubstatus.com/

**Comment by jberkhahn** [comment]
this seems have to worked itself out by now

**Pull request merged**
