### PR TITLE
Update createdAt when `make bundle` is run

### PR DESCRIPTION
**Pull request by redhatrises**
Signed-off-by: Gabe Alford <redhatrises@gmail.com>

**Description of the change:**
The createdAt field should be updated when `make bundle` is run.

**Motivation for the change:**
Per discussion with the operator-sdk team at KubeCon, having createdAt updated on a `make bundle` is one less thing that has to be manually updated.

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Review by everettraven — CHANGES_REQUESTED** [review]
Thanks for the contribution @redhatrises !

The main change looks great to me, just a couple other things need to get done prior to merging this in:
- Update the unit tests for this change (they are failing due to this key being added to the annotations and the test expectations not matching)
- Regenerate our testdata so that the changes are reflected there as well (should just need to run `make generate` and commit the changes)

**Comment by redhatrises** [comment]
> Thanks for the contribution @redhatrises !
> 
> The main change looks great to me, just a couple other things need to get done prior to merging this in:
> 
> * Update the unit tests for this change (they are failing due to this key being added to the annotations and the test expectations not matching)
> * Regenerate our testdata so that the changes are reflected there as well (should just need to run `make generate` and commit the changes)

Thanks @everettraven!

Question: What would you recommend around the testdata since `createdAt` will be updated with the latest timestamp? Should a CLI flag be created to skip updating `createdAt`? Or......?

**Comment by everettraven** [comment]
>Question: What would you recommend around the testdata since createdAt will be updated with the latest timestamp and fail the git diff? Should a CLI flag be created to skip updating createdAt? Or......?

@redhatrises Ah good question, that had slipped my mind :). 

Thinking a bit about this a bit I think there are 2 potential solutions:
1. We can do the CLI flag like you mentioned.  I think we would like this `createdAt` field to be set, and I can't think of a scenario where an operator author would not like this field automatically set for them. I would *personally* rather not add a new flag unless there is a clear case where it would be used. That being said, I am open to this path if you feel there is a strong case for the flag being added.

2. We can define a constant. As part of the testdata generation process we replace the `createdAt` value in the generated CSV with this constant. This should prevent the `git diff` check from failing solely because of the `createdAt` value.

**Comment by redhatrises** [comment]
> > Question: What would you recommend around the testdata since createdAt will be updated with the latest timestamp and fail the git diff? Should a CLI flag be created to skip updating createdAt? Or......?
> 
> @redhatrises Ah good question, that had slipped my mind :).
> 
> Thinking a bit about this a bit I think there are 2 potential solutions:
> 
> 1. We can do the CLI flag like you mentioned.  I think we would like this `createdAt` field to be set, and I can't think of a scenario where an operator author would not like this field automatically set for them. I would _personally_ rather not add a new flag unless there is a clear case where it would be used. That being said, I am open to this path if you feel there is a strong case for the flag being added.
> 2. We can define a constant. As part of the testdata generation process we replace the `createdAt` value in the generated CSV with this constant. This should prevent the `git diff` check from failing solely because of the `createdAt` value.

Number 2 probably makes more sense then. I assume the constant and code changes for the testdata generation should be under the `hack/` directory?

**Comment by redhatrises** [comment]
@everettraven thanks. I have made updates and tests are passing now.

**Review by everettraven — APPROVED** [review]
@redhatrises The changes look good to me, thanks again for the contribution!

/lgtm

**Pull request merged**
