### PR TITLE
enable ginkgolinter and fix findings

### PR DESCRIPTION
**Pull request by nunnatsa**
## Description of the change
enable [ginkgolinter](https://github.com/nunnatsa/ginkgolinter) and fix findings.

## Motivation for the change
Improve test code quality and prevent some bug, when using ginkgo and gomega.

## Checklist

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Review by varshaprasad96 — APPROVED** [review]
/lgtm

**Comment by varshaprasad96** [comment]
@nunnatsa looks like the scorecard tests are failing. At a glance looks like the changes in scorecard/ files is as expected. This may also be a flake, hence restarting the tests.

**Comment by nunnatsa** [comment]
@varshaprasad96 thsnks. I think this test is broken. It constantly fails in my other pr, and also locally from the master branch.

**Review by everettraven — APPROVED** [review]
Thanks for this PR @nunnatsa! All the changes look good to me!

/lgtm

**Review by everettraven — APPROVED** [review]
/lgtm

**Comment by everettraven** [comment]
Closing and reopening to pick up the docs link fixes

**Comment by nunnatsa** [comment]
Not sure closing and reopening is enough. I'll rebase

**Comment by everettraven** [comment]
@nunnatsa Closing and reopening worked. The current failures are unrelated and shouldn't block this PR

**Comment by nunnatsa** [comment]
rebased anyway. @everettraven - sorry - missed your coment.

**Comment by nunnatsa** [comment]
@varshaprasad96, @grokspawn - could you please take another look?

**Comment by grokspawn** [comment]
/override ansible/e2e-molecule
/override sanity/docs

These are unrelated; tracked separately by #6433 and #6434

**Comment by grokspawn** [comment]
/override docs
/override e2e-molecule

(see above)

**Comment by nunnatsa** [comment]
:tada:

**Pull request merged**
