### PR TITLE
docs: Fix link to the envtest documentation in the v1.0.0 migration guide

### PR DESCRIPTION
**Pull request by timflannagan**
Update the v1.0.0.md migration guide and ensure the link to the envtest
documentation is correctly formatted.

**Description of the change:**

**Motivation for the change:**

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Comment by timflannagan** [comment]
That looks like it can be ignored:

```
  *  External link https://v1-10-x.sdk.operatorframework.io/ failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
             Sometimes, making too many requests at once also breaks things.
             Either way, the return message (if any) from the server is: Couldn't resolve host name
```

**Review by estroz — APPROVED** [review]
/lgtm

**Pull request merged**
