### PR TITLE
Add 'make kustomize' step to Quickstart doc

### PR DESCRIPTION
**Pull request by bentito**
**Description of the change:**

We call for deleting using `kustomize` command line. We have a `make kustomize` step, but the docs are incomplete because they never cause the user to install `kustomize`.

Closes https://github.com/operator-framework/operator-sdk/issues/4362.

**Motivation for the change:**
See description

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Comment by estroz** [comment]
@bentito this is supposed to fix `kustomize build config/default | kubectl delete -f -`? If so, add `make kustomize` above that line in the docs instead of where it currently is.

**Comment by bentito** [comment]
Huh, @estroz , I think the Github-based "Edit this page" link doesn't work as expected. It made me suggest the change to the wrong doc page source. 

This page:

https://sdk.operatorframework.io/docs/building-operators/golang/quickstart/ 

as rendered in my browser, doesn't seem to come from this source: 

https://github.com/operator-framework/operator-sdk/edit/master/website/content/en/docs/building-operators/golang/quickstart.md 

But that is where the "Edit this page" link points. It seems like maybe an outdated Quickstart page is being rendered? 

For instance, in the rendered version there is no mention of the OLM install option.

**Comment by estroz** [comment]
@bentito looks like related docs changes (from #4335) didn't make it into the latest release and therefore don't show up in the latest website. If you go to [the master link](https://master.sdk.operatorframework.io/docs/building-operators/golang/quickstart/#direct-deployment) you'll see the doc you linked. This PR should target branch `v1.3.x` so the latest release's docs are updated.

**Comment by bentito** [comment]
Closing this pull request as the original "thing", kustomize usage for the memcache operator delete before installing it, has been removed from the v1.3.x version of the quickstart docs in favor of a call to: `make undeploy`. Hopefully the rendered version of the quickstart docs will update soon and problem will be solved all around.

**Pull request closed without merging**
