### PR TITLE
[Doc] Added git url release note v1.22.0.md 

### PR DESCRIPTION
**Pull request by Mitulsharma123**
Signed-off-by: Mitulsharma123 <sharmamitul72@gmail.com>

**Description of the change:**
Added missing url for https://github.com/kubernetes-sigs/kubebuilder/pull/2596 in v1.22.0.md 

**Motivation for the change:**
To make documentation readable and precise 

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Review by camilamacedo86 — APPROVED** [review]
/lgtm

**Comment by Mitulsharma123** [comment]
@camilamacedo86 Can it be merged ?

**Review by jmrodri — APPROVED** [review]
/lgtm

**Comment by jmrodri** [comment]
@Mitulsharma123 I merged it. Thanks for the contribution.

**Pull request merged**
