### PR TITLE
Use the old setup logic to work around failing builds

### PR DESCRIPTION
**Pull request by fabianvf**
**Description of the change:**
Move back to manual set up of /etc/passwd

**Motivation for the change:**
/etc/passwd is no longer being properly created

### CODE REVIEW

**Comment by hasbro17** [comment]
@fabianvf I think this fixed the permissions error with the ansible test.

But we're hitting another issue with the e2e-aws-go which seems to be related to #1932 which is the issue with controller-tools not promoting the version specific fields (`subresources`, `schema`, and `additionalPrinterColumns`) to the top level version. 

```
time="2019-09-23T19:31:05Z" level=info msg="Testing operator locally."
time="2019-09-23T19:31:05Z" level=debug msg="Running []string{\"go\", \"test\", \"./test/e2e/...\", \"-namespacedMan\", \"/tmp/namespaced-manifest.yaml335172055\", \"-globalMan\", \"/tmp/global-manifest.yaml120439114\", \"-root\", \"/tmp/tmp.yYLZYf8SBS/memcached-operator\"}"
go: downloading github.com/prometheus/prometheus v1.8.2-0.20190525122359-d20e84d0fb64
go: extracting github.com/prometheus/prometheus v1.8.2-0.20190525122359-d20e84d0fb64
time="2019-09-23T19:31:13Z" level=fatal msg="Failed to create resource(s) in global resource manifest: CustomResourceDefinition.apiextensions.k8s.io \"memcacheds.cache.example.com\" is invalid: [spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:\"v1alpha1\", Served:true, Storage:true, Schema:(*apiextensions.CustomResourceValidation)(0xc009a8d140), Subresources:(*apiextensions.CustomResourceSubresources)(0xc00f33f0c0), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}}: per-version schemas may not all be set to identical values (top-level validation should be used instead), spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:\"v1alpha1\", Served:true, Storage:true, Schema:(*apiextensions.CustomResourceValidation)(0xc009a8d140), Subresources:(*apiextensions.CustomResourceSubresources)(0xc00f33f0c0), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}}: per-version subresources may not all be set to identical values (top-level subresources should be used instead)]"
```

I'm going to bump the SDK to use the latest controller-tools to include the fix #322 for this.

**Comment by hasbro17** [comment]
@fabianvf This will probably need a rebase once #1961 is merged to fix the CRD per-version error in `e2e-aws-go`.

On the bright side since the underlying issue with CRIO seems to be fixed for now, we don't need this as urgently so this can wait until we clear the CI for this.

**Comment by hasbro17** [comment]
I'm seeing this issue again on #1961 so it doesn't seem like it was fixed.

So I've added the changes there to fix `e2e-aws-ansible` and the other CI issues all together.

**Comment by camilamacedo86** [comment]
I think this changes are applied here: https://github.com/operator-framework/operator-sdk/pull/1961.
could we not close this one in prol of this PR?

**Comment by hasbro17** [comment]
Closing in favor of #1961

**Pull request closed without merging**
