### PR TITLE
add marc and move bharathi-tenneti to sdk-emeritus-approvers

### PR DESCRIPTION
**Pull request by camilamacedo86**

### CODE REVIEW

**Review by jmccormick2001 — APPROVED** [review]

**Comment by joelanford** [comment]
Looks like we need to get @marc-obrien added to the org. It's probably best to do that before merging in case that messes up any automation that exists around the OWNERS file (e.g. being added to various CNCF aliases).

NOTE: Marc has been a member of the Red Hat Operator Framework team for over a year and is grandfathered into the GitHub organization and the SDK contributor membership.

**Pull request merged**
