### PR TITLE
Operator developers gets UBI8 based images (for all less Ansible)

### PR DESCRIPTION
**Pull request by camilamacedo86**
**Description of the change:**
Update Go, Helm and scorecard proxy base images to use ubi8 instead of 7. 

**Motivation for the change:**
https://jira.coreos.com/browse/OSDK-512

### CODE REVIEW

**Comment by estroz** [comment]
@AlexNPavel I assume ubi8 is available in the ci cluster?

**Comment by camilamacedo86** [comment]
Hi @estroz, 

Yes, because of this it is passing in the ci. @AlexNPavel added this. Before his PR it was not passing in the prow tests.  I tracked his changes here: https://jira.coreos.com/browse/OSDK-556

**Pull request merged**
