### PR TITLE
Proposal for change of logo position in the readme.

### PR DESCRIPTION
**Pull request by Ankit152**
Hey operator-sdk team! 🙂 

I have a proposal of shifting the logo to the middle. Here is the changes made in the readme file for your kind reference. 
Let me know your thoughts on this.

Signed-off-by: Ankit Kurmi akurmi@redhat.com

### CODE REVIEW

**Comment by asmacdo** [comment]
@Ankit152 looks fine to me, ill bring this up in our community meeting monday

**Comment by asmacdo** [comment]
@Ankit152 please sign the commit for the DCO test

**Comment by Ankit152** [comment]
Hey @asmacdo 🙂 
I installed DCO in my forked repo and again gave the commit by writing `git commit -s -m "placed logo in the middle of the readme"`. Can you help me where I am missing?

**Comment by Ankit152** [comment]
I figured out my way. DCO is signed now! 😄

**Comment by asmacdo** [comment]
You shouldn't need to install DCO in your fork, but glad its working! I've kicked the tests.

**Comment by Ankit152** [comment]
Hey @asmacdo 🙂 
Is there any updates/reviews for this PR? Do let me if there's any.

**Comment by rashmigottipati** [comment]
@asmacdo what have we decided in the community meeting regarding this? 
I think this is only changing the alignment of the logo and not the logo itself.

**Comment by jmrodri** [comment]
While I appreciate the submission, I don't think we should move the logo to the center. I'm closing this PR.

**Pull request closed without merging**
