### PR TITLE
internal/olm/installer: prepend 'v' to semvers >= 0.17.0

### PR DESCRIPTION
**Pull request by estroz**
**Description of the change:** prepend `v` to semver strings passed to `olm` subcommands

**Motivation for the change:** OLM versions now have a `v` prefix.

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Review by varshaprasad96 — APPROVED** [review]

**Review by joelanford — APPROVED** [review]
/lgtm

**Review by camilamacedo86 — APPROVED** [review]
/approve 👍

**Pull request merged**
