### PR TITLE
*: remove `lll` linter

### PR DESCRIPTION
**Pull request by estroz**
**Description of the change:** remove `lll` linter and nolint comments

**Motivation for the change:** based on consensus, the `lll` linter doesn't provide much value since any lines that are quite long tend to be necessarily so. Typically unnecessarily long lines are restricted by PR reviews.

### CODE REVIEW

**Comment by jmrodri** [comment]
For the record I do not approve of removing, but I lost in voting :) just wanted to make sure it was here for posterity.

**Comment by jmrodri** [comment]
> @estroz,
> 
> If we will remove it then, it mean just remove the line https://github.com/operator-framework/operator-sdk/blob/master/hack/tests/check-lint.sh#L64 and add the check-in the line https://github.com/operator-framework/operator-sdk/blob/master/hack/tests/check-lint.sh#L18. All the other changes should be revert.
> 
> IMO we should keep the current comments //nolint:lll to ignore the checks in the required cases since we can always decide came back to use it and then, we also still able to check it with `make lint-dev` as well.

That's a fair statement. Just removing the check but leave the comments.

**Comment by estroz** [comment]
@camilamacedo86 the dev linter is broken for a bunch of code, so I don't see a reason to treat `lll` any different from say `gosec`.

**Comment by camilamacedo86** [comment]
Hi @estroz, 

> @camilamacedo86 the dev linter is broken for a bunch of code

This is its goal. The `make lint-dev` will do all idealistic checks just in dev with things that we could not solved. 

> so I don't see a reason to treat lll any different from say gosec.

if we disabled the gosec, I think we should done the same bisedes this ones has false positives which is not the case for lll

However, the most important for me would not remove all comments to allow we easily came back if we wish.

**Comment by estroz** [comment]
@camilamacedo86 the idealistic check includes `lll` so the dev linter should return errors for "non-ideal" (in someone's opinion) code. Long lines are "non-ideal" in that case -> errors should be returned, so why should we keep these nolint comments?

If we want to add back `lll`, then we should add back these comments, not just have them sitting around in the codebase for no reason. I'd rather not treat one linter differently than another.

**Pull request merged**
