### PR TITLE
Update tutorial.md

### PR DESCRIPTION
**Pull request by w7089**
fix typo

**Description of the change:**

**Motivation for the change:**

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Review by estroz — APPROVED** [review]
/lgtm

**Comment by estroz** [comment]
@w7089 can you add a DCO to your commit?

**Review by camilamacedo86 — COMMENTED** [review]
Could you please check that you need to assign the PR for we are able to get this merge?
See the tests executed. You will find the command line that you need to copy and paste to make that in the DOC check.

**Review by jmrodri — APPROVED** [review]
/lgtm

**Pull request merged**
