### PR TITLE
Update copyrights

### PR DESCRIPTION
**Pull request by briantopping**
Update copyright dates to 2019. Inferred from CR on #1361, feel free to reject if misinterpreted.

### CODE REVIEW

**Comment by briantopping** [comment]
Incorrect branch base in original PR was fixed.

**Comment by briantopping** [comment]
> Hi @briantopping thanks for the PR, but from what I understand there is no need to update copyright, as the year of creation is sufficient.

Thanks @LiliC, I was reacting to the comment from @estroz in https://github.com/operator-framework/operator-sdk/pull/1361/files/b97ca71e03d93ef31484f916e54f2769fb50e9de#r280242743

**Comment by LiliC** [comment]
I am not a lawyer so could be wrong, but according to my experience and quick google search, we should keep the initial copyright year. https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated

But deferring to @estroz.

**Comment by briantopping** [comment]
Got it, thanks. Maybe what needs to be in there is the date range and only create the range when the start date < 2019.

**Comment by joelanford** [comment]
@briantopping based on what @LiliC linked, we've been using the current year for any _new_ files, leaving the year alone in existing files, and not adding ranges when changes span years. I think @estroz suggested 2019 in #1361 because that was a new file.

I'm going to close this since there seems to be a consensus that we should not bump the year on files created in previous years.

**Pull request closed without merging**
