### PR TITLE
Add best practice for designing lean operator

### PR DESCRIPTION
**Pull request by rocrisp**
**Description of the change:**
Add documentation for best practices for designing lean operator.
#5382

**Motivation for the change:**

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Review by asmacdo — COMMENTED** [review]
I think this doc needs to mention that filtered caches make the filtered-out objects invisible to the client. That might be unexpected so we'll want to highlight that.

**Comment by rocrisp** [comment]
true true.

**Comment by asmacdo** [comment]
@rocrisp you will need a signature to pass CI. [more info](https://github.com/operator-framework/operator-sdk/pull/6164/checks?check_run_id=9396845811)

Content is great thank you!
/lgtm

**Review by varshaprasad96 — APPROVED** [review]
Looks good! Thanks @rocrisp!
/lgtm

**Comment by rocrisp** [comment]
I signed the commit and force pushed. Hope I didn't break anything.

**Comment by everettraven** [comment]
@rocrisp it looks like the DCO check is still failing. Looking at the DCO check steps you should be able to do:
1. `git rebase HEAD~2 --signoff`
2. `git push --force-with-lease origin <branch-name>`

I hope this helps!

**Comment by rocrisp** [comment]
@everettraven  Worked this time. Thank you.

**Review by everettraven — APPROVED** [review]
/lgtm

**Pull request merged**
