### PR TITLE
images: install Python kubernetes-validate in Ansible images

### LINKED ISSUE #2433: Install Python dependency in Ansible Operator image to validate managed resources
## Feature Request

**Is your feature request related to a problem? Please describe.**
I would like to use the k8s validate feature introduced in Ansible version 2.8. This will allow me to validate the native Kubernetes resources managed by my operator. Currently this is not possible since the required Python module (`kubernetes-validate`) is not installed in the ansible-operator image.

**Describe the solution you'd like**
Install the `kubernetes-validate` Python module with pip3 alongside `openshift` in https://github.com/operator-framework/operator-sdk/blob/aa1c5ea2fbb0c300b24810ba8031ad2871c296a8/ci/dockerfiles/ansible.Dockerfile#L32

I will prepare a PR.

### PR DESCRIPTION
**Pull request by erikgb**
this allows usage of the validation feature in Ansible k8s module

Fixes #2433

**Description of the change:**

**Motivation for the change:**

### CODE REVIEW

**Comment by erikgb** [comment]
On second thought I think the dependency to kubernetes-validate should be unpinned to version. This will require less effort supporting newer Kubernetes versions. I'll fix/update.

**Comment by asmacdo** [comment]
Thanks for the issue and PR!  You should be able to any deps you need in your `build/Dockerfile`. 

https://github.com/operator-framework/operator-sdk/blob/master/doc/faq.md#my-ansible-module-is-missing-a-dependency-how-do-i-add-it-to-the-image

I'm closing for now to keep the base image minimal feel free to reopen if you would like more discussion.

**Comment by erikgb** [comment]
@asmacdo : I do fully understand why you want to keep the base image as small as possible. It's just that without this Python dependency you cannot use the full feature set of the k8s Ansible module - which is already pre-installed in the base image - and this does not seem right to me. We are using the base image as is, and would prefer to avoid the maintenance overhead with adding our own layer to this image. And my guess is that this is quite common for Ansible-based operators?

**Comment by asmacdo** [comment]
On hold until discussion https://github.com/operator-framework/operator-sdk/issues/2433 is resolved

**Comment by asmacdo** [comment]
@erikgb, assuming that the discussion #2433 ends favorably, we would still want to pin.

**Comment by erikgb** [comment]
Closing, as an additional dependency is not welcomed by the core team.

**Pull request closed without merging**
