### PR TITLE
Post-release v1.2.0

### PR DESCRIPTION
**Pull request by estroz**
**Description of the change:** post release v1.2.0

**Motivation for the change:** post release

Note: I need to add add a separate sanity check for release tags that takes into account annotation version changes.

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Review by jmrodri — APPROVED** [review]
/lgtm

**Review by camilamacedo86 — APPROVED** [review]
/lgtm

**Comment by estroz** [comment]
Superseded by #4213

**Pull request closed without merging**
