### PR TITLE
cmd/.../genutil: fix typo in comment

### PR DESCRIPTION
**Pull request by johananl**
**Description of the change:**

Fix typo in the `generateWithHeaderFile` comment.

**Motivation for the change:**

"arguemnt" isn't a valid English word.

### CODE REVIEW

**Comment by johananl** [comment]
Not sure why the Travis job failed. Maybe it's unstable?

**Comment by joelanford** [comment]
@johananl Yeah, it's flaky. We can babysit it until it passes.

**Comment by joelanford** [comment]
@johananl If you can fix the merge conflict, I can LGTM again and see if we can get the tests to pass this time around. Sorry about the flakes on a change that obviously won't break anything!

**Comment by johananl** [comment]
@joelanford done. Let's hope CI passes this time.

**Pull request merged**
