### PR TITLE
Pin docker base images

### PR DESCRIPTION
**Pull request by reinvantveer**
**Description of the change:**
Pin Docker base images for Ansible operator and Helm operator 

**Motivation for the change:**
Pinning Docker images reduces the chance of facing a dependency conflict resulting from differences in base images. "Latest" base image bugs are very hard to discover - the user may have pulled a newer image without knowing.

This merge request is in response to in accordance with https://github.com/operator-framework/operator-sdk/pull/4413#issuecomment-764811597 and is part of addressing the discussion in issue #4237 

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [x] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Comment by reinvantveer** [comment]
@estroz @dalbani

**Review by estroz — COMMENTED** [review]
@reinvantveer mind pinning all the other ubi images in `images/` while you're at it?

**Comment by reinvantveer** [comment]
Consider it pinned :P

**Review by estroz — APPROVED** [review]
/lgtm

**Review by jmrodri — APPROVED** [review]
/lgtm

**Comment by reinvantveer** [comment]
Good to see progress on this!

**Pull request merged**
