### PR TITLE
add gcc to image dependencies, so it can be used to fully run operator-sdk cli

### PR DESCRIPTION
**Pull request by rccrdpccl**
Closes 6171

**Description of the change:**

Added GCC to dependencies

**Motivation for the change:**

operator-sdk cli is not fully functional without it with default settings if run through docker image

For more details see #6171 

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Review by everettraven — APPROVED** [review]
@rccrdpccl Great catch! Thanks for contributing the fix!

/lgtm

**Review by theishshah — APPROVED** [review]
/lgtm

**Comment by theishshah** [comment]
Re-running the docs test as it seemed to have a link response time flake, should be good to merge once that passes. Thanks for the contribution!

**Comment by rccrdpccl** [comment]
externals urls in docs were timing out, it seems that they are working from my location now
/retest

**Pull request merged**
